### PR TITLE
#1992 undefined objects in cell actions

### LINKED ISSUE #1992: TypeError in MainActivity
## Error in mSupply Mobile

**TypeError** in **MainActivity**
undefined is not an object (evaluating 'k.expiryDate=t')

[View on Bugsnag](https://app.bugsnag.com/sustainable-solutions-nz-ltd/msupply-mobile/errors/5e297e84edd555001a10a9ba?event_id=5e297e840056038d67e40000&i=gh&m=ci)

## Stacktrace

    src/pages/dataTableUtilities/actions/cellActions.js:64 - 
    src/hooks/index.js:11 - value
    src/pages/dataTableUtilities/actions/cellActions.js:63 - 
    src/pages/dataTableUtilities/getPageDispatchers.js:89 - onEditDate
    src/images/flags/gil.png:1 - V

[View full stacktrace](https://app.bugsnag.com/sustainable-solutions-nz-ltd/msupply-mobile/errors/5e297e84edd555001a10a9ba?event_id=5e297e840056038d67e40000&i=gh&m=ci)

*Created automatically via Bugsnag*

### PR DESCRIPTION
**Pull request by joshxg**
Fixes #1992 

## Change summary

- This actually occurs when you're mid-editing a cell and navigate back.
- You basically have to be spamming a cell with text and clicking back at the same time, so not tooo bad

## Testing

- [ ] Edit a cell by repeat spamming constantly, and then with your other hand navigate back - the app should not crash.

### Related areas to think about

I mean, the codes not pretty but 🤷‍♂ 

Ideally, there would be a `ERROR` action which would be dispatched in the else - which wouldn't do anything, but potentially logs in the future

### CODE REVIEW

File: src/pages/dataTableUtilities/actions/cellActions.js [hunk 1]
```diff
@@ -44,12 +44,14 @@ export const editBatchName = (value, rowKey, objectType, route) => (dispatch, ge
 
   const objectToEdit = data.find(row => keyExtractor(row) === rowKey);
 
-  const { batch } = objectToEdit;
+  if (objectToEdit) {
+    const { batch } = objectToEdit;
```
Comment (wlthomson) [inline src/pages/dataTableUtilities/actions/cellActions.js]: Nit: could use null coalescing here?

```
const batch = objectToEdit?.batch;
```
