### PR TITLE
#3015 fix insurance policy outgoing sync formatting

### LINKED ISSUE #3015: Insurance: "-" should not be added in absence of Family Policy Number
## Describe the bug

"-" should not be added in absence of Family Policy Number

### To reproduce

1. Go to Mobile apk -> create a Prescription
2. Add an insurance such that Family Policy number is blank/empty
3. Finalize and sync
4. GO to Desktop store. Check the following prescription
4. See error. "-" is shown as prefix to Personal Policy Number
Screen Shot 2020-07-10 at 12 02 12 PM

### Expected behaviour

"-" should be removed in absence of Family Policy Number

### Proposed Solution

Leave if you don't know how to fix/implement. Edit this issue description and explain here if you know the best path of implementing the fix within the codebase.

### Version and device info

- App version: 5.1.1
- Tablet model:
- OS version:

### Additional context

arises while testing #2918

### PR DESCRIPTION
**Pull request by wlthomson**
Fixes #3015.

## Change summary

Fixes formatting of policy numbers synced from mobile to desktop.

## Testing

Steps to reproduce or otherwise test the changes of this PR:

- [ ] Policies with personal numbers are correctly formatted after being synced from mobile to desktop  (`familyNumber-personalNumber`).
- [ ] Policies without personal numbers are correctly formatted after being synced from mobile to desktop  (`familyNumber`).

### Related areas to think about

N/A.

### CODE REVIEW

File: src/database/DataTypes/InsurancePolicy.js [hunk 1]
```diff
@@ -2,7 +2,8 @@ import Realm from 'realm';
 
 export class InsurancePolicy extends Realm.Object {
   get policyNumber() {
-    return `${this.policyNumberPerson} ${this.policyNumberFamily}`;
+    if (!this.policyNumberPerson) return this.policyNumberFamily;
```
Comment (joshxg) [inline src/database/DataTypes/InsurancePolicy.js:5]: both values are required in the schema aren't they? 

https://github.com/openmsupply/mobile/blob/d515a274516ae0b1b434add43eb967e4d94f8ad4/src/database/DataTypes/InsurancePolicy.js#L15-L16

🤔

Comment (wlthomson) [reply src/database/DataTypes/InsurancePolicy.js:5]: Yeah, I believe that just means it can't be set to `null` or `undefined`? As it's a primitive I think it makes more sense to have it initialised to a falsey but non-null value? 

To make it more explicit can do:

```
policyNumberPerson: { type: 'string', default: '' };
```

but I think the above is equivalent to the existing declaration?

Comment (joshxg) [reply src/database/DataTypes/InsurancePolicy.js:5]: I didn't know so I did a quick test with:

```
UIDatabase.write(() => {
      const insuranceProvider = UIDatabase.update('InsuranceProvider', {
        id: '1',
      });

      UIDatabase.update('InsurancePolicy', { id: '1', insuranceProvider });
    });
```

And got the error "Missing value for property `InsurancePolicy.policyNumberFamily`" - so I believe you need to explicitly set the default. Also doesn't say anything in the docs about defaults being set for primitives automatically: https://realm.io/docs/javascript/latest/#default-property-values

Comment (wlthomson) [reply src/database/DataTypes/InsurancePolicy.js:5]: Oops, looks like I misinterpreted the examples in the [docs](https://realm.io/docs/javascript/latest/#models) (I guess that includes implicitly on construction).

eeb4b8c36cbd900662740f69499455cbffe7d945.
