### PR TITLE
#1198 StocktakeManagePage fixes -- 4

### LINKED ISSUE #1198: DataTable StocktakeManagePage fixes
## Describe the bug

Comments in PR #1191 

Also ensure all handlers are declared and memoized

### Additional context

N/A

### PR DESCRIPTION
**Pull request by joshxg**
### NOTE: Branch not runnable due to many files being shifted - branch at #1224 is when the app is runnable again.

Fixes #1198 

## Change summary

- Fixes PR comments:
- added doc strings to `navigation/actions`
- added doc string to `Stocktake` getter
- Added a `stateInitialiser` function
- Added explicitly defined callbacks
- Added `toggleStockOut` and `toggleAll` ActionCreators

## Testing
See #1043 

### Related areas to think about

- I think `toggleStockout` and `toggleAll` being in different files means my groupings aren't correct :(

### CODE REVIEW

File: src/navigation/actions.js [hunk 1]
```diff
@@ -126,35 +143,27 @@ export const createSupplierRequisition = ({
...
+    else if (itemIds) stocktake.setItemsByID(UIDatabase, itemIds);
+  });
 
-  const navigationAction = NavigationActions.navigate({
-    routeName: 'customerInvoice',
-    params: {
-      title: `${navStrings.invoice} ${transaction.serialNumber}`,
-      transaction,
-    },
+  const replaceAction = StackActions.replace({
```
Comment (joshxg) [inline src/navigation/actions.js]: poor naming - `navigationReplaceAction`, `stackReplacementAction`?

File: src/navigation/actions.js [hunk 2]
```diff
@@ -172,3 +181,20 @@ export const createCustomerInvoice = (otherParty, currentUser) => dispatch => {
...
   dispatch(gotoCustomerInvoice(newCustomerInvoice));
 };
+
+/**
+ * Updates a Stocktake with the passed array of itemIDs and navigates to a
+ * StocktakeEditPage.
+ *
+ * @param {Object} stocktake realm Stocktake object
+ * @param {Array}  itemIds   Array of item id strings that should be the new
+ *                           Items in the stocktake.
```
Comment (joshxg) [inline src/navigation/actions.js]: Maybe make it more clear here what `setItemsByID` is doing

File: src/pages/StocktakeManagePage.js [hunk 3]
```diff
@@ -9,148 +9,138 @@ import React, { useCallback, useEffect } from 'react';
...
+  routeName,
+  dispatch: reduxDispatch,
+  stocktake,
+  runWithLoadingIndicator,
+}) => {
+  const [state, dispatch, instantDebouncedDispatch, debouncedDispatch] = usePageReducer(
+    routeName,
+    {},
+    stateInitialiser,
+    stocktake
```
Comment (joshxg) [inline src/pages/StocktakeManagePage.js]: I think `usePageReducer` could be changed:

`usePageReducer(routeName, initialValue, initialiser)` - such that if `initialiser` is passed, `initialValue` is the input - otherwise just use `initialValue` as the initial state.

File: src/pages/StocktakeManagePage.js [hunk 4]
```diff
@@ -163,16 +153,19 @@ export const StocktakeManagePage = ({
       <View style={newPageTopSectionContainer}>
         <View style={newPageTopLeftSectionContainer}>
           <SearchBar
-            onChange={value => debouncedDispatch(filterData(value))}
+            onChangeText={value => debouncedDispatch(PageActions.filterData(value))}
             style={searchBar}
             color={SUSSOL_ORANGE}
             placeholder=""
```
Comment (joshxg) [inline src/pages/StocktakeManagePage.js]: using default props here

File: src/navigation/actions.js (hunk 1 above)
Comment (mark-prins) [reply src/navigation/actions.js]: +1 for `stackReplacementAction`

File: src/navigation/actions.js [hunk 5]
```diff
@@ -126,35 +143,27 @@ export const createSupplierRequisition = ({
...
-  if (!isConfirmed && !isFinalised) {
-    UIDatabase.write(() => {
-      transaction.confirm(UIDatabase);
-      UIDatabase.save('Transaction', transaction);
-    });
-  }
+  UIDatabase.write(() => {
+    stocktake = createRecord(UIDatabase, 'Stocktake', currentUser, stocktakeName, program);
+    if (program) stocktake.addItemsFromProgram(UIDatabase);
+    else if (itemIds) stocktake.setItemsByID(UIDatabase, itemIds);
```
Comment (mark-prins) [inline src/navigation/actions.js]: the items from program is 'add' and the other is 'set'
but within `setItemsByID` it talks about `itemsToAdd` and creates records. I'd suggest changing that one to `addItemsById`

File: src/navigation/actions.js (hunk 2 above)
Comment (mark-prins) [reply src/navigation/actions.js]: renaming the method might be enough

File: src/pages/StocktakeManagePage.js [hunk 6]
```diff
@@ -9,148 +9,138 @@ import React, { useCallback, useEffect } from 'react';
...
+    () => (
+      <DataTableHeaderRow
+        columns={columns}
+        dispatch={instantDebouncedDispatch}
+        sortAction={PageActions.sortData}
+        isAscending={isAscending}
+        sortBy={sortBy}
+      />
+    ),
+    []
```
Comment (mark-prins) [inline src/pages/StocktakeManagePage.js]:
```suggestion
    [sortBy, isAscending]
```
