### PR TITLE
#2242 add service price cash transaction offset

### LINKED ISSUE #2242: Totals for a cash transaction offset (CCs/CIs) get cleared when opened on server
## Describe the bug
Wasn't sure whether this should be on desktop issue or mobile, but this doesn't happen for transactions made on desktop: 

When I make a transaction on the cash register in mobile, I can see it on desktop: 
image

I can also see the offset transaction created from it (in this case a cc/ customer credit)
image

If I open the transaction and close it again, the total is set to 0: 
image

### To reproduce

1. Create a cash transaction through the cash register in mobile. Sync to desktop
2. On desktop, log into the mobile store. Check the cash register. Make sure the total is correct. 
3. Find the customer credit or customer invoice created from the cash transaction you made on mobile. Open it and close it. 
4. Now check the total of that customer credit/customer invoice. 

### Expected behaviour

The values should remain the same 

### Proposed Solution

Leave if you don't know how to fix/implement. Edit this issue description and explain here if you know the best path of implementing the fix within the codebase.

### Version and device info

- App version: 4.0.0 RC4
- Tablet model:
- OS version:

### PR DESCRIPTION
**Pull request by wlthomson**
Fixes #2242.

## Change summary

- Syncs the `service_price` field.
- Fixes precision errors caused by `float` datatypes.

## Testing

Steps to reproduce or otherwise test the changes of this PR:

- [ ] Create a new cash in transaction and sync to desktop. Open and close the associated customer invoice on desktop. The `total` should not revert to `0`.
- [ ] Create a new cash out transaction and sync to desktop. Open and close the associated supplier invoice on desktop. The `total` should not revert to `0`.

### Related areas to think about

N/A.

### CODE REVIEW

File: src/sync/outgoingSyncUtils.js [hunk 1]
```diff
@@ -177,6 +177,7 @@ const generateSyncData = (settings, recordType, record) => {
       };
     }
     case 'Transaction': {
+      console.log(record.servicePrice);
```
Comment (joshxg) [inline src/sync/outgoingSyncUtils.js]: !
