### PR TITLE
#1102 foreign item lines IC special

### LINKED ISSUE #1102: Foreign Item Lines
## Describe the bug

Before there was a fix for #1062 it was possible to sync foreign item lines to mobile store, this cause a few issue in IC. 
Foot runner code was originally executed that caused deletion of foreign item lines, causing #1088
We don't actually know if some of the sites that have not been synced yet need to be fixed by foot runner code.

### Proposed solution

Do migration code (specific for IC) that looks through all item batches, identifies them as foreign and deletes them. Followed by running this migration code https://github.com/openmsupply/mobile/pull/1094

### Version and device info

- App version: 2.3.0

### Additional context

A special RC version should be made for this migration code (2.3.5-RC1) <- maybe better named

#### How to find foreign item line ?

* First transaction is supplier invoice (finalised on)
* First transaction is inventory adjustment coming from a stock take where snap shot quantity was 0 (can deduce this through code)

### PR DESCRIPTION
**Pull request by andreievg**
Fixes #1102 

## Change summary

It's hard to identify the 'first' transaction (since confirmDate lacks the time if tablet was reinitialised or created from desktop site)
So instead, look at all of the transactionBatches for an itemBatch:
* If we find one that belongs to supplier invoice, then don't delete
* Look at all of the addition inventory adjustments
  * If inventory adjustment doesn't have stock take, don't delete (Mobile site must have been created from a desktop site, and stock was increased with just inventory adjustments, take not that mobile does not integrate foreign transactions)
  * If inventory adjustment does have a stock take, find StocktakeBatch that references current itemBatch and see if it's an increasing record from 0 snapshot, if so then don't delete
* Delete every ItemBatch that wasn't skipped
* Delete from sync out the fresh deletions
* Make sure transaction batches have itemBatch (@joshxg PR that i'am branching from)

## Testing

Steps to reproduce or otherwise test the changes of this PR:

- [ ] - Sync a mobile store with version <= 2.3.5
- [ ] - Run this foot runner code:
```
QUERY([item_line];[item_line]store_ID={foreignStoreID})
REDUCE SELECTION([item_line];1)
sync_generate_sync_record (Table(->[item_line]);"I";12;"";{syncSiteID};{mobileStoreID})
```
- [ ] - Sync the tablet, you will see you have a foreign Item Line (check stock page in mobile)
- [ ] - Upgrade to this version
- [ ] - Item Line should be deleted

To fully test though, before the upgrade step, do the following
- [ ] - Create stock takes, with increasing and decreasing stock lines for this item line (finalise them)
- [ ] - Create a stock take but don't finalise (with this item line)
- [ ] - Create reducing customer invoices with this item line
- [ ] - Upgrade
- [ ] - Make sure the customer invoices you've entered can be opened, also make sure all of the stock takes created with item line can be opened, and in un finalised stock take can still edit counted quantities etc (and can finalise)

### Related areas to think about

The branch this PR is going into will be IC specific.

@mark-prins, this is the fix, we need to test it a little bit further (tonight) and make a release for you.
A few more conditions then i though (due to not being able to find the 'first' transaction for the itemLine and some mobile sites were created from desktop sites)

### CODE REVIEW

File: src/database/migration/v2.js [hunk 1]
```diff
@@ -133,8 +136,80 @@ const v2Migrations = [
     },
   },
   {
-    version: '2.3.6',
+    version: '2.3.6-IC1',
     migrate: database => {
+      // *** PART ONE, find foreign item line and delete
+
+      const itemBatches = this.database.objects('ItemBatch').snapshot();
+      const itemBatcheIDsToDelete = [];
```
Comment (joshxg) [inline src/database/migration/v2.js]: `itemBatchIDsToDelete` hehe

File: src/database/migration/v2.js [hunk 2]
```diff
@@ -133,8 +136,80 @@ const v2Migrations = [
...
+        if (transactionBatches.length === 0) {
+          itemBatcheIDsToDelete.push(id);
+          return;
+        }
+        // supplier_invoice type transactions are all addition transactions
+        const additionTransactionBatches = transactionBatches.filtered(
+          'transaction.type = "supplier_invoice"'
+        );
+        // First try to find supplier invoice, if found this must be a local ItemBatch
+        const supplierInvoiceBatches = additionTransactionBatches.filtered(
```
Comment (joshxg) [inline src/database/migration/v2.js]: This is just an extra check? If there is a supplier invoice for the batch it is local? Or i'm missing something?

File: src/database/migration/v2.js [hunk 3]
```diff
@@ -133,8 +136,80 @@ const v2Migrations = [
...
+          'transaction.otherParty.id != $0',
+          inventoryAdjustmentName.id
+        );
+        if (supplierInvoiceBatches.length > 0) return;
+
+        // Find all 'addition' inventory adjustments
+        const additionInventoryAdjustemnetBatches = additionTransactionBatches.filtered(
```
Comment (joshxg) [inline src/database/migration/v2.js]: `const additionInventoryAdjustmentBatches` hehe also this is the same query as for supplier invoices above? I think this is meant to be just for addition transaction batches not specifically

**Comment by andreievg** [comment]
Opening finalised stock take with delete item batch breaks things

**Comment by andreievg** [comment]
Un-finalise customer invoice with deleted batch, still shows that we can issue stock : /

**Comment by andreievg** [comment]
Consumption for that item disappears (I think we need to associated item with newly created itembatch)

File: src/database/migration/v2.js (hunk 3 above)
Comment (joshxg) [reply src/database/migration/v2.js]: im stupid

**Comment by andreievg** [comment]
oops that last commit has completely wrong comment

File: src/database/migration/v2.js (hunk 2 above)
Comment (andreievg) [reply src/database/migration/v2.js]: Yeah, if there is supplier invoice, must be local item batch, since it was created via supplier invoice

File: src/database/migration/v2.js (hunk 1 above)
Comment (andreievg) [reply src/database/migration/v2.js]: dbfe6d34603ec76292aa71fb677e995e6b6efaf4
