### PR TITLE
#1902 fix supplier requisition no indicator error

### LINKED ISSUE #1902: Non-indicator supplier requisitions throw error
Creating a new general requisition or non-indicator program requisition throws an error on latest `feature/hiv-indicators` branch.

#1902-fix-supplier-requisition-no-indicator-error

### PR DESCRIPTION
**Pull request by wlthomson**
Fixes #1902.

## Change summary

Adds `usingIndicators` prop to `SupplierRequisition` to prevent error when creating non-indicators requisitions.

## Testing

Steps to reproduce or otherwise test the changes of this PR:

- [ ] Can successfully create a supplier requisition for a program with no indicator data.
- [ ] Can successfully create a non-program supplier requisition.

### Related areas to think about

N/A.

### CODE REVIEW

File: src/pages/SupplierRequisitionPage.js [hunk 1]
```diff
@@ -351,8 +352,11 @@ const mapDispatchToProps = (dispatch, ownProps) => {
 const mapStateToProps = state => {
   // TODO: add indicator toggle flag to page state.
```
Comment (joshxg) [inline src/pages/SupplierRequisitionPage.js]: TODO's suck change my mind

laugh-fifty

Comment (wlthomson) [reply src/pages/SupplierRequisitionPage.js]: c38bc97f26aa8cf9d1a2a0b788fea0258dc0cf4f.

damn
