### PR TITLE
#3018 fix insurance form policy number enforcement

### LINKED ISSUE #3018: Insurance form incorrectly enforces personal number instead of family number
## Describe the bug

The insurance form config incorrectly specifies personal number as required instead of family number. 

### To reproduce

1. Create a new insurance policy in the dispensing window.
2. See error

### Expected behaviour

Family policy number should be enforced as required (personal as optional).

### Proposed Solution

Update `formInputConfigs`.

### Version and device info

- App version: v5.1.1.
- Tablet model: Nexus 10 (Android emulator).
- OS version: API 28.

### Additional context

N/A.

### PR DESCRIPTION
**Pull request by wlthomson**
Fixes #3018.

## Change summary

Fix personal instead of family policy number being enforced.

## Testing

Steps to reproduce or otherwise test the changes of this PR:

- [ ] Can create insurance policies without a personal policy number.
- [ ] Cannot create insurance polices without a family policy number.

### Related areas to think about

N/A.

### CODE REVIEW

File: src/utilities/formInputConfigs.js [hunk 1]
```diff
@@ -186,7 +186,7 @@ const FORM_INPUT_CONFIGS = seedObject => ({
     initialValue: '',
     key: 'policyNumberFamily',
     validator: input => input.length >= 0 && input.length < 50,
-    isRequired: false,
+    isRequired: true,
```
Comment (joshxg) [inline src/utilities/formInputConfigs.js:189]: oh same as in the other PR, isn't this required in the schemaaaaa

Comment (wlthomson) [reply src/utilities/formInputConfigs.js:189]: Yeah, I think this one is OK (required in schema and in input config)?

Comment (joshxg) [reply src/utilities/formInputConfigs.js:189]: lol oops :)
