### PR TITLE
#1400 column header spacing

### LINKED ISSUE #1400: Column headers not great when not english
## Describe the bug

Column headers aren't looking great when not in english

### To reproduce

1. Go to supplier/customer requisitions or stocktake edit page in french/laos/kiribati

### Expected behaviour

Should look good

### Version and device info

2.3.6 development

### Additional context

image

image

image

Tetum/English are fine

### PR DESCRIPTION
**Pull request by joshxg**
Fixes #1400 

## Change summary

- Added some explicit new lines in a few strings
- Changed margin on right aligned cells to give a bit more space
- Added a few french translations

Kiribati/laos customer requisitions still doesn't look good. The strings are long, I think it would require increasing the size of the header row by about 50%. I think we could look into making sure the translations are correct and are as short as possible before doing that. Especially considering a couple strings have `?` at the end, as if the translations weren't actually complete and a bit of guessing was going on?

## Testing

- [ ] Customer requisition page in particular looks fine in english/french (Was the focus of the PR in the end)
- [ ] Hide/show over stock toggle in french looks fine

### Related areas to think about

Need to update a lot of translations. There is a veyr old issue here #484 which I think is worth doing. Wouldn't take long and would be super helpful!

image

image

image

### CODE REVIEW

File: src/localization/buttonStrings.js [hunk 1]
```diff
@@ -27,9 +27,9 @@ export const buttonStrings = new LocalizedStrings({
     view_regimen_data: 'View Regimen Data',
   },
   fr: {
-    // TODO: view_regimen_data
+    view_regimen_data: 'Données de régimes',
     add_batch: 'Ajouter un lot',
-    add_master_list_items: "Ajouter une liste-Maître d'articles ?",
+    add_master_list_items: 'Ajouter à\npartir des\nlistes maîtres',
```
Comment (wlthomson) [inline src/localization/buttonStrings.js]: Noticed this translation has changed. Just checking this is the correct translation?

Comment (wlthomson) [inline src/localization/buttonStrings.js]: I think can get away with a single newline here:

```suggestion
    add_master_list_items: 'Ajouter à partir\ndes listes maîtres',
```

Before:

#1400-column-header-spacing-1

After:

#1400-column-header-spacing-2

Comment (joshxg) [reply src/localization/buttonStrings.js]: oops sorry I meant to put that in the top comment. I took this translation for desktop explicitly. The `?` tipped me off it may not have been translated correctly:

Original: Ajouter une liste-Maître d'articles -- Add a master list of articles
New: Ajouter à partir des listes maîtres -- Add from master lists

@alainsussol this is correct? :)

Comment (joshxg) [reply src/localization/buttonStrings.js]: Ah nice thanks - f83afcc

Comment (wlthomson) [reply src/localization/buttonStrings.js]: Google translate says you're right 😄 . For sake of getting `v3.0.0` out, will merge (can always fix later, if needed 👍 ).

**Comment by joshxg** [comment]
have fixed conflicts

File: src/localization/buttonStrings.js (hunk 1 above)
Comment (alainsussol) [reply src/localization/buttonStrings.js]: Yes this is correct...
