### PR TITLE
#2515 supplier requisition is visible undefined

### LINKED ISSUE #2515: Supplier requisition isVisible is undefined
## Describe the bug

When creating a new program or general supplier requisition, the `isVisible` prop is `undefined`.

### To reproduce

1. Go to `Supplier Requisitions` -> `New Requisition` -> `General order`.
2. Click on `"Select a supplier"`.
3. See error.

### Expected behaviour

`isVisible` should be correctly defined.

### Proposed Solution

Define `isVisible` prop.

### Version and device info

- App version: v4.0.1.
- Tablet model: Android emulator.
- OS version: API 28.

### Additional context

N/A.

### PR DESCRIPTION
**Pull request by wlthomson**
Fixes #2515.

## Change summary

Just a small prop typo.

## Testing

Steps to reproduce or otherwise test the changes of this PR:

- [ ] No warning `isVisible` prop is undefined when selecting a supplier for a new supplier requisition.

### Related areas to think about

N/A.

### CODE REVIEW

File: src/widgets/modals/ByProgramModal.js [hunk 1]
```diff
@@ -1,4 +1,5 @@
 /* eslint-disable react/forbid-prop-types */
+/* eslint-disable import/no-named-as-default */
```
Comment (joshxg) [inline src/widgets/modals/ByProgramModal.js]: Bit nicer to just fix the import - just putting `{ ModalContainer }` on the import

Comment (wlthomson) [reply src/widgets/modals/ByProgramModal.js]: Yeah, didn't really want to touch files that aren't in scope (`ModalContainer` component is only default exported). Not a big worry! ffd584e08ae86b2c3562b9aaf4175965361ffc7b.

**Comment by Rebecca367** [comment]
It's good to have capacity to read through all these issues/PR to know what's going on in mSupply / mSupply mobile.
