### PR TITLE
#1335 Stocktakename cant be updated

### LINKED ISSUE #1335: StocktakeManagePage confirmation modal not updating stocktake name
## Describe the bug

When updating a stocktake, the confirm modal prompts the user to update the stocktake name. After entering a new name, the stocktake does not update.

### To reproduce

1. Go to "Stocktakes".
2. Click on an existing stocktake or create a new one.
3. Click "Manage stocktake".
4. Select one or more rows, the confirmation modal should prompt you to update the stocktake name.
5. Update the stocktake name. You will be navigated back to the stocktake page.
6. Note that the stocktake name has not updated.

### Expected behaviour

The stocktake name should update.

### Version and device info

- App version: 2.3.7.
- Tablet model: TB-X304L (replicated with emulator).
- OS version: 8.1.0.

### Additional context

See https://github.com/openmsupply/mobile/issues/1241#issuecomment-540257131.

### PR DESCRIPTION
**Pull request by joshxg**
Fixes #1335 

## Change summary

- Added updating of name from stocktake manage page via redux
- Added onpress event for the name page info on `StocktakeEditPage`

Note: This does fix the page info problem described in #1343 also, as  it was easier to just do it here

Seems I just completely forgot about this..

## Testing
- [ ] Updating the stocktake name in stocktake manage page correctly updates the name
- [ ] Updating the stocktake name in `StocktakeEditPage` correctly updates the name

### Related areas to think about

N/A

### CODE REVIEW

File: src/navigation/actions.js [hunk 1]
```diff
@@ -254,9 +254,12 @@ export const createSupplierInvoice = (otherParty, currentUser) => dispatch => {
  * @param {Object} stocktake realm Stocktake object
  * @param {Array}  itemIds   Array of item id strings that should be the new
  *                           Items in the stocktake.
+ *  * @param {String} name   Name of the stocktake for updating. Cannot update to remove completely.
```
Comment (wlthomson) [inline src/navigation/actions.js]: Is the indent and extra `*` intentional?

Comment (joshxg) [reply src/navigation/actions.js]: special one 
82fc96e

**Comment by joshxg** [comment]
I agree

**Comment by wlthomson** [comment]
> I agree

Nice.
