### PR TITLE
#1899 Change the way values are being obtained from data

### LINKED ISSUE #1899: Change values to values[0] in the data prop
## Describe the bug

Data coming from the `json` object includes values, which are not being properly obtained the way it is setted right now. 

### Expected behaviour

Charts should be rendered properly (it is not working right now).

### Proposed Solution

Change data props of `PieChart`, `BarChart`, `LineChart` components from `data = { values }` to `data = { values[0] }`

### Additional context

No need to modify `TableReport`

### PR DESCRIPTION
**Pull request by diegoevangelisti**
Fixes #1899 

## Change summary

Based on the data structure received from dashboard reports, the correct way to read what to graph should be accessing to `values`, which can be one or more array with `x` and `y` values.

## Testing

Further testing will be taking place when the dashboard feature is ready.

### CODE REVIEW

File: src/widgets/BarChart.js [hunk 1]
```diff
@@ -33,7 +33,7 @@ export const BarChart = ({ data, width, height }) => {
 
   return (
     <VictoryChart width={width} height={height} padding={padding} domainPadding={domainPadding}>
-      <VictoryBar style={style} data={values} />
+      <VictoryBar style={style} data={values[0]} />
```
Comment (wlthomson) [inline src/widgets/BarChart.js]: This will throw an error if `values.length == 0` 😢 . A safer alternative is to declare a variable by deconstructing:

```
const [value = null] = values;

return (
  ...
     <VictoryBar style={style} data={value} />
  ...
)
```

Using this syntax, `value` will default to `null` if `values.length == 0`.

Comment (diegoevangelisti) [reply src/widgets/BarChart.js]: Thanks Will! I was making more changes related with this PR that can be found here:
f5067e2
dba8a2c 
e46724a

I found that data structure can include more than one array of values (mainly on line charts), so I added a map over data to render as many i.e. lines as necessary in the same graph.

File: src/widgets/LineChart.js [hunk 2]
```diff
@@ -36,10 +35,14 @@ export const LineChart = ({ width, height, data }) => {
   };
   return (
     <VictoryChart width={width} height={height} padding={padding}>
-      <VictoryScatter size={dotSize} style={dotStyle} data={values} />
-      <VictoryLine style={lineStyle} data={values} />
-      {renderXAxis()}
+      {data.map(({ values }) => (
+        <VictoryScatter size={dotSize} style={dotStyle} data={values} />
+      ))}
```
Comment (joshxg) [inline src/widgets/LineChart.js]: You can use hooks here to memoize:

`const scatterLine = React.useMemo(() => data.map...., [data])`

then below.. `{scatterLine}`

Although not 100% needed, good to know

**Comment by diegoevangelisti** [comment]
> Looks good. I wonder if you tested with an empty array? (For example, if you just use `{[]}`, which could happen if `data` is empty .. which it shouldn't be, but could be!)
> 
> nice work! 🎉

Thanks both @joshxg and @wlthomson for noticing the empty data issue. I guess I will need to display a message to show `Empty Report` or something similar. I will create an issue for that so I can move on with labels now

File: src/widgets/LineChart.js (hunk 2 above)
Comment (diegoevangelisti) [reply src/widgets/LineChart.js]: Nice! I'll give it a try later, thanks for sharing this
