### PR TITLE
#4095 Check for transactions before summing doses

### LINKED ISSUE #4095: Selecting a vaccine on the supplier requisition page crashes app
## Describe the bug
Linked Bugsnag logged issue: https://github.com/openmsupply/mobile/issues/4094

https://user-images.githubusercontent.com/65875762/121458191-0bfd7180-c9fd-11eb-9efc-c2cfb657d995.mp4

### To reproduce

Steps to reproduce the behaviour:

1. Go to supplier requisition and pick a vaccine

### Expected behaviour

No crash

### Proposed Solution

Leave if you don't know how to fix/implement. Edit this issue description and explain here if you know the best path of implementing the fix within the codebase.

### Version and device info

- App version: 8.1.0-rc0
- Tablet model: Lenovo
- OS version: 8.1

### Additional context

Vaccine module wasn't enabled, not sure if relevant

### PR DESCRIPTION
**Pull request by katherine-sussol**
Fixes #4095

## Change summary

- Check filtered transactions before summing doses for openVialWastage
- Not sure why lots of random realm things seem to be breaking 😿 

## Testing

Steps to reproduce or otherwise test the changes of this PR:

- [ ] Repro #4095

### Related areas to think about

Not sure

### CODE REVIEW

File: src/database/DataTypes/Item.js [hunk 1]
```diff
@@ -240,11 +240,16 @@ export class Item extends Realm.Object {
...
       .filtered("option.type == 'openVialWastage'")
-      .filtered('transaction.confirmDate >= $0', fromDate)
-      .sum('doses');
+      .filtered('transaction.confirmDate >= $0', fromDate);
+
+    if (transactions.length) {
+      return transactions.sum('doses');
+    }
+
+    return 0;
```
Comment (mark-prins) [inline src/database/DataTypes/Item.js:252]:
```suggestion
    return transactions.length ? transactions.sum('doses') : 0;
```

**Review by mark-prins — APPROVED** [review]
LGTM!
Though it does leave me nervous that there are other little land mines like this lying around.
I suggest a one-liner if that doesn't make it harder to read

File: src/database/DataTypes/Item.js (hunk 1 above)
Comment (katherine-sussol) [reply src/database/DataTypes/Item.js]: Thanks, I'm not sure whether I find it easier or harder 😆 . The shorter form does seem to be used quite prolifically through the app though so maybe I should conform 😸  bb1b00f
