### PR TITLE
#977 full aggregation rewrite

### LINKED ISSUE #977: Full aggregator rewrite
Build Number:
2.2.0 rc-0?
Description:
The full aggregator currently used in the vaccines module is a little convoluted, needs to be rewritten to be a little more simple.

Reproducible:
N/A

Reproduction Steps:
N/A

Comments:

### PR DESCRIPTION
**Pull request by joshxg**
Fixes #977 

- Adds a new full aggregation method
- Does not use the most recent 2 hours of sensor logs.
- Deletes all other pre-aggregated logs

- I think the time constants should be in their own file
- Could use the generic sensorlog create method in other methods when theyre cleaned up

- think I need to take another go over to make sure it's as defensive as possible

### CODE REVIEW

File: src/utilities/modules/temperatureSensorHelpers.js [hunk 1]
```diff
@@ -370,87 +378,119 @@ function addHeadAndTrailingLogToBreach({ result, sensor, database }) {
...
+ */
+function doFullAggregation({ result, sensor, database }) {
+  const { sensorLogs } = sensor;
+  if (!sensorLogs || sensorLogs.length === 0) return null;
+  // Want to leave the last 2 hours of logs un-aggregated. Filter them
+  // out.
+  const maxTimeToAggregate =
+    sensorLogs.filtered('aggregate == $0', 'preAggregate').max('timestamp') -
+    TWO_HOURS_MILLISECONDS;
+  const sortedSensorLogs = sensorLogs.filtered(
```
Comment (andreievg) [inline src/utilities/modules/temperatureSensorHelpers.js]: Can you get this sorted

File: src/utilities/modules/temperatureSensorHelpers.js [hunk 2]
```diff
@@ -370,87 +378,119 @@ function addHeadAndTrailingLogToBreach({ result, sensor, database }) {
...
+    }
   });
-
-  return { ...result, fullAggregateAdditions: logsToAdd.length, fullAggregationDeletions };
+  // Create an array of aggregated sensor log objects
+  const aggregatedSensorLogs = sensorLogGroups
+    .map(group => createFullAggregateSensorLogs(group))
+    .flat();
+  // Store each aggregated sensorlog in the database.
+  aggregatedSensorLogs.forEach(aggregatedLog => database.update('SensorLog', aggregatedLog));
```
Comment (andreievg) [inline src/utilities/modules/temperatureSensorHelpers.js]: I think we are not in write transaction atm

Comment (joshxg) [reply src/utilities/modules/temperatureSensorHelpers.js]: Have added this here: cdff488fe5270c2e3e767ddbe43af57e331f171c

I actually wonder if write transactions shouldn't be used within methods. Means you cannot use this method at all if the caller is already in a write transaction (creates situations as with settings)

File: src/utilities/modules/temperatureSensorHelpers.js (hunk 1 above)
Comment (joshxg) [reply src/utilities/modules/temperatureSensorHelpers.js]: oops 3a18cca9ff6858e75629009e3d9d62776b07319d

File: src/utilities/modules/temperatureSensorHelpers.js [hunk 3]
```diff
@@ -370,87 +378,119 @@ function addHeadAndTrailingLogToBreach({ result, sensor, database }) {
...
-
-    logsToAdd.push({
-      id: generateUUID(),
-      location: sensor.location,
-      sensor,
-      temperature: thisPeriodLogs.max('temperature'),
-      timestamp: aggregateMiddlePoint,
-      aggregation: 'aggregate',
-    });
+function createGenericSensorLog({
```
Comment (joshxg) [inline src/utilities/modules/temperatureSensorHelpers.js]: UUID's are generated here

File: src/utilities/modules/temperatureSensorHelpers.js [hunk 4]
```diff
@@ -370,87 +378,119 @@ function addHeadAndTrailingLogToBreach({ result, sensor, database }) {
...
+function doFullAggregation({ result, sensor, database }) {
+  const { sensorLogs } = sensor;
+  if (!sensorLogs || sensorLogs.length === 0) return null;
+  // Want to leave the last 2 hours of logs un-aggregated. Filter them
+  // out.
+  const maxTimeToAggregate =
+    sensorLogs.filtered('aggregate == $0', 'preAggregate').max('timestamp') -
+    TWO_HOURS_MILLISECONDS;
+  const sortedSensorLogs = sensorLogs
+    .filtered('aggregate == $0 && timestamp < $1', 'preAggregate', maxTimeToAggregate)
```
Comment (andreievg) [inline src/utilities/modules/temperatureSensorHelpers.js]: @joshxg 'aggregation'

File: src/utilities/modules/temperatureSensorHelpers.js [hunk 5]
```diff
@@ -370,87 +378,119 @@ function addHeadAndTrailingLogToBreach({ result, sensor, database }) {
...
+  const sensorLogGroups = [];
+  // A collection of sensor logs, grouped for the currently being operated on,
+  // < 8 hour period.
+  let sensorLogGroup = [];
+  sortedSensorLogs.forEach(sensorLog => {
+    const { timestamp } = sensorLog;
+    // Premature return if this sensorlog is malformed
+    if (!timestamp) return;
+    // Check if this sensorLog is in the current interval.
+    const isInSameInterval = logGroupStartTimestamp - timestamp < FULL_AGGREGATION_INTERVAL;
```
Comment (andreievg) [inline src/utilities/modules/temperatureSensorHelpers.js]: @joshxg is logGropuStartTimestamp set for first iteration ?

File: src/utilities/modules/temperatureSensorHelpers.js [hunk 6]
```diff
@@ -370,87 +378,119 @@ function addHeadAndTrailingLogToBreach({ result, sensor, database }) {
...
+  // Store each aggregated sensorlog in the database.
   database.write(() => {
-    logsToAdd.forEach(sensorLog => {
-      const newSensorLog = database.update('SensorLog', sensorLog);
-      sensor.sensorLogs.push(newSensorLog);
-      linkToBatches(newSensorLog, database);
-    });
+    aggregatedSensorLogs.forEach(aggregatedLog => database.update('SensorLog', aggregatedLog));
+    // Delete each pre-aggregated sensorlog.
+    sortedSensorLogs.forEach(preAggregatedLog => database.delete(preAggregatedLog));
```
Comment (andreievg) [inline src/utilities/modules/temperatureSensorHelpers.js]: was wondering, because sortedSensorLog is realm collection, is it safe to iterate it while deleting the logs ? i.e. would it mutate during iteration causing adverse effects ?

**Comment by joshxg** [comment]
@andreievg Have done the changes requested as well as the changes as per the other issue

File: src/utilities/modules/temperatureSensorHelpers.js [hunk 7]
```diff
@@ -370,87 +383,167 @@ function addHeadAndTrailingLogToBreach({ result, sensor, database }) {
...
+  const mostRecentPreAggregateTimestamp = sensorLogs
+    .filtered('aggregation == $0', SENSOR_LOG_PRE_AGGREGATE_TYPE)
+    .max('timestamp');
+  const maxTimestampForDeletion = new Date().getTime() - SENSOR_LOG_NO_DELETION_INTERVAL;
+  // Starting timestamp is either from the first fullAggregate timestamp, or beginning of time
+  const aggregationIntervalStart = (mostRecentFullAggregateTimestamp || -Infinity) + 1;
+  // Ending timestamp is either from the most recent preAggregate or from now, less the
+  // no full aggregate period (32 hours)
+  const aggregationIntervalEnd =
+    (mostRecentPreAggregateTimestamp || new Date().getTime()) - NO_FULL_AGGREGATE_PERIOD;
```
Comment (andreievg) [inline src/utilities/modules/temperatureSensorHelpers.js]: i think this should just be maxTimestampForDeletion ?

File: src/utilities/modules/temperatureSensorHelpers.js [hunk 8]
```diff
@@ -370,87 +383,167 @@ function addHeadAndTrailingLogToBreach({ result, sensor, database }) {
...
+      sensorLogGroup = [sensorLog];
+      logGroupStartTimestamp = timestamp;
+    }
   });
-
+  // Create an array of aggregated sensor log objects
+  const aggregatedSensorLogs = sensorLogGroups
+    .map(group => createFullAggregateSensorLogs(group))
+    .flat();
+  const sensorLogsToDelete = sortedSensorLogs.filtered('timestamp < $0', maxTimestampForDeletion);
```
Comment (andreievg) [inline src/utilities/modules/temperatureSensorHelpers.js]: this could mean the logs at the end of sortedSensorLogs, that are not aggregated yet (i.e. time between them is less then FULL_AGGREGATION_INTERVAL), would be deleted ?

File: src/utilities/modules/temperatureSensorHelpers.js [hunk 9]
```diff
@@ -370,87 +383,167 @@ function addHeadAndTrailingLogToBreach({ result, sensor, database }) {
...
+    // Somewhat arbitrary three days to ensure there is always enough data and
+    // a little bit defensive in case something goes wrong.
+    database.delete('SensorLog', sensorLogsToDelete);
   });
-
-  return { ...result, fullAggregateAdditions: logsToAdd.length, fullAggregationDeletions };
+  return {
+    ...result,
+    fullAggregateAdditions: aggregatedSensorLogs.length,
+    preAggregateDeletions: sortedSensorLogs.length,
```
Comment (andreievg) [inline src/utilities/modules/temperatureSensorHelpers.js]: sensorLogsToDelete

File: src/utilities/modules/temperatureSensorHelpers.js [hunk 10]
```diff
@@ -370,87 +383,167 @@ function addHeadAndTrailingLogToBreach({ result, sensor, database }) {
...
+function linkSensorLogToItemBatches({ sensorLog, database }) {
+  const { location } = sensorLog;
+  if (!location) return;
+  const itemBatches = location.getItemBatchesWithQuantity(database);
+  if (!itemBatches || itemBatches.length === 0) return;
+  database.update('SensorLog', {
+    ...sensorLog,
+    itemBatches,
+  });
+  itemBatches.forEach(itemBatch =>
```
Comment (andreievg) [inline src/utilities/modules/temperatureSensorHelpers.js]: also add sensorLog to itemBatches please

File: src/utilities/modules/temperatureSensorHelpers.js (hunk 7 above)
Comment (joshxg) [reply src/utilities/modules/temperatureSensorHelpers.js]: 7fb11aeda7c1f2c9c78024d9f123eb6166993196 - I think using the date of the last preaggregate is right - if we have large intervals between syncing it could incorrectly aggregate

File: src/utilities/modules/temperatureSensorHelpers.js (hunk 8 above)
Comment (joshxg) [reply src/utilities/modules/temperatureSensorHelpers.js]: da613bfbbc6d41ab60e2c213d675915ab62295fe

File: src/utilities/modules/temperatureSensorHelpers.js (hunk 9 above)
Comment (joshxg) [reply src/utilities/modules/temperatureSensorHelpers.js]: da613bfbbc6d41ab60e2c213d675915ab62295fe - sorry screwed my commits up

File: src/utilities/modules/temperatureSensorHelpers.js (hunk 10 above)
Comment (joshxg) [reply src/utilities/modules/temperatureSensorHelpers.js]: da613bfbbc6d41ab60e2c213d675915ab62295fe


Added a helper to itemBatches to be consistent with other realm models?

File: src/utilities/modules/temperatureSensorHelpers.js (hunk 7 above)
Comment (andreievg) [reply src/utilities/modules/temperatureSensorHelpers.js]: true

Comment (andreievg) [reply src/utilities/modules/temperatureSensorHelpers.js]: actually, full aggregation would happen after a successful sync, at this stage we should have all of the info pulled from the sensor, so either way would work. i like the pre-emptive thinking though

File: src/utilities/modules/temperatureSensorHelpers.js [hunk 11]
```diff
@@ -370,87 +382,170 @@ function addHeadAndTrailingLogToBreach({ result, sensor, database }) {
...
+    }
   });
-
+  // Create an array of aggregated sensor log objects
+  const aggregatedSensorLogs = sensorLogGroups
+    .map(group => createFullAggregateSensorLogs(group))
+    .flat();
+  const deleteFromTimestamp =
+    sensorLogGroup.length > 0 ? sensorLogGroup[0].timestamp : aggregationIntervalEnd;
+  const sensorLogsToDelete = sortedSensorLogs.filtered('timestamp < $0', deleteFromTimestamp);
```
Comment (andreievg) [inline src/utilities/modules/temperatureSensorHelpers.js]: @joshxg, i think this is not quite right yet, shouldn't it it just be sensorLogGroup.flat() ?

Comment (joshxg) [reply src/utilities/modules/temperatureSensorHelpers.js]: `sensorLogGroup` is a 1D array, filled with sensorLog objects, not sure what you mean. Essentially it is a stack which builds an 8 hour interval of `sensorLogs`. If we take the first log from that, it is the earliest in the last set of `sensorLogs` which have not been aggregated yet and we can delete all the pre aggregate logs left over and delete them, as we have already filtered `sortedSensorLogs` to be a collection of `sensorLogs` that are to-be-aggregated. If `sensorLogGroup` does not have any sensorLogs in it, we can just delete everything as there are no more `sensorLogs` to aggregate (this case shouldn't occur, maybe it is to safe?)

Comment (andreievg) [reply src/utilities/modules/temperatureSensorHelpers.js]: @joshxg I missed the 's' on sensorLogGroups.
`sensorLogsToDelete = sensorLogGroups.flat()`
 
Your code all good apart from when 0 sortedSensorLogs?

Comment (joshxg) [reply src/utilities/modules/temperatureSensorHelpers.js]: Oh right, sorry. I think I was not 100% that actual realm objects were required or not for the delete method.

Technically the method does nothing when `sortedSensorLogs.length = 0`, but can add an early return.

On that note, I forgot to ask if you think the early return on no `sensorLogs` should return an object in the same form, or if null is fine. Further, I kinda hate the result parameter and return value, heh

Comment (andreievg) [reply src/utilities/modules/temperatureSensorHelpers.js]: @joshxg I think you need to loop through each element to delete it of not realm array. I thought that would be cleaner and quicker then query realm in this case

Comment (andreievg) [reply src/utilities/modules/temperatureSensorHelpers.js]: I am not a fan of returns either, can discuss tomorrow
