### PR TITLE
#1519 usage dates

### LINKED ISSUE #1519: Usage calculations wrong if there is a SI in progress
## Describe the bug

Usage bug -- relatively obscure -- premise is that null is always less than any date:

Usage starts here, just setting up parameters: https://github.com/openmsupply/mobile/blob/ca52751126a6bdfde01459e76a07b6ed33d45bbb/src/database/DataTypes/Item.js#L73-L78

Calls this to calculate usage over the period: https://github.com/openmsupply/mobile/blob/ca52751126a6bdfde01459e76a07b6ed33d45bbb/src/database/DataTypes/Item.js#L200-L212

Which gets the date an item was added here: https://github.com/openmsupply/mobile/blob/ca52751126a6bdfde01459e76a07b6ed33d45bbb/src/database/DataTypes/Item.js#L86-L94

Which is where the problem is (commented): 

```
  get addedDate() {
    if (this.batches.length === 0) return undefined;
    let itemAddedDate = new Date();
    this.batches.forEach(batch => {
      // If a batches added date is null (which is if there is any transaction
       // which has is not confirmed yet), then itemAddedDate is always null
      const batchAddedDate = batch.addedDate;
      itemAddedDate = batchAddedDate < itemAddedDate ? batchAddedDate : itemAddedDate;
    });
    return itemAddedDate;
  }
```

Method to get a transaction batches added date:
https://github.com/openmsupply/mobile/blob/ca52751126a6bdfde01459e76a07b6ed33d45bbb/src/database/DataTypes/ItemBatch.js#L41-L48

### Expected behaviour

When `itemAddedDate` is newer than the AMC lookback time (90 days by default, editable by store custom data), then the period to calculate consumption for should be from the item added date.

The fix is very easy, one line. But this has been in production for a long time and this changes, some usage quite drastically - for example:
OLD:
```
{"usage":0},{"usage":1.4111111111111112},{"usage":22.366666666666667},{"usage":2.1666666666666665},{"usage":1.1875},{"usage":0.18888888888888888}]
```
NEW/BUG FIXED:
```
[{"usage":0},{"usage":6.0476190476190474},{"usage":95.85714285714286},{"usage":41},{"usage":1.1875},{"usage":1.0625}] 
```

### Version and device info

- App version: 1.0 +
- Tablet model: All
- OS version: All

### Additional context

N/A

### PR DESCRIPTION
**Pull request by joshxg**
Fixes #1519 

## Change summary

- Changes `Item.addedDate` and `ItemBatch.addedDate` methods so that the added date is the earliest confirm date, of all incoming `TransactionBatch` records.

I tried to mimic the previous behaviour while just fixing the bug between `null` and dates.

I understand that we use the earliest date for the added date. I don't fully understand why we would use this in the usage calculation. It seems to be trying to account for using large amounts when an item is 'added'. If so, should this look for the earliest confirmed, incoming batch, with stock? Currently this logic would only account for the first ever incoming batch.

I'm missing a little bit of knowledge here I think!

## Testing

*Internal, hard to test change..*
- [ ] `Item.addedDate` returns the date of the earliest confirmed transaction batch..
- [ ] `ItemBatch.addedDate` returns the date of the earliest confirmed transaction batch..

### Related areas to think about

Related PR: #1520

### CODE REVIEW

File: src/database/DataTypes/ItemBatch.js [hunk 1]
```diff
@@ -35,16 +35,14 @@ export class ItemBatch extends Realm.Object {
...
    * @return  {Date}
    */
   get addedDate() {
-    if (this.transactionBatches.length === 0) return new Date();
-    const transactionBatches = this.transactionBatches.slice();
-    const sortedTransactionBatches = transactionBatches.sort(
-      (a, b) => a.transaction.confirmDate < b.transaction.confirmDate
+    return (
+      this.transactionBatches
+        .filtered('transaction.type == $0 && transaction.status != $1', 'supplier_invoice', 'new')
```
Comment (Chris-Petty) [inline src/database/DataTypes/ItemBatch.js]: I don't know why parameterise when arguments are hardcoded constants?
