### PR TITLE
#2008 patient saving

### LINKED ISSUE #2008: Patients DOB not saving correctly
## Describe the bug

When editing a patients D.O.B with the date picker, the value is not cast correctly.

### To reproduce

Dispensing Development bug

### Expected behaviour

For the date to be saved correctly

### Proposed Solution

N/A

### Version and device info

Dispensing Development bug

### Additional context

N/A

### PR DESCRIPTION
**Pull request by joshxg**
Fixes #2008 

## Change summary

- Correctly saves a patient - the corrected initial value fixes this
- Correctly refreshes the underlying dispensing page table to reflect the new details - the new action

## Testing

N/A

### Related areas to think about

N/A

### CODE REVIEW

File: src/pages/dataTableUtilities/getPageInitialiser.js [hunk 1]
```diff
@@ -468,11 +468,6 @@ const pageInitialisers = {
   supplierInvoices: supplierInvoicesInitialiser,
   supplierRequisition: supplierRequisitionInitialiser,
   supplierRequisitions: supplierRequisitionsInitialiser,
-  prescriptions: prescriptionsInitialiser,
```
Comment (wlthomson) [inline src/pages/dataTableUtilities/getPageInitialiser.js]: If these are TODOs, can do, e.g. `prescriptions: null` (tested working for me).
