### PR TITLE
#3210 Excessive row rendering

### LINKED ISSUE #3210: Customer requisition rows excessive re-rendering
## Describe the bug

Turned `debug` on on `CustomerRequisitionPage` and there is some unneeded row renders

### To reproduce

Turned `debug` on on `CustomerRequisitionPage` and see some unneeded row renders

### Expected behaviour

Rows should only re-render when required

### Proposed Solution

N/A

### Version and device info

- App version: 6.0RC10 +
- Tablet model:
- OS version:

### Additional context

N/A

### PR DESCRIPTION
**Pull request by joshxg**
Fixes #3210

## Change summary

- Memoized columns and style object of data table row
- Fixed minor page info key issue

## Testing

- [ ] Editing a row doesn't cause 10's of re-renders

### Related areas to think about

N/A

### CODE REVIEW

File: src/widgets/DataTable/DataTableRow.js [hunk 1]
```diff
@@ -372,6 +375,7 @@ const DataTableRow = React.memo(
         rowData={rowData}
         rowState={rowState}
         rowIndex={rowIndex}
+        debug
```
Comment (wlthomson) [inline src/widgets/DataTable/DataTableRow.js:378]: Oops, or intentional?

File: src/widgets/DataTable/DataTableRow.js [hunk 2]
```diff
@@ -87,11 +87,14 @@ const DataTableRow = React.memo(
...
-      ...(!isValidated && { borderColor: SUSSOL_ORANGE, borderWidth: 1, borderRadius: 5 }),
-    };
+    const rowStyle = useMemo(
+      () => ({
+        ...(rowIndex % 2 === 0 ? alternateRowStyle : basicRowStyle),
+        ...(isSelected && selectedRowStyle),
+        ...(!isValidated && { borderColor: SUSSOL_ORANGE, borderWidth: 1, borderRadius: 5 }),
+      }),
+      [rowIndex, isSelected, isValidated]
+    );
```
Comment (wlthomson) [inline src/widgets/DataTable/DataTableRow.js:97]: Could you squeeze a bit more performance here but separating out into individual `useMemo`s for different use cases, e.g. `rowIndex` for sorting, `isSelected` for selecting, etc.?

File: src/pages/CustomerRequisitionPage.js [hunk 3]
```diff
@@ -91,9 +89,24 @@ export const CustomerRequisition = ({
...
   const { isFinalised, comment, program, isResponse, createdDate, entryDate } = pageObject;
 
+  const currentColumns = useMemo(() => {
+    const formEntryColumnSet = isRemoteOrder
+      ? 'editableCustomerRequisitionFormEntry'
+      : 'customerRequisitionFormEntry';
+    if (usingIndicators && showIndicators) {
+      return indicatorColumns;
+    }
+    return columnSet === 'a'
```
Comment (wlthomson) [inline src/pages/CustomerRequisitionPage.js:105]: Any particular reasoning for this literal? Could perhaps benefit from a constant (or a comment, in the meantime)?

**Review by wlthomson — APPROVED** [review]
lgtm

File: src/widgets/DataTable/DataTableRow.js (hunk 1 above)
Comment (joshxg) [reply src/widgets/DataTable/DataTableRow.js]: oops 857b7aa

File: src/widgets/DataTable/DataTableRow.js (hunk 2 above)
Comment (joshxg) [reply src/widgets/DataTable/DataTableRow.js:97]: I think only for when the row index changes and the `% 2` result is the same? Don't think it's worth it

File: src/pages/CustomerRequisitionPage.js (hunk 3 above)
Comment (joshxg) [reply src/pages/CustomerRequisitionPage.js:105]: it's just the state that's set, not sure what comment I could write that would help

File: src/widgets/DataTable/DataTableRow.js (hunk 2 above)
Comment (wlthomson) [reply src/widgets/DataTable/DataTableRow.js:97]: I mean't more that you could make it so that you only needed to worry about the selected row style when `isSelected` changes and the validated styles when `isValidated` changes etc. (rather than calculating them all when any of the variables changes). But it's such a small thing, agree it's not really worth it!

File: src/pages/CustomerRequisitionPage.js (hunk 3 above)
Comment (wlthomson) [reply src/pages/CustomerRequisitionPage.js:105]: Is there a reason the `columnSet` is `'a'` rather than a constant? Does the literal have an obvious meaning that I'm missing?

Comment (joshxg) [reply src/pages/CustomerRequisitionPage.js:105]: No, the action/reducer switches between "a" and "b" (This is just taken from the `mapStateToProps`)
