### PR TITLE
#1184 Broken byProgramModal

### LINKED ISSUE #1184: ByProgramModal broken after merge
## Describe the bug

Couple of basic mistakes in `ByProgramModal` after being merged, doesn't work in develop

### To reproduce

1. Open `ByProgramModal`

### Expected behaviour

Working!

### Version and device info

Dev 2.3.6

### Additional context
N/A

### PR DESCRIPTION
**Pull request by joshxg**
Fixes #1184 

## Change summary

Couple of fixes

## Testing

- [ ] `ByProgramModal` doesnt crash the app when opening

### Related areas to think about

N/A

### CODE REVIEW

File: src/reducers/ByProgramReducer.js [hunk 1]
```diff
@@ -162,15 +162,16 @@ export const byProgramReducer = (state, action) => {
       };
     case actions.SET_TOGGLE: {
       const { isProgramBased, transactionType } = state;
-      const steps = STEPS[transactionType][getType(state)];
+      const newIsProgramBasaed = !isProgramBased;
```
Comment (Chris-Petty) [inline src/reducers/ByProgramReducer.js]: basaesed PR
