### PR TITLE
#3673 fix fridge date string overlapping chevron icon

### LINKED ISSUE #3673: Mobile Vaccines: chevron icon overlaps with time string
## Describe the bug

Migrated from #3665,

Log record time label overflow and overlap with Sensor detail icon.

### To reproduce

1. Go to Sensor list page. Check the alarm icon label. When alarm label shows two digit value and "minutes" , label overlap with Detail icon.

### Expected behaviour

Margin should be there between Alarm icon label and Detail icon.

### Proposed Solution

Leave if you don't know how to fix/implement. Edit this issue description and explain here if you know the best path of implementing the fix within the codebase.

### Version and device info

- App version: v7.0.0 rc8
- Tablet model: Samsung
- OS version: 8.1

### Additional context

arises while testing #2913

### PR DESCRIPTION
**Pull request by wlthomson**
Fixes #3673.

## Change summary

Minor UI fix to prevent `FridgeDisplay` date string overlapping chevron icon.

## Testing

Steps to reproduce or otherwise test the changes of this PR:

- [ ] Setup a sensor with a log interval > 10 minutes (e.g. 15 minutes). View the sensor > 10 minutes after the last temperature log. The date string does not overlap the chevron icon.

### Related areas to think about

N/A.

### CODE REVIEW

File: src/selectors/Entities/temperatureBreachConfig.js [hunk 1]
```diff
@@ -36,8 +36,8 @@ export const selectEditingConfigThresholds = state => {
   const coldConsecutiveThreshold = (hotConsecutiveConfig.minimumTemperature ?? 0) - 0.1;
   const hotConsecutiveThreshold = (coldConsecutiveConfig.maximumTemperature ?? 0) + 0.1;
 
-  const coldCumulativeThreshold = (hotCumulativeConfig.minimumTemperature ?? 0) + 0.1;
-  const hotCumulativeThreshold = (coldCumulativeConfig.maximumTemperature ?? 0) - 0.1;
+  const coldCumulativeThreshold = (hotCumulativeConfig.minimumTemperature ?? 0) - 0.1;
```
Comment (wlthomson) [inline src/selectors/Entities/temperatureBreachConfig.js]: Hm, not sure what happened here!

**Review by katherine-sussol — APPROVED** [review]
👀  pretty good to me! Can confirm no overlap (did wrap on my emulator but I think it looks ok?)

image
