### PR TITLE
#2085 patient full name

### LINKED ISSUE #2085: Patient full name
## Describe the bug

On desktop, the `[name]name` field for a patient is `lastName, firstName`. This field is not filled at all on mobile. It should at least be synced

### To reproduce

Dispensary development bug

### Expected behaviour

Dispensary development bug

### Proposed Solution

Dispensary development bug

### Version and device info

Dispensary development bug

### Additional context

Dispensary development bug

### PR DESCRIPTION
**Pull request by joshxg**
Fixes #2085 

## Change summary

- Adds `name.name` to be a full name of a patients `lastName, firstName` - the same as desktop

## Testing

N/A

### Related areas to think about

N/A

### CODE REVIEW

File: src/globalStyles/pageStyles.js [hunk 1]
```diff
@@ -6,7 +6,7 @@
 import { SHADOW_BORDER, BLUE_WHITE, BACKGROUND_COLOR } from './colors';
 
 export const PAGE_CONTENT_PADDING_HORIZONTAL = 20;
-export const FULL_SCREEN_MODAL_MARGIN = 8;
+export const FULL_SCREEN_MODAL_MARGIN = 1;
```
Comment (joshxg) [inline src/globalStyles/pageStyles.js]: little offroad.. looks better :)

File: src/localization/dispensingStrings.json [hunk 2]
```diff
@@ -7,7 +7,7 @@
     "choose_a_name": "Choose a name",
     "choose_a_reason": "Choose a reason",
     "click_on_an_item_to_add_it": "Click on an item to add it",
-    "credit_user": "Credit used",
+    "credit_used": "Credit used",
```
Comment (joshxg) [inline src/localization/dispensingStrings.json]: more offroad - just noticed it 🤷‍♂

File: src/widgets/modals/PatientHistory.js [hunk 3]
```diff
@@ -74,7 +74,10 @@ const PatientHistory = ({ sortKey, onSortColumn, isAscending, data }) => {
 
 const mapStateToProps = state => {
   const { patient } = state;
-  return { ...patient, data: selectSortedPatientHistory(state) };
+  const { isAscending, sortKey } = patient;
+  const data = selectSortedPatientHistory(state);
+
+  return { isAscending, sortKey, data };
```
Comment (joshxg) [inline src/widgets/modals/PatientHistory.js]: Added a small off-road tidy up :)
