### PR TITLE
#3040 location creation

### LINKED ISSUE #3040: Creating a location seems to create another location with an empty code field
## Describe the bug

I am not sure how it happened but I tried to create a new location and found myself also with an extra location record with all fields empty including the location code. Now Mobile is crashing each time I click on the Vaccines button.

image

### To reproduce

Have vaccine module store preference on
1. Click on the Vaccines button
2. Click on 'Admin' button
3. Go to location and create anew location.

### Expected behaviour

Should not create an extra record without a code

### Proposed Solution

Leave if you don't know how to fix/implement. Edit this issue description and explain here if you know the best path of implementing the fix within the codebase.

### Version and device info

- App version: v6.0.0RC0
- Tablet model: Galaxy tab A 10.1
- OS version: Android

### Additional context

Testing Vaccine module

### PR DESCRIPTION
**Pull request by joshxg**
Fixes #3040 

## Change summary

- Added some code to help with handling not having locations for a sensor to be assigned to (a better placeholder)
- Added some code yo help with handling not having location types (mainly to handle the case where a location is on the mobile database with no location type - dont allow it to be saved, but still allow it to be edited so you could add one once you get location types. Before it was just disallowing editting completely)
- Added some defensive code around a location not having temperaturelogs.

Was *NOT* able to reproduce the bug where a location is created with two locations, having an additional location with no description or code..!

## Testing

Alain is testing vaccines!

### Related areas to think about

Not able to produce half the bug. The two bugs reported were actually unrelated, though.

### CODE REVIEW

File: src/pages/VaccineAdminPage.js [hunk 1]
```diff
@@ -43,7 +43,7 @@ const VaccineAdminPageComponent = ({
   onSortColumn,
   onToggleFridges,
   onToggleSensors,
-  onSelectLocation,
+  onSelectSensorLocation,
```
Comment (joshxg) [inline src/pages/VaccineAdminPage.js:46]: Added the Sensor_location stuff to  have a different placeholder

File: src/pages/VaccineAdminPage.js [hunk 2]
```diff
@@ -54,6 +54,7 @@ const VaccineAdminPageComponent = ({
   isScanning,
   onEditLocation,
   onSaveLocation,
+  onNewLocation,
```
Comment (joshxg) [inline src/pages/VaccineAdminPage.js:57]: was using a single callback for both editing and creating - changed to different callbacks. The callback was having a toast pop up saying "No location types sorry", when trying to edit or create. Now, just when trying to create it shows that toast

File: src/utilities/formInputConfigs.js [hunk 3]
```diff
@@ -220,6 +220,8 @@ const FORM_INPUT_CONFIGS = seedObject => ({
     options: UIDatabase.objects('LocationType'),
     optionKey: 'description',
     isEditable: true,
+    validator: input => !!input,
```
Comment (joshxg) [inline src/utilities/formInputConfigs.js:223]: made location type required. Previously drop downs were assuming there were options and there were no "NONE" option, so it didn't matter

File: src/widgets/FormInputs/FormDropdown.js [hunk 4]
```diff
@@ -44,13 +45,19 @@ export const FormDropdown = ({
...
+          style={{ width: null, flex: 1 }}
+          values={valueStrings}
+          selectedValue={value[optionKey]}
+          onValueChange={onValueChangeCallback}
+          isDisabled={isDisabled}
+        />
+      ) : (
+        <View>
+          <Text>{generalStrings.no_options}</Text>
+        </View>
```
Comment (joshxg) [inline src/widgets/FormInputs/FormDropdown.js:59]: just having the drop down menu replaced with "NO OPTIONS" string. Not memoizing this as its just not needed

File: src/widgets/FridgeDisplay.js [hunk 5]
```diff
@@ -57,6 +57,25 @@ export const FridgeDisplayComponent = ({
...
+        breaches={breaches}
+        onPressBreach={onOpenBreachModal}
+        xTickFormat={temperatureFormatter}
+      />
+    )) || <NoLogsComponent />;
+
+  const Spinner = () => (
+    <FlexView justifyContent="center" flex={1} alignItems="center">
+      <ActivityIndicator size="small" color={SUSSOL_ORANGE} />
+    </FlexView>
```
Comment (joshxg) [inline src/widgets/FridgeDisplay.js:76]: just tidying the render method a bit - it's slightly different and actually shows the no logs component now..! Not memoizing as it isn't really needed

File: src/widgets/FridgeDisplayInfo.js [hunk 6]
```diff
@@ -38,8 +38,8 @@ export const FridgeDisplayInfo = ({
     leastRecentTemperatureLog,
   } = fridge;
 
-  const { timestamp: minimumDate } = leastRecentTemperatureLog;
-  const { timestamp: maximumDate } = mostRecentTemperatureLog;
+  const { timestamp: minimumDate = fromDate } = leastRecentTemperatureLog ?? {};
+  const { timestamp: maximumDate = toDate } = mostRecentTemperatureLog ?? {};
```
Comment (joshxg) [inline src/widgets/FridgeDisplayInfo.js:42]: defensive code to stop the crash descrbied in the issue

**Comment by joshxg** [comment]
@mark-prins thanks mark. I'll merge and do another RC. I think it's a little easier for him that way!
