### PR TITLE
#1405 Multiline Cell component

### LINKED ISSUE #1405: Cell component should be multi line by default
## Describe the bug

`Cell` is a single line. This cna be a bit problematic when item names are long. Especially given that their units and sizes need to be in the name.

### To reproduce

1. On desktop edit an item name to be super long
2. Add this item to any page - SI/CI/Stocktake etc
4. See error [It's ellipsized up and cut off even though theres room for a couple lines at least]

### Expected behaviour

Should use two lines

### Version and device info

All, forever I think

### Additional context

- Would need to update PR here: https://github.com/sussol/react-native-data-table/pull/57
- Maaybe need to adjust row height maybe, but worth it most likely

### PR DESCRIPTION
**Pull request by joshxg**
Fixes #1405 

## Change summary

- Adds a `maxLines` prop to `Cell`, default of 2

image

image

## Testing

- [ ] Have an `ItemLine`/`Supplier`/`Customer` with a really long name and look at the name in the `DataTable`, should look all good over two lines

### Related areas to think about

N/A

have updated PR for `react-native-data-table`: https://github.com/sussol/react-native-data-table/pull/57

### CODE REVIEW

File: src/widgets/DataTable/Cell.js [hunk 1]
```diff
@@ -13,15 +13,16 @@ import { getAdjustedStyle } from './utilities';
...
  */
-const Cell = React.memo(({ value, textStyle, viewStyle, width, isLastCell, debug }) => {
+const Cell = React.memo(({ value, textStyle, viewStyle, width, isLastCell, maxLines, debug }) => {
   if (debug) console.log(`- Cell: ${value}`);
   const internalViewStyle = getAdjustedStyle(viewStyle, width, isLastCell);
 
   return (
     <View style={internalViewStyle}>
-      <Text ellipsizeMode="tail" numberOfLines={1} style={textStyle}>
+      <Text ellipsizeMode="tail" numberOfLines={maxLines} style={textStyle}>
```
Comment (wlthomson) [inline src/widgets/DataTable/Cell.js]: Just my opinion, think its nice to use consistent props with the underlying component. E.g. `numberOfLines` instead of `maxLines`. I think unless the underlying component is being used in a very different way, it makes sense to model components consistently with the conventions used by the built-in components?

Comment (joshxg) [reply src/widgets/DataTable/Cell.js]: 352447b432b5fde3924d06546c5fbe067c662eea
