### PR TITLE
#1880 Get values from data object

### LINKED ISSUE #1880: Reports' data structure is not similar than desktop one
## Describe the bug

Before syncing actual reports, some demo data was created predicting data structures that don't match with the real one expected to be arriving. Different nesting mainly.

### To reproduce

Check the difference between `ReportDemoData.js` and the JSON structure available in desktop reports, which is the following:

- BarChart

```
  {
    name: 'TopFacilities',
    data: [
      {
        label: 'Top Facilities Supplied last 90 days',
        values: [
          {
            x: 'Hufflepuff Health Centre',
            y: 41,
          },
          {
            x: '',
            y: 0,
          },
        ],
      },
    ],
  }
```
- LineChart

```
{
    name: 'ExpiringStock',
    data: [
      {
        label: 'Cumulative',
        values: [
          {
            x: '1 month',
            y: 0,
          },
          {
            x: '2 months',
            y: 6205,
          },
          {
            x: '3 months',
            y: 9730,
          },
          {
            x: '4 months',
            y: 9747.644,
          },
          {
            x: '5 months',
            y: 9747.644,
          },
          {
            x: '6 months',
            y: 9993.794,
          },
          {
            x: '7 months',
            y: 11354.794,
          },
          {
            x: '8 months',
            y: 12752.294,
          },
          {
            x: '9 months',
            y: 12772.604,
          },
          {
            x: '10 months',
            y: 12772.604,
          },
          {
            x: '11 months',
            y: 12772.604,
          },
          {
            x: '12 months',
            y: 61500.188,
          },
        ],
      },
      {
        label: 'Monthly',
        values: [
          {
            x: '1 month',
            y: 0,
          },
          {
            x: '2 months',
            y: 6205,
          },
          {
            x: '3 months',
            y: 3525,
          },
          {
            x: '4 months',
            y: 17.644,
          },
          {
            x: '5 months',
            y: 0,
          },
          {
            x: '6 months',
            y: 246.15,
          },
          {
            x: '7 months',
            y: 1361,
          },
          {
            x: '8 months',
            y: 1397.5,
          },
          {
            x: '9 months',
            y: 20.31,
          },
          {
            x: '10 months',
            y: 0,
          },
          {
            x: '11 months',
            y: 0,
          },
          {
            x: '12 months',
            y: 48727.584,
          },
        ],
      },
    ],
  }
```
- TableReport

```
{
    name: 'TransactionPerStore',
    data: {
      rows: [
        ['General Warehouse', 0, 0],
        ['Hogwarts Dispensary', 0, 0],
        ['Hufflepuff Health Centre', 0, 8],
        ['Gryffindor District Store', 0, 0],
        ['Slytherin Health Centre', 0, 0],
        ['Ravenclaw District Store', 0, 0],
        ['Gryffindor Dispensary', 0, 0],
        ['This Store Is To Add A New One And Long One ', 0, 0],
        ['Testing Programs Store', 0, 0],
      ],
      header: ['Store', 'Week', 'Month'],
    },
}
```
- PieChart

```
{
    name: 'TopFacilities',
    data: [
      {
        label: 'Top Facilities Supplied last 90 days',
        values: [
          {
            x: 'Guido Valadares National Hospital',
            y: 135886,
          },
          {
            x: 'District Services Ermera',
            y: 28444,
          },
        ],
      },
    ],
  }
```

### Expected behaviour

Data structure for all reports should respect the one used in the desktop version.

### Proposed Solution

Update all reports to use the corresponding structure.

### PR DESCRIPTION
**Pull request by diegoevangelisti**
Fixes #1880 and #1878 

## Change summary

According to the data structure obtained from the desktop version, the actual data needed is more nested than we thought. This changes are intending to solve that wrong assumption.
So here we destructure `data` to get the actual values.
Aclaration: No need to do it in `ReportTable`

## Testing

Further testing will be taking place all together for the feature/dashboard branch.

### Related areas to think about

`ReportDemoData` should be updated to can test with the new structure.

### CODE REVIEW

File: src/sync/incomingSyncUtils.js [hunk 1]
```diff
@@ -504,7 +504,7 @@ export const createOrUpdateRecord = (database, settings, recordType, record) =>
       try {
         const parsedData = JSON.parse(data);
         const shouldSetData = checkIsObject(parsedData);
-        internalRecord = { id, title, type, _data: shouldSetData ? data : null };
+        internalRecord = { id, title, type, _data: shouldSetData ? data.data : null };
```
Comment (joshxg) [inline src/sync/incomingSyncUtils.js]: Lets just do this one here too if you don't mind: https://github.com/openmsupply/mobile/issues/1878

If you see here: https://github.com/sussol/msupply/pull/4985 - actually it is not called `data`! it is `json` .. so above we need to change `data` to `json` and also it should be `json.data`.

also here: https://github.com/openmsupply/mobile/blob/8490cbec79a165ea9e0d362c69b0b3a8ca448d67/src/sync/incomingSyncUtils.js#L255

Comment (diegoevangelisti) [reply src/sync/incomingSyncUtils.js]: Great that you noticed that! 
Sure, I'' work on that now. I didn't see #1878 because it wasn't in the Project Dashboard (Found you're a human been after all haha)

Comment (joshxg) [reply src/sync/incomingSyncUtils.js]: 🤖

Comment (andreievg) [reply src/sync/incomingSyncUtils.js]: > Found you're a human been after all haha
no way 🤯

Comment (diegoevangelisti) [reply src/sync/incomingSyncUtils.js]: Done here 6ac1fc6

Comment (diegoevangelisti) [reply src/sync/incomingSyncUtils.js]: @joshxg 
I guess this one `_data` should be `_json` as well, don't you think? I missed that

File: src/sync/incomingSyncUtils.js [hunk 2]
```diff
@@ -500,11 +500,11 @@ export const createOrUpdateRecord = (database, settings, recordType, record) =>
...
     }
     case 'Report': {
-      const { ID: id, title, type, data } = record;
+      const { ID: id, title, type, json } = record;
       try {
-        const parsedData = JSON.parse(data);
+        const parsedData = JSON.parse(json);
         const shouldSetData = checkIsObject(parsedData);
-        internalRecord = { id, title, type, _data: shouldSetData ? data : null };
+        internalRecord = { id, title, type, _data: shouldSetData ? json.data : null };
```
Comment (joshxg) [inline src/sync/incomingSyncUtils.js]: sorry my mistake - `json` will actually be a string here. So, we will need to parse the string - for example `parsedData.data`. BUT we also need to make sure we are setting a STRING as `_data`, NOT an object!

File: src/sync/incomingSyncUtils.js (hunk 1 above)
Comment (joshxg) [reply src/sync/incomingSyncUtils.js]: I personally hate the name `json` for a field 🤣  So I think `data` is fine. What do you think?

File: src/sync/incomingSyncUtils.js (hunk 2 above)
Comment (diegoevangelisti) [reply src/sync/incomingSyncUtils.js]: Ok, so apart from checking `parsedData.data` we can add something like `checkIsString` to check`json` as well, and if it's all good we assigned that to `_data` (or `_json`)
Am I right?

Comment (joshxg) [reply src/sync/incomingSyncUtils.js]: Hmm it does get a bit confusing. Consider this simplified case, where I think `testData` is a simple version of the `json` field and `testOne` is `json.data`:

```
const testData = { testOne: [{ testTwo: 2 }] };
const testDataAsString = JSON.stringify(testData);
const parsedTestData = JSON.parse(testDataAsString);
console.log(typeof parsedTestData.testOne);
```

then what gets logged?

File: src/sync/incomingSyncUtils.js (hunk 1 above)
Comment (diegoevangelisti) [reply src/sync/incomingSyncUtils.js]: Yeah haha let's keep that `_data`, at least as much as we can

File: src/sync/incomingSyncUtils.js (hunk 2 above)
Comment (diegoevangelisti) [reply src/sync/incomingSyncUtils.js]: haha I guess we will see the original `testData.testOne`, but with a couple of shakings, right?

Comment (diegoevangelisti) [reply src/sync/incomingSyncUtils.js]: Great, thanks! I reckon it's solved here: 01ad0a9

File: src/widgets/PieChart.js [hunk 3]
```diff
@@ -10,7 +10,8 @@ import { VictoryLabel, VictoryPie } from 'victory-native';
 
 import { APP_FONT_FAMILY, GREY } from '../globalStyles';
 
-export const PieChart = ({ width, height, data }) => {
+export const PieChart = ({ width, height, json }) => {
```
Comment (joshxg) [inline src/widgets/PieChart.js]: hmm.. you seem to have renamed a bunch of these props to `json` (I'm not sure why), but you are still passing as `data` here: https://github.com/openmsupply/mobile/blob/f8b25f317a6b1d6e3a000c9d52f8e715b01ea817/src/widgets/ReportChart.js#L31-L38

I would just revert back to `data`?

Comment (diegoevangelisti) [reply src/widgets/PieChart.js]: My mistake! Yes, I guess that's the best option, since we decided to keep it like `data`, otherwise I need to rename to `json` all the rest but not the best option.
Thanks btw😅

Comment (diegoevangelisti) [reply src/widgets/PieChart.js]: Hopefully this is well done here bf1b7bd 😄
