### PR TITLE
#2202 orphan sync out

### LINKED ISSUE #2202: SyncOut has orphan records
## Describe the bug

Some records can appear in the `SyncQueue` which have no 

### To reproduce

Dispensary development

### Expected behaviour

Dispensary development

### Proposed Solution

Dispensary development

### Version and device info

Dispensary development

### Additional context

Dispensary development

### PR DESCRIPTION
**Pull request by joshxg**
Fixes #2202 

## Change summary

- Delete orphaned sync outs
- This will still throw the error - but it'll get bugsnagged and minimal changes, just need to start sync again 🤷‍♂ 

## Testing

N/A

### Related areas to think about

N/A

### CODE REVIEW

File: src/sync/outgoingSyncUtils.js [hunk 1]
```diff
@@ -314,6 +314,14 @@ export const generateSyncJson = (database, settings, syncOutRecord) => {
     const recordResults = database.objects(recordType).filtered('id == $0', recordId);
     if (!recordResults || recordResults.length === 0) {
       // No such record
+
+      database.write(() => {
+        database.delete(
+          'SyncOut',
+          database.objects('SyncOut').filtered('recordId == $0', recordId)
```
Comment (wlthomson) [inline src/sync/outgoingSyncUtils.js]: Nit: `database.objects('SyncOut').get(recordId)`?
