### PR TITLE
#3227 Additional filtering on programs

### LINKED ISSUE #3227: Programs should be filtered by those visible to the mobile store
## Describe the bug

When creating a program customer requisition, programs are only filtered by those that are linked to the customer. It currently does not filter out those that are not visible to the mobile store (and therefore shouldn't be useable).

### To reproduce

1. Go to create a program customer requisition
2. Click on a customer
3. View programs: They're all the programs visible to the customer, regardless of being visible to the mobile store

### Expected behaviour

Only programs visible to both the customer and mobile store should be visible

### Proposed Solution

Additional filtering!

### Version and device info

- App version: V6.0RC10
- Tablet model: N/A
- OS version: N/A

### Additional context

N/A

### PR DESCRIPTION
**Pull request by joshxg**
Fixes #3227

## Change summary

- Adds additional filtering to filter out those programs which are not visible to the mobile store.

## Testing

- [ ] When creating a program-based customer requisition, programs listed are only those which are visible to the mobile store and to the customer.

### Related areas to think about

N/A

### CODE REVIEW

File: src/utilities/byProgram.js [hunk 1]
```diff
@@ -16,11 +16,14 @@ import { SETTINGS_KEYS } from '../settings';
  * -- Is visible to the customer.
  * -- masterList.isProgram = true,
  * -- has a store tag in programSettings, with a key which matches a name_tag for this customer.
+ * -- Is visible to the mobile store.
  * @param  {Object} Customer
  * @param  {Realm}  database
- * @return {array}  MasterLists which are programs usable by this customer.
+ * @return {array}  MasterLists which are programs usable by this customer & is visible.
```
Comment (wlthomson) [inline src/utilities/byProgram.js:22]: Nit:

```suggestion
 * @return {array} MasterList objects representing programs which are visible and usable by this customer.
```

File: src/utilities/byProgram.js [hunk 2]
```diff
@@ -16,11 +16,14 @@ import { SETTINGS_KEYS } from '../settings';
  * -- Is visible to the customer.
  * -- masterList.isProgram = true,
  * -- has a store tag in programSettings, with a key which matches a name_tag for this customer.
+ * -- Is visible to the mobile store.
  * @param  {Object} Customer
```
Comment (wlthomson) [inline src/utilities/byProgram.js:20]: Nit:

```suggestion
 * @param  {Object} Name object representing customer.
```

File: src/utilities/byProgram.js [hunk 3]
```diff
@@ -16,11 +16,14 @@ import { SETTINGS_KEYS } from '../settings';
...
  * @param  {Realm}  database
- * @return {array}  MasterLists which are programs usable by this customer.
+ * @return {array}  MasterLists which are programs usable by this customer & is visible.
  */
 const getAllProgramsForCustomer = (customer, database) => {
+  const thisStoresNameID = database.getSetting(SETTINGS_KEYS.THIS_STORE_NAME_ID);
```
Comment (wlthomson) [inline src/utilities/byProgram.js:25]: Nit: 

```suggestion
  const thisStoreNameID = database.getSetting(SETTINGS_KEYS.THIS_STORE_NAME_ID);
```

File: src/utilities/byProgram.js [hunk 4]
```diff
@@ -30,6 +33,13 @@ const getAllProgramsForCustomer = (customer, database) => {
   return database
     .objects('MasterListNameJoin')
     .filtered('name.id = $0 && masterList.isProgram = $1', id, true)
+    .filter(
+      ({ masterList }) =>
+        database
+          .objects('MasterListNameJoin')
+          .filtered('masterList.id == $0 && name.id == $1', masterList.id, thisStoresNameID)
```
Comment (wlthomson) [inline src/utilities/byProgram.js:40]: If make above suggested change:

```suggestion
          .filtered('masterList.id == $0 && name.id == $1', masterList.id, thisStoreNameID)
```

**Review by wlthomson — APPROVED** [review]
lgtm
