### PR TITLE
#1657 Bold the currently highlighted row

### LINKED ISSUE #1657: Bold/ Highlight the current row
**Describe the bug**
Currently when editing a cell in a row, there is not enough visual feedback of what row the the user has focused.

**To reproduce**

Go to a unfinalised customer invoice
Add a few items if there aren't any
Focus textinput of quantity field of an item
WANT: the row that focused cell is in to be highlighted.

**Expected behaviour**
The row currently with focus in it should be highlighted in some manner. Either highlight the row by changing the background colour. BONUS: Get fancy and highlight the row and bold the text in the cell with focus if you like.

**Solution**
This will require some in-depth knowledge of the page and data table state management.

1. Add action constant "focusCell"
Create an action creator function in cellActions.js. Action payload should have rowKey and columnKey
2. Add a reducer function in cellReducers.js that immuntably sets: dataState.row[action.rowKey].focusedColumn = action.columnKey (likely catch, if the focus has moved from one row to another, need to clear the focusedColumn from the previous rowState object)
3. Add a function onFocusCell to getPageDispatchers that dispatches the above action.
TextInputCell.js needs prop for onFocus that passes into the TextInput props. The component should make a method that calls it with rowKey and columnKey.
4. DataTableRow.js needs to check rowState to see if it's "focusedColumn" has a value and highlight the row if so.
Version and device info
App version: all
Tablet model: all
OS version: all
Additional context
Original description:

When editing a stocktake in particular, but also requisitions etc., it can be easy for a user to enter the quantity on the row above or below the one they mean to. The contrasting lines help with that, but apparently not enough. Would be great to highlight or bold the currently edited item to make it clearer!

### PR DESCRIPTION
**Pull request by joshxg**
Fixes #1657

## Change summary

- Adds some state to data table row and a callback to manage focused rows

## Testing

- [ ] When editing a row in a data table page (`CustomerRequisitionPage`, `SupplierInvoicePage`, `CustomerInvoicePage`, `SupplierRequisitionPage`, `StocktakeEditPage`)

### Related areas to think about

Implementation differs to what I originally thought. 

1. I thought it would be best to manage this in `dataState` in the redux store for each page, and have a cell `onFocus`, dispatch the action to store in state that the row was focused. However, this caused a redux update which isn't ideal and is a bit slow.
2. Also I realised there needs to be an `onBlur` callback, for when you, for example, focus the searchbar the row needs to unfocus - this can cause some serious jank, as you need to manage the flow where a single row has multiple text inputs, and when you push enter, the next column on the same row is focused. So if you just un-focus on blur, the highlighting would blink! ..

So: 1) Manage state in `datatablerow` is a bit quicker than managing in redux 2) debounce the focusing such that when `blur` event is triggered, it does not execute for a few milliseconds, and then the next call to `focus` cancels the `blur` call (if its the same row).

### CODE REVIEW

**Comment by mark-prins** [comment]
on the stocktake batch modal I'm still getting a janky update when moving from the expiry date edit to another column in the same row. Maybe just on emulator, dunno. Don't think that it's bad enough to need addressing, just being a tester and adding a grey cloud into an otherwise clear sky..

File: src/widgets/DataTable/DataTableRow.js [hunk 1]
```diff
@@ -371,6 +376,7 @@ const DataTableRow = React.memo(
         rowData={rowData}
         rowState={rowState}
         rowIndex={rowIndex}
+        debug
```
Comment (mark-prins) [inline src/widgets/DataTable/DataTableRow.js:379]: needs removing?

**Review by mark-prins — APPROVED** [review]
I really like it - and nice work with the debounce, the UI looks good

File: src/widgets/DataTable/DataTableRow.js (hunk 1 above)
Comment (joshxg) [reply src/widgets/DataTable/DataTableRow.js]: 261a9c9

**Comment by joshxg** [comment]
Nice - Turns out this cell was actually calling its callback twice - causing two re-renders and the jank!
