### PR TITLE
#976 sortIndex modified to start from 1

### LINKED ISSUE #976: SortIndex starts from 0 instead of 1 for stocktakeBatch and transactionBatch
Build Number: Literally all of them I think, though in this case 2.3.0+

Description: Mobile doesn't really use sortIndex, but on desktop it's expected the line numbers start from 1, not 0.

Fix is straight forward in `createRecord.js`.
```
// Correct
sortIndex: requisition.items.length + 1,
// Wrong
sortIndex: transactionItem.transaction ? transactionItem.transaction.numberOfBatches : 0
sortIndex: stocktakeItem.stocktake ? stocktakeItem.stocktake.numberOfBatches : 0,

// This I guess? Assignee figure it out.
sortIndex: stocktakeItem.stocktake ? stocktakeItem.stocktake.numberOfBatches + 1 : 1,
```
Reproducible: Yes

Reproduction Steps: make transactions or stocktakes on mobile, view collector copy on desktop.

Comments:

### PR DESCRIPTION
**Pull request by diegoevangelisti**
Fixes #976 

## Change summary

Main intention is change sortIndex to start from 1 instead of 0. This is important because on desktop it is expected that line numbers start from 1.

## Testing

Steps to reproduce or otherwise test the changes of this PR:

- [ ] Create a Supplier requisition (can be a General order), and select General Warehouse.
- [ ] Add items to the list and finalise it.
- [ ] Perform a manual sync and check internal customer requisitions.
- [ ] Open the requisition and check all items were added correctly.

### CODE REVIEW

File: src/database/utilities/createRecord.js [hunk 1]
```diff
@@ -359,7 +359,7 @@ const createTransactionBatch = (database, transactionItem, itemBatch) => {
     sellPrice,
     donor,
     transaction: transactionItem.transaction,
-    sortIndex: transactionItem.transaction ? transactionItem.transaction.numberOfBatches : 0,
+    sortIndex: transactionItem.transaction ? transactionItem.transaction.numberOfBatches + 1 : 1,
```
Comment (joshxg) [inline src/database/utilities/createRecord.js]: Nice :) 

We have this [optional chaining](
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining) syntax available, now - brand new!!!
It is a stage 4 proposal, so safe to use: https://github.com/tc39/proposal-optional-chaining

So this can become `(transactionItem?.transaction?.numberOfBatches || 0) + 1 || 1`

if you use [short circuit evaluation](https://codeburst.io/javascript-short-circuit-conditionals-bbc13ac3e9eb)

I think this is a lot more concise and nicer, what do you think?

Comment (diegoevangelisti) [reply src/database/utilities/createRecord.js]: Thanks, this is great. Getting used to this syntax can take time at the beginning (hard to read to people that is not used to this maybe as well?) but it is a great to avoid deeply-nested structures. Thumbs up to this!

**Comment by diegoevangelisti** [comment]
> Nice! I'm not going to merge this just yet - I hope to release 3.1 today, and don't want the extra testing to hold that back!

Fare enough!

**Comment by joshxg** [comment]
Merged, thanks @diegoevangelisti !
