### PR TITLE
#3158 Missing variable in deps list for ByProgramModal

### LINKED ISSUE #3158: ByProgramModal fields not updating correctly
## Describe the bug

- When changing a the current field from one selection to another, the selection isn't updated correctly

### To reproduce

1. Go to `ByProgramModal`
2. Select a supplier/customer
3. Check programs
4. Select a new supplier/customer which has a different set of programs available
5. See the selection not updated

### Expected behaviour

The list should be updated

### Proposed Solution

Probably memozation issue

### Version and device info

- App version: N/A 
- Tablet model: N/A 
- OS version: N/A

### Additional context

N/A

### PR DESCRIPTION
**Pull request by joshxg**
Fixes #3158 

## Change summary

- Updated variable to refetch modal data once the data of the step has changed

## Testing

- [ ] Selection is updated (as described in issue)

### Related areas to think about

Another indication a refactor needed?

### CODE REVIEW

**Review by Chris-Petty — APPROVED** [review]

File: src/widgets/Step.js [hunk 1]
```diff
@@ -73,7 +74,7 @@ export const Step = memo(props => {
   useEffect(() => {
     if (status !== 'CURRENT' || !getModalData) return;
     setModalData(getModalData());
-  }, [status, internalStatus]);
+  }, [status, internalStatus, data]);
```
Comment (Chris-Petty) [inline src/widgets/Step.js:77]: Did it take long to find this? One of the arguments I read against prematurely optimising with memoization (might have been from the man Dan?) was that it makes tracing bugs a bit more difficult, so is a compromise against the value of the optimisation

Comment (joshxg) [reply src/widgets/Step.js:77]: This one, no - but I have had others that I've had issues with. To be honest, getting pretty good at spotting when it's a memoization problem just from the behaviour of the interface.. 🤣
