### PR TITLE
#2162 fix cash register not filtering reasons

### LINKED ISSUE #2162: Cash transactions not using the specific transaction cash reasons
## Describe the bug

There is a specific type of reason which should be used for cash in reasons

image

### To reproduce

Dispensary development

### Expected behaviour

As above

### Proposed Solution

Create a `UIDatabase` case for this specific type and use that rather than `Options`

### Version and device info

Dispensary development

### Additional context

Dispensary development

### PR DESCRIPTION
**Pull request by wlthomson**
Fixes #2162.

## Change summary

Fixes cash register reason filtering.

## Testing

Steps to reproduce or otherwise test the changes of this PR:

- [ ] Cash out transaction reasons only display `Options` records with type `"newCashOutTransaction"`.

### Related areas to think about

N/A.

### CODE REVIEW

File: src/widgets/modals/CashTransactionModal.js [hunk 1]
```diff
@@ -42,7 +42,7 @@ export const CashTransactionModal = ({ onConfirm }) => {
   const [isDescriptionModalOpen, setIsDescriptionModalOpen] = useState(false);
 
   const names = useMemo(() => UIDatabase.objects('CashTransactionName'));
-  const reasons = useMemo(() => UIDatabase.objects('Options'));
+  const reasons = useMemo(() => UIDatabase.objects('CashTransactionReason'));
```
Comment (joshxg) [inline src/widgets/modals/CashTransactionModal.js]: this needs a dependency list, and the one above - `[]`

Comment (wlthomson) [reply src/widgets/modals/CashTransactionModal.js]: Good catch, de740a0e079c65cdf001008e3d98583422ff2a7e.

Comment (joshxg) [reply src/widgets/modals/CashTransactionModal.js]: https://github.com/openmsupply/mobile/blob/2ca29f7680485d3922950388f263c7b7b78c0477/src/widgets/modals/CashTransactionModal.js#L63-L64 

https://github.com/openmsupply/mobile/blob/2ca29f7680485d3922950388f263c7b7b78c0477/src/widgets/modals/CashTransactionModal.js#L66-L83

Maybe more that I didn't see !
