### PR TITLE
#3006 fix insurance policy lookup is active field

### LINKED ISSUE #3006: Insurance policies from lookup API are inactive (v6)
## Describe the bug

All insurance policies from lookup API are inactive.

### To reproduce

1. Add a patient with at least one active policy using lookup API.
2. Dispense to the patient. Navigate to the payment summary page.
3. Note that the active policy is listed as inactive in the policy dropdown.

### Expected behaviour

Active policies should remain active when added to mobile via the lookup API.

### Proposed Solution

Will need to do a fix for `v4` and `v5` majors.

Problem looks like `parseBoolean` is being called on a value which is a boolean (as opposed to a string). Most defensive solution (although a bit hacky), is to make a small fix to `parseBoolean` to ensure booleans are correctly parsed (currently `parseBoolean(true)` returns `false`).

### Version and device info

- App version: v5.1.0.
- Tablet model: Nexus 10 (emulated).
- OS version: API 28.

### Additional context

N/A.

### PR DESCRIPTION
**Pull request by wlthomson**
Fixes #3006.

## Change summary

Minor fix to boolean parse helper.

## Testing

Steps to reproduce or otherwise test the changes of this PR:

- [ ] Active policies for patients looked up via lookup API are displayed as active.
- [ ] Inactive policies for patients looked up via lookup API are displayed as inactive.

### Related areas to think about

N/A.

### CODE REVIEW

File: src/database/utilities/parsers.js [hunk 1]
```diff
@@ -5,13 +5,11 @@
...
- * @param  {string} numberString The string to convert to a boolean
+ *
+ * @param  {string}  numberString  The string to convert to a boolean
  * @return {boolean}               The boolean representation of the string
  */
-export const parseBoolean = booleanString => {
-  const trueStrings = ['true', 'True', 'TRUE'];
-  return trueStrings.includes(booleanString);
-};
+export const parseBoolean = booleanString => booleanString.toString().toLowerCase() === 'true';
```
Comment (joshxg) [inline src/database/utilities/parsers.js:12]: Looks like this might be getting called with `undefined` or `null`s some might be best to be even more defensive : `booleanString?.toString?.()...`

File: src/sync/lookupApiUtils.js [hunk 2]
```diff
@@ -120,8 +120,8 @@ const processInsuranceResponse = response =>
     })
   );
 
-export const processPatientResponse = response => {
-  const patientData = response.map(
+export const processPatientResponse = response =>
```
Comment (joshxg) [inline src/sync/lookupApiUtils.js:123]: refactor???? 😠

File: src/database/utilities/parsers.js (hunk 1 above)
Comment (wlthomson) [reply src/database/utilities/parsers.js:12]: 4f4a5bd17844653800c02cdf9e2d140a4c308c5a.

File: src/sync/lookupApiUtils.js (hunk 2 above)
Comment (wlthomson) [reply src/sync/lookupApiUtils.js:123]: run

**Comment by wlthomson** [comment]
> it breaks still if you pass `{toString: "AHHHH"}` but I that's not going to happen 🤣

why
