### PR TITLE
#2743 fix lookup search button localisation

### LINKED ISSUE #2743: Patient lookup search button should be titled 'Search'
## Describe the bug

Patient lookup search button is named 'Save' - I think it would make more sense as 'Search'?
image

### To reproduce

1. Go to Dispensary
2. Click on Lookup Patient
3.Look at search button 

### Expected behaviour

Should read 'Search'
### Proposed Solution

Change string to 'Search' string?

### Version and device info

- App version: 5.00.RC1
- Tablet model: 
- OS version:

### PR DESCRIPTION
**Pull request by wlthomson**
Fixes #2743.

## Change summary

Lookup button was displaying default value (`"Save"`) as `saveButtonText` prop was being incorrectly destructured.

## Testing

Steps to reproduce or otherwise test the changes of this PR:

- [ ] Lookup modal button reads `"Search"` (NOT `"Save"`).

### Related areas to think about

N/A.

### CODE REVIEW

File: src/widgets/modals/index.js [hunk 1]
```diff
@@ -10,4 +10,3 @@ export { DemoUserModal } from './DemoUserModal';
 export { FinaliseModal } from './FinaliseModal';
 export { LoginModal } from './LoginModal';
 export { ModalContainer } from './ModalContainer';
-export { DispensaryLookupModal } from './DispensaryLookup';
```
Comment (wlthomson) [inline src/widgets/modals/index.js:13]: Took the opportunity to get rid of this unused component!
