### PR TITLE
#4640 Showing invalid date

### LINKED ISSUE #4640: Showing invalid date
## Describe the bug

Mobile expects a single date format example "01/01/2021" if we send a date in any other format that gives the wrong output like "1/1/2021" which gives an invalid date.

image

### To reproduce

Steps to reproduce the behaviour:

1. Go to mSupply and send any data with the date of format "1/1/2021"
2. Check-in tablet and it will show you an invalid date.

### Expected behaviour
It should show the correct date.

### Proposed Solution

export const convertMobileDateToISO = dateString => {
  if (!dateString) return undefined;

  const separators = ['/', '-'];
  const splitDate = dateString.split(new RegExp(separators.join('|'), 'g'));

  if (splitDate.length !== 3) return undefined;
  const dayOfMonth = splitDate[0].padStart(2, '0');
  const month = splitDate[1].padStart(2, '0');
  const year = splitDate[2].padStart(4, '0');

  return `${year}-${month}-${dayOfMonth}`;
};

### Version and device info

- App version:8.4.1
- Tablet model: In physical device Lenovo, and Emulator as well.
- OS version:

### Additional context

n/a

### PR DESCRIPTION
**Pull request by anildahalsussol**
By default take date format to 'MM/DD/YYYY'

Fixes #4640 

## Change summary

Change date format to 'MM/DD/YYYY'

## Testing

Steps to reproduce or otherwise test the changes of this PR:

- [ ] Add any name notes in msupply and change date to 'm/d/yyyy'.
- [ ] Once it synced to mobile check vaccincation>history for that patient.
- [ ] Check Date it shouldn't show 'Invalid date'.

### Related areas to think about

If there are any general areas of the codebase your changes might have side affects on, mention them here

### CODE REVIEW

File: src/utilities/formatters.js [hunk 1]
```diff
@@ -74,6 +74,7 @@ export const formatDate = date => (date ? moment(date).fromNow() : generalString
  * @return  {string}              A string representing the date in 'yyyy-mm-dd' format
  */
 export const convertMobileDateToISO = dateString => {
+  dateString = moment(dateString).format('MM/DD/YYYY');
```
Comment (katherine-sussol) [inline src/utilities/formatters.js:77]: https://github.com/openmsupply/mobile/issues/4640#issuecomment-1081250954

We could do something like this instead? Still brittle but just handles missing zeros better?
```
export const convertMobileDateToISO = dateString => {
  if (!dateString) return undefined;

  const separators = ['/', '-'];
  const splitDate = dateString.split(new RegExp(separators.join('|'), 'g'));

  if (splitDate.length !== 3) return undefined;
  const dayOfMonth = splitDate[0].padStart(2, '0');
  const month = splitDate[1].padStart(2, '0');
  const year = splitDate[2].padStart(4, '0');

  return `${year}-${month}-${dayOfMonth}`;
};
```

Comment (katherine-sussol) [reply src/utilities/formatters.js:77]: Experimented a bit more, another alternative we could use if we'd still prefer to use moment (but the input format in both of these examples still needs to be DD/MM/YYYY and not MM/DD/YYYY):
`dateString = moment(dateString, 'DD/MM/YYYY').format('DD/MM/YYYY');`

Comment (anildahalsussol) [reply src/utilities/formatters.js:77]: > 

sure I think we can do this... As we will just extract a day, month, and year whatever the format and whatever date it will be. I agree with your suggested solution.

**Review by katherine-sussol — APPROVED** [review]
👍
