### PR TITLE
Remove fullScreen prop making all modals full screen

### LINKED ISSUE #3209: Modals should be full screen
## Describe the bug

`StocktakeBatchModal` and other modals should be full screen

### To reproduce

1. Go to `StocktakeBatchModal`

### Expected behaviour

Modals should be full screen, you can't click behind it and from observing people they often get annoyed

### Proposed Solution

use `fullScreen` prop

### Version and device info

- App version: 6.0RC10
- Tablet model:
- OS version:

### Additional context

N/a

### PR DESCRIPTION
**Pull request by joshxg**
Fixes #3209 

## Change summary

- Removes `fullScreen` prop and changes styles slightly to adjust

## Testing

- [ ] All modals are `fullScreen`

### Related areas to think about

N/A

### CODE REVIEW

File: src/widgets/modals/ModalContainer.js [hunk 1]
```diff
@@ -95,8 +79,8 @@ export const ModalContainer = ({
     <View style={modalContainer}>
       <Modal
         visible={isVisible}
+        presentationStyle="fullScreen"
         animationType="slide"
-        fullScreen={fullScreen}
         transparent
```
Comment (mark-prins) [inline src/widgets/modals/ModalContainer.js:84]: I had to remove `transparent` as I was getting a warning about the presentation style with transparent.

Screen Shot 2020-11-21 at 9 12 48 AM

**Review by mark-prins — DISMISSED** [review]
As commented, I'm getting a warning about a presentationStyle clash with transparent.

Apart from that - all looks good. Works ok, the style look ok and I can't find any 'fullscreen' in the code now 👍 

Always nice to remove a bunch of code and clean things up 😄

**Comment by joshxg** [comment]
Nice - removed the prop also!

Thanks!
