### PR TITLE
#960 fix undefined stocktake name

### LINKED ISSUE #960: General stocktake default name "undefined"
Build Number: 2.3.0 master

Description:
General stocktake can get a name in format "undefined -  - <currentDate+Time>"

Reproducible: yes

Reproduction Steps:
1. Go to general tab when making a new stocktake
2. Tap field then hit keyboard done to dismiss
3. Can proceed without name
image
4. Stocktake name gets messed up 
image

Comments:

### PR DESCRIPTION
**Pull request by Chris-Petty**
Fixes #960

# Testing
**No programs on store**
- [ ] Can create and name a stocktake and it saves the name
- [ ] Can create a stocktake without providing name, gives a useful one "Stocktake - some date/time"

**With programs on store** 
- [ ] Can create and name a general stocktake and it saves the name
- [ ] Can create a general stocktake without providing name (through #960 reproduction steps), gives a useful one "Stocktake - some date/time"
- [ ] Can create and name a program stocktake and it saves the name
- [ ] Can create a program stocktake without providing name (through #960 reproduction steps), gives a useful one "Program name - some date/time"

### CODE REVIEW

File: src/database/utilities/createRecord.js [hunk 1]
```diff
@@ -206,22 +206,25 @@ const createRequisitionItem = (database, requisition, item, dailyUsage) => {
...
  * @return  {Stocktake}
  */
-const createStocktake = (database, { createdBy, program, name }) => {
+const createStocktake = (database, user, stocktakeName, program) => {
   const date = new Date();
-  const { stocktakeText } = generalStrings;
-  const defaultName = `${stocktakeText} - ${name} - ${formatDateAndTime(date, 'slashes')}`;
+  const serialNumber = getNextNumber(database, STOCKTAKE_SERIAL_NUMBER);
+  const title = program ? program.name : generalStrings.stocktake;
+  const defaultName = `${title} - ${formatDateAndTime(date, 'slashes')}`;
```
Comment (sworup) [inline src/database/utilities/createRecord.js]: I guess this is the core code change and the rest are just code refactors. 
Looks good!

Comment (Chris-Petty) [reply src/database/utilities/createRecord.js]: To some degree. The old both `stocktakeText` and `name` were coming through undefined so the refactoring was in part to resolve that.

Also I don't like passing of objects as args and destructuring the props you want out of them. It invites just passing through everything rather than just what you need (i.e. we'd see the entire state of `byProgramModal.js` showing up here before).
