### PR TITLE
#2448 fix error on creating stocktake item for undefined item

### LINKED ISSUE #2448: ItemBatch can sometimes have an undefined Item
## Error in mSupply Mobile

**TypeError** in **MainActivity**
undefined is not an object (evaluating 'o.realItem')

[View on Bugsnag](https://app.bugsnag.com/sustainable-solutions-nz-ltd/msupply-mobile/errors/5e5d92afd76ba6001939533e?event_id=5e5d92af005754ebd1ff0000&i=gh&m=ci)

## Stacktrace

    src/database/utilities/createRecord.js:282 - createStocktakeItem
    src/database/utilities/createRecord.js:474 - createRecord
    src/database/DataTypes/Stocktake.js:85 - 
    src/database/DataTypes/Stocktake.js:82 - value
    src/navigation/actions.js:326 - 
    src/database/UIDatabase.js:183 - value
    src/navigation/actions.js:323 - 
    src/pages/StocktakeManagePage.js:67 - 
    src/mSupplyMobileApp.js:141 - 

[View full stacktrace](https://app.bugsnag.com/sustainable-solutions-nz-ltd/msupply-mobile/errors/5e5d92afd76ba6001939533e?event_id=5e5d92af005754ebd1ff0000&i=gh&m=ci)

*Created automatically via Bugsnag*

### PR DESCRIPTION
**Pull request by wlthomson**
Fixes #2448.

## Change summary

Prevents creating a new `StocktakeItem` for an `undefined` item.

## Testing

Steps to reproduce or otherwise test the changes of this PR:

- Not completely sure how best to replicate this without using corrupted data. Suggest a quick regression test of existing stocktake logic.

### Related areas to think about

N/A.

### CODE REVIEW

File: src/database/DataTypes/Stocktake.js [hunk 1]
```diff
@@ -285,7 +292,10 @@ export class Stocktake extends Realm.Object {
    */
   addItemsFromProgram(database) {
     if (!this.program) return false;
-    this.setItemsByID(database, this.program.items.map(masterListItem => masterListItem.item.id));
+    this.setItemsByID(
+      database,
+      this.program.items.map(masterListItem => masterListItem.item.id)
+    );
```
Comment (wlthomson) [inline src/database/DataTypes/Stocktake.js]: Looks like some prettier changes sneaked into the commit, unrelated to logic changes!
