### PR TITLE
#1343 stocktake updates

### LINKED ISSUE #1343: StocktakeEditPage updates
## Describe the bug

Few bugs in `StocktakeEditPage` highlighted in testing: https://github.com/openmsupply/mobile/issues/1242#issuecomment-540822222

- name `PageInfo` is disabled
- Items are set to the snapshot quantity automatically
- Placeholder does not show

additional:

- can't remove items  from the stocktake
- Bottom confirm modal goes away when nothing is selected, but should always stay

### To reproduce

1. 
- try to edit a name in a stocktake
- see error

2.
- Add an item to a stocktake
- see error

3. 
- try to remove an item from a stocktake
- see error

### Expected behaviour

The opposite of the bugs

### Version and device info

`DataTable` feature branch in development

### Additional context

N/A

### PR DESCRIPTION
**Pull request by joshxg**
Fixes #1343 

## Change summary

- Correctly using placeholders and not counted state for rows in a stocktake
- Made the bottom modal thing in `StocktakeManagePage`  always open
- Corrected logic for remove items from a `Stocktake`
- Corrected logic for the keyboard type for editable cells

## Testing

- [ ] When editing a cell that should be numeric, the numeric keyboard is opened
- [ ] When adding an item to a stocktake, initial state is to be NOT COUNTED
- [ ] When changing a value in a stocktake row, the state is the value entered
- [ ] Can remove items from a `Stocktake`
- [ ] When finalising a `Stocktake`, `Not Counted` rows are pruned

### Related areas to think about
`DataTableRow` getting pretty messy at this point. Could refactor soon!

### CODE REVIEW

**Comment by joshxg** [comment]
I got a little confused - this also basically contains #1339

File: src/widgets/DataTable/DataTableRow.js [hunk 1]
```diff
@@ -88,7 +89,15 @@ const DataTableRow = React.memo(
...
             case COLUMN_TYPES.EDITABLE_STRING:
-            case COLUMN_TYPES.EDITABLE_NUMERIC:
+            case COLUMN_TYPES.EDITABLE_NUMERIC: {
+              // Special condition for stocktake counted total quantity cells.
+              // Use the placeholder 'Not counted' when a stocktake item or batch
+              // has not been counted yet.
+              let placeholder = '';
+              if (columnKey === COLUMN_NAMES.COUNTED_TOTAL_QUANTITY) {
+                placeholder = rowData.hasBeenCounted ? '' : tableStrings.not_counted;
+              }
```
Comment (wlthomson) [inline src/widgets/DataTable/DataTableRow.js]: Maybe can remove the mutable state here, something like:

```
const defaultPlaceholder = '';
const notCountedPlaceholder = tableStrings.not_counted;
const isNotCounted = columnKey === COLUMN_NAMES.COUNTED_TOTAL_QUANTITY && !rowData.hasBeenCounted;
const placeholder = isNotCounted ? notCountedPlaceholder : defaultPlaceholder;

```

Comment (joshxg) [reply src/widgets/DataTable/DataTableRow.js]: as much as I don't like mutating - if it makes it easier to read I just do it, and it seems to be easier to read than those lines? (and also more open to other special conditions if we need to use placeholders for other column types?) :(

Comment (wlthomson) [reply src/widgets/DataTable/DataTableRow.js]: Personally, I find `let` hard to read, because it's harder to reason about the variable state (because it can be changed). Looking at it again, I think I went over the top with variables. You could make the suggestion a bit cleaner:

```
const isNotCounted = columnKey === COLUMN_NAMES.COUNTED_TOTAL_QUANTITY && !rowData.hasBeenCounted;
const placeholder = isNotCounted ? tableStrings.not_counted : '';
```

Let me know either way and I'll merge 👍 .

Comment (joshxg) [reply src/widgets/DataTable/DataTableRow.js]: i think no, simply cause the next cell that needs a placeholder will be screwed!
