### PR TITLE
#1324 SearchBar not dismissing details on StockPage

### LINKED ISSUE #1324: StockPage pop up does not close when search bar is clicked
## Describe the bug

If the search bar is clicked while the`ItemDetails` modal is open, the modal does not close.

#1324-stockpage-popup-not-closing

### To reproduce

1. Go to 'Current Stock`.
2. Click on a row. The `ItemDetails` modal should appear at the bottom of the screen.
3. Click on the search bar.
4. See error.

### Expected behaviour

The `ItemDetails` modal should close when the search bar is focussed. 

### Version and device info

- App version: 2.3.7.
- Tablet model: TB-X304L (replicated with emulator).
- OS version: 8.1.0.

### Additional context

See https://github.com/openmsupply/mobile/issues/1245#issuecomment-536812130.

### PR DESCRIPTION
**Pull request by joshxg**
Fixes #1324 

## Change summary

-  Updated memoization, closure wasn't updating

## Testing

- [ ] When the item details popup is open, focusing the `SearchBar` dismisses the item details

### Related areas to think about

N/A

### CODE REVIEW

File: src/widgets/SearchBar.js [hunk 1]
```diff
@@ -98,9 +98,17 @@ export const SearchBarComponent = ({
...
+ * Only re-render this component when the value or onFocusOrBlur
+ * props change.
  */
-const propsAreEqual = ({ value: prevValue }, { value: nextValue }) => prevValue === nextValue;
+const propsAreEqual = (
+  { value: prevValue, onFocusOrBlur: prevOnFocusOrBlur },
+  { value: nextValue, onFocusOrBlur: nextOnFocusOrBlur }
+) => {
+  const valuesAreEqual = prevValue === nextValue;
+  const onFocusOrBlueAreEqual = prevOnFocusOrBlur === nextOnFocusOrBlur;
```
Comment (wlthomson) [inline src/widgets/SearchBar.js]: `onFocusOrBlue` typo.

Comment (joshxg) [reply src/widgets/SearchBar.js]: 2b70acd
