### PR TITLE
#2046 localize dates

### LINKED ISSUE #2046: Localize dates
## Describe the bug

Dates aren't localized

### To reproduce

See a date when using french language

### Expected behaviour

Dates should be localized

### Proposed Solution

N/A

### Version and device info

N/A

### Additional context

N/A

### PR DESCRIPTION
**Pull request by joshxg**
Fixes #2046 

## Change summary

- Adds a function to set the date locale of `moment` when changing the language of the app.

## Testing

N/A

### Related areas to think about

N/A

### CODE REVIEW

File: src/settings/MobileAppSettings.js [hunk 1]
```diff
@@ -30,6 +30,7 @@ class MobileAppSettings extends Settings {
     const currentLanguage = this.get(SETTINGS_KEYS.CURRENT_LANGUAGE);
     setCurrentLanguage(currentLanguage);
```
Comment (wlthomson) [inline src/settings/MobileAppSettings.js]: Might be missing some info, but I can't think of a situation where you would want to set these to different languages. If that's the case, I think could make this a bit tidier by calling them all in `setCurrentLanguage`?

File: src/settings/MobileAppSettings.js [hunk 2]
```diff
@@ -30,6 +30,7 @@ class MobileAppSettings extends Settings {
...
     setCurrencyLocalisation(currentLanguage);
+    setDateLocale(currentLanguage);
```
Comment (wlthomson) [inline src/settings/MobileAppSettings.js]: I think this is more setting "format" rather than locale. I think this has a bit of potential for confusion, e.g. between a currency format and an actual unit of currency, or a date format and a timezone. Maybe something like `setCurrencyLanguage`, `setDateLanguage`, or `setCurrencyFormat(currentLanguage)`, `setDateFormat(currentLanguage)`?

Comment (joshxg) [reply src/settings/MobileAppSettings.js]: yeah you're right - will fix soon
