### PR TITLE
#2470 fix address country not saving

### LINKED ISSUE #2470: Some fields in new patient form don't get saved
## Describe the bug
When adding new patient fields like `Address 1`, `Address 2`, `Country` don't get saved after clicking `Save` button

### To reproduce

1. Go to Dispensary > New patient
2. Fill up a form with some values
3. Tab `Save` button to save
4. Tap a edit button to re-open that form and see those 3 fields now have an empty values

### Expected behaviour
Entered values should get saved after tapping `Save` button

### Version and device info

- App version: 4.0.0

### PR DESCRIPTION
**Pull request by wlthomson**
Fixes #2470.

## Change summary

Fixes patient billing addresses and country not saving/syncing.

## Testing

Steps to reproduce or otherwise test the changes of this PR:

- [ ] Edit a patient `"Address 1"`. Close and reopen. The patient `"Address 1"` is updated.
- [ ] Edit a patient `"Address 2"`. Close and reopen. The patient `"Address 2"` is updated.
- [ ] Edit a patient `"Country"`. Close and reopen. The patient `"Country"` is updated.

### Related areas to think about

N/A.

### CODE REVIEW

File: src/actions/PatientActions.js [hunk 1]
```diff
@@ -32,11 +32,11 @@ const patientUpdate = completedForm => (dispatch, getState) => {
   const { currentPatient } = patient;
 
   if (currentPatient) {
-    const { addressOne, addressTwo } = completedForm;
+    const { addressOne: line1, addressTwo: line2 } = completedForm;
     const { billingAddress } = currentPatient;
 
     UIDatabase.write(() => {
-      UIDatabase.update('Address', { ...billingAddress, line1: addressOne, line2: addressTwo });
+      UIDatabase.update('Address', { ...billingAddress, line1, line2 });
```
Comment (mark-prins) [inline src/actions/PatientActions.js]: really?! Can't see why it would require this, but sure. if it works.

**Comment by wlthomson** [comment]
Update: had to do some rebasing and cherry-picking to rewrite the history to be based on `master` not `develop`. No code changes.

File: src/actions/PatientActions.js (hunk 1 above)
Comment (wlthomson) [reply src/actions/PatientActions.js]: This was just a sneaky tidy up, not required!
