### PR TITLE
#3034 update period date formatting

### LINKED ISSUE #3034: Format and value of period dates
## Describe the bug

The start and end date of periods, shown when creating a new requisition, are both incorrect and in US date format.

### To reproduce

Steps to reproduce the behaviour:

1. Change regional settings on the tablet, so that the timezone is non-NZ ( I selected the region of Côte d'Ivoire => GMT )
2. Create a new program-based supplier requisition
3. When you reach the `period` selection, observe the dates and compare to mSupply

### Expected behaviour

- Date format should be consistent. Currently, mSupply shows DD/MM/YYYY and mobile shows MM/DD/YYYY
- Dates are affected by the timezone difference between server and mobile

### Additional context

Screen Shot 2020-07-20 at 5 29 13 PM

### PR DESCRIPTION
**Pull request by wlthomson**
Fixes #3034.

## Change summary

Update period date formatting for consistency with desktop.

## Testing

Steps to reproduce or otherwise test the changes of this PR:

- [ ] Period start and end date is formatted as `DD/MM/YY` when creating a new program requisition.
- [ ] Period start and end date is formatted as `DD/MM/YY` when viewing a program requisition.

### Related areas to think about

N/A.

### CODE REVIEW

File: src/database/DataTypes/Period.js [hunk 1]
```diff
@@ -48,7 +49,9 @@ export class Period extends Realm.Object {
   }
 
   toString() {
-    return `${this.startDate.toLocaleDateString()} - ${this.endDate.toLocaleDateString()}`;
+    const startDate = moment(this.startDate).format('DD/MM/YY');
```
Comment (mark-prins) [inline src/database/DataTypes/Period.js:52]: I went with a 
```
const DATE_FORMAT = 'DD/MM/YY';

export const formatDate = date => moment(date).format(DATE_FORMAT);
```

in `localization/utilities` and used that. Possibly overkill, but we may need date formatting elsewhere and may need to have a localisation friendly format?

Comment (wlthomson) [reply src/database/DataTypes/Period.js:52]: Fair enough. There's a few other hardcoded formatting strings so I'll make a new issue for this 👍 .
