### PR TITLE
#2900 TemperatureBreach stats incorrect [Branched from: #2874] 

### LINKED ISSUE #2900: Breach stats logically incorrect
## Describe the bug

The stats for a breach: Total stock, number of affected batches are not being determined correctly.

The `Location` is determining if item batches were in a breach using a query on it's `LocationMovements` like:
- `(enterTimestamp <= $0 && (exitTimestamp > $0 || exitTimestamp == null))`

But it should be using a query like:

- `'enterTimestamp <= $0 && (exitTimestamp > $0 || exitTimestamp == null) ||' + 'enterTimestamp >= $0 && enterTimestamp <= $1',`

This will more accurately capture if an `ItemBatch` was in a Location during the time of a breach.

- The `totalStock()` can be more easily calculated by adding a `linkingObjects` on `Location` for `itemBatches`, and calculating the number of packs, from there.

### To reproduce

code logic bug

### Expected behaviour

As above

### Proposed Solution

As above

### Version and device info

- App version: Vaccine development
- Tablet model: N/A
- OS version: N/A

### Additional context

N/A

### PR DESCRIPTION
**Pull request by joshxg**
Fixes #2900 

## Change summary

- Changed `batchesAtTime` to `batchesDuringTime`, having it receive a range rather than a single moment in time. Then changed the query such that the batch should be in the location either before the initial start time, and having left it either never, or some time after the starting time OR entered it after the start time but before the end time. This is because the old query was not capturing those batches which had entered after a breach had started, but before it had finished (primarily, for very long breaches! Some fridges in Vannuatu are just permanently breached :( )
- simplified `totalStock`

## Testing
N/A

### Related areas to think about

N/A

### CODE REVIEW

File: src/database/DataTypes/TemperatureBreach.js [hunk 1]
```diff
@@ -44,7 +44,7 @@ export class TemperatureBreach extends Realm.Object {
   }
 
   affectedBatches(database) {
-    return this.location.batchesAtTime(database, this.endTimestamp);
+    return this.location.batchesDuringTime(database, this.startTimestamp, this.endTimestamp);
```
Comment (wlthomson) [inline src/database/DataTypes/TemperatureBreach.js:47]: I think `location` is optional? Maybe some defensive code here?

Comment (joshxg) [reply src/database/DataTypes/TemperatureBreach.js]: Added here. 
31b2b08 

Note I've merged a whole bunch of PRs into this one so just look at that commit 🤣
