### PR TITLE
#1249 extract state initialisers

### LINKED ISSUE #1249: State initialisers should be extracted
## Describe the bug

Each page uses a `stateInitialiser` function. This function is within the `XXXPage` component. It should be extracted for the benefits:

- Simple method to use to 'reset' state of a component by the components reducer
- Component becomes a bit cleaner.

I think this would potentially be a good method to call after pushing to the navigation stack - so that poping (and returning to the screen) would result in a clean page, rather than a potentially dirty one with still selected items etc. Of course you can just add into the code to unselect all items etc etc, but it is a lot simpler to just re-init the state. Would ensure nothing was missed (i.e. forgetting to reset `modalKey: ''` to ensure the modal is closed.

Couple of options as pointed out here: https://github.com/openmsupply/mobile/pull/1215#discussion_r324481839

I'm going to make a claim that reading from the DB is an OK thing to do in the reducer. Essentially we are already doing this with `backingData` and any `pageObject`. Reading a requisitions `items` field is essentially equivalent to reading `UIDatabase.objects("X")`

I think having these functions in `pageReducers`?

Also https://github.com/openmsupply/mobile/pull/1216#discussion_r324486286

Need to also ensure `usePageReducer` can be used without having one of these intiialiser functions defined. Also each initialiser may need to be derived from props passed to the component (i.e. a requisition)

### To reproduce

Development

### Expected behaviour

N/A

### Version and device info

- App version:
- Tablet model:
- OS version:

### PR DESCRIPTION
**Pull request by wlthomson**
Fixes #1249.

## Change summary

Simplifies page logic by moving initialisation logic into a dedicated file and updating the `usePageReducer` hook signature to more closely resemble the standard React `useReducer` hook. 

## Testing

Steps to reproduce or otherwise test the changes of this PR:

- [ ] All pages still work and don't crash!

### Related areas to think about

Updated initialisation naming to UK English 🇬🇧 style (both US and UK were being used in different contexts). If people prefer US 🇺🇸 naming, can update with a quick find/replace.

### CODE REVIEW

File: src/pages/dataTableUtilities/getPageInitialiser.js [hunk 1]
```diff
@@ -0,0 +1,213 @@
...
+ * mSupply Mobile
+ * Sustainable Solutions (NZ) Ltd. 2019
+ */
+
+import { UIDatabase } from '../../database';
+import Settings from '../../settings/MobileAppSettings';
+
+import { newSortDataBy, getAllPrograms } from '../../utilities';
+import { recordKeyExtractor } from './utilities';
+
```
Comment (joshxg) [inline src/pages/dataTableUtilities/getPageInitialiser.js]: There are two other components which use `NewStocktakeBatchModal` and `RegimenDataModal` -- They're very weird components that I hate, but they'll be broken. Not 100% sure the best way to handle. I don't think bother moving their initialisers into the file but keeping it usable in `usePageReducer`?

File: src/pages/dataTableUtilities/getPageInitialiser.js [hunk 2]
```diff
@@ -0,0 +1,213 @@
...
+  searchTerm: '',
+  filterDataKeys: ['item.name'],
+  sortBy: 'itemName',
+  isAscending: true,
+  modalKey: '',
+  modalValue: null,
+  hasSelection: false,
+});
+
+const customerInvoicesInitialiser = () => {
```
Comment (joshxg) [inline src/pages/dataTableUtilities/getPageInitialiser.js]: do you think these need doc strings or ott

File: src/pages/dataTableUtilities/getPageInitialiser.js [hunk 3]
```diff
@@ -0,0 +1,213 @@
...
+    supplierInvoice: supplierInvoiceInitialiser,
+    supplierInvoices: supplierInvoicesInitialiser,
+    supplierRequisition: supplierRequisitionInitialiser,
+    supplierRequisitions: supplierRequisitionsInitialiser,
+  };
+
+  return pageToInitialiser[page];
+};
+
+export default getPageInitialiser;
```
Comment (joshxg) [inline src/pages/dataTableUtilities/getPageInitialiser.js]: https://blog.neufund.org/why-we-have-banned-default-exports-and-you-should-do-the-same-d51fdc2cf2ad

**Comment by joshxg** [comment]
I'll also note that after this is merged we can use it in a few pages where `useNavigationFocus` is used. Instead of `refreshData`, we can call an action `reInit`? which will set the state as the initial state again (I think this should be a new issue, not done here)

File: src/pages/dataTableUtilities/getPageInitialiser.js (hunk 3 above)
Comment (wlthomson) [reply src/pages/dataTableUtilities/getPageInitialiser.js]: Yeah, I'm not a big fan of `default`. I think it's best to address this in a separate issue, for consistencies sake with other methods (e.g. `getColumns`, `getPageInfoColumns` also `default export`, so my though would be to keep `getPageInitialiser` consistent). 

If we want to go with this pattern, will also need to update the eslint config as we currently use air-bnb's `prefer-default-export`: https://github.com/airbnb/javascript#modules--prefer-default-export.

Comment (joshxg) [reply src/pages/dataTableUtilities/getPageInitialiser.js]: you're right! Was going to do it here.. oopsies https://github.com/openmsupply/mobile/issues/845#issuecomment-524062278 (more just bringing this to attention than requiring some sort of change right now :))

**Comment by joshxg** [comment]
I've also had a change of heart 🤣  re my last comment - after playing around I like how the state stays the exact same after navigating !

File: src/pages/dataTableUtilities/getPageInitialiser.js [hunk 4]
```diff
@@ -0,0 +1,213 @@
...
+    filterDataKeys: ['serialNumber', 'otherStoreName.name'],
+    sortBy: 'serialNumber',
+    isAscending: true,
+    modalKey: '',
+    hasSelection: false,
+  };
+};
+
+const getPageInitialiser = page => {
+  const pageToInitialiser = {
```
[the remark this answers is not in the document]
Comment (wlthomson) [reply src/pages/dataTableUtilities/getPageInitialiser.js]: Oops, I meant to finish this off with a closure. I like the idea of modules only exporting functions without any "implicit" closures. See what you think: 5eecb6f87c1eda83782ba1b3f50424d8346860a2.

File: src/hooks/usePageReducer.js [hunk 5]
```diff
@@ -37,25 +38,24 @@ import { debounce } from '../utilities/index';
  *
  * @param {String} page                   routeName for the current page.
  * @param {Object} initialState           Initial state of the reducer
- * @param {Func}   initializer            Function to generate the initial state (optional)
+ * @param {Func}   initialiser            Function to generate the initial state (optional)
```
[the remark this answers is not in the document]
Comment (wlthomson) [reply src/hooks/usePageReducer.js]: 8dc05cd9142146d6a373e0177c940c551157e1e8.

My opinion if anyone interested: I think that having an initialiser parameter leaves the usage a bit ambiguous, as it implies the caller has to have knowledge of what pages the reducer knows about or always provide a backup initialiser. I think it'd be nice to extract out all initialisation from the caller by essentially restricting it to callers which have hardcoded initialisers (can think of these as the set of pages the function is defined over). It seems counter-intuitive, but I think that adding the optional parameter actually makes the reducer more as opposed to less tightly coupled.

File: src/pages/dataTableUtilities/getPageInitialiser.js (hunk 1 above)
Comment (wlthomson) [reply src/pages/dataTableUtilities/getPageInitialiser.js]: 7fe5aed1a656a7173223ed4d6169891948aadd4c.

Updated `NewStocktakeBatchModal` to use new `usePageReducer`. I think `RegimenDataModal` should be fixed in its own issue (it still uses `useReducer` with its own actions and reducer).

File: src/pages/dataTableUtilities/getPageInitialiser.js (hunk 2 above)
Comment (wlthomson) [reply src/pages/dataTableUtilities/getPageInitialiser.js]: 🤣 . 98bc3c103448b3fcef6587e2ff3c600f89eeb246.

File: src/pages/dataTableUtilities/getPageInitialiser.js [hunk 6]
```diff
@@ -0,0 +1,322 @@
...
+
+  return {
+    pageObject: requisition,
+    backingData,
+    data: showAll
+      ? backingData.sorted('item.name').slice()
+      : backingData.filter(item => item.isLessThanThresholdMOS),
+    keyExtractor: recordKeyExtractor,
+    dataState: new Map(),
+    currentFocusedRowKey: null,
```
Comment (joshxg) [inline src/pages/dataTableUtilities/getPageInitialiser.js]: dont need this

File: src/pages/dataTableUtilities/getPageInitialiser.js [hunk 7]
```diff
@@ -0,0 +1,322 @@
...
+  backingData: requisition.items,
+  data: requisition.items.sorted('item.name').slice(),
+  keyExtractor: recordKeyExtractor,
+  dataState: new Map(),
+  searchTerm: '',
+  filterDataKeys: ['item.name', 'item.code'],
+  sortBy: 'itemName',
+  isAscending: true,
+  modalKey: '',
+});
```
Comment (joshxg) [inline src/pages/dataTableUtilities/getPageInitialiser.js]: missing `modalValue`

File: src/pages/dataTableUtilities/getPageInitialiser.js [hunk 8]
```diff
@@ -0,0 +1,322 @@
...
+};
+
+/**
+ * Gets data for initialising a customer requisition page from an associated requisition.
+ *
+ * @param    {Requisition}  requisition
+ * @returns  {object}
+ */
+const customerRequisitionInitialiser = requisition => ({
+  requisition,
```
Comment (joshxg) [inline src/pages/dataTableUtilities/getPageInitialiser.js]: should be `pageObject`

File: src/pages/dataTableUtilities/getPageInitialiser.js [hunk 9]
```diff
@@ -0,0 +1,322 @@
...
+import { recordKeyExtractor } from './utilities';
+
+/**
+ * Gets data for initialising a customer invoice page from an associated transaction.
+ *
+ * @param    {Transaction}  transaction
+ * @returns  {object}
+ */
+const customerInvoiceInitialiser = transaction => ({
+  transaction,
```
Comment (joshxg) [inline src/pages/dataTableUtilities/getPageInitialiser.js]: pageObject

File: src/hooks/usePageReducer.js (hunk 5 above)
[the remark this answers is not in the document]
Comment (joshxg) [reply src/hooks/usePageReducer.js]: more tightly coupled with what?

The intention with this was essentially to create a middleware for `useReducer`.. it slowly expanded into injecting props for a bit of DRYness (all of them could just be called in a page). 

I think possibly the best option would be to make a `useThunkReducer` hook - which is the middleware hook. Then, the `usePageReducer` hook could just inject properties. However, I also wonder now if we should just put the field injections straight into the initial state - maybe that would be less confusing heh

[the remark this answers is not in the document]
Comment (wlthomson) [reply src/hooks/usePageReducer.js]: Oops, just saw this. I agree with that.

My anti-initialisation parameter thoughts clarified:

I like the idea of `usePageReducer` only being usable by pages which are known to the application, as it allows all the state to be abstracted away from the page.  It feels a bit wrong for the caller to be initialising state which it doesn't maintain.

Thinking of DRY, it also makes sense that all pages should have the source of truth for their initialisers in a single place, rather than having a division between pages with and without hardcoded initialisers.

In that context, I think your suggestion of separating out `usePageReducer` into two reducer is a good one, it allows a clearer separation between the more static "page" state and the more dynamic/side-effecty "data" state.
