### PR TITLE
#1800 only next with items

### LINKED ISSUE #1800: Disabled the Next button until items have been chosen in a prescription
## Describe the bug

Currently can proceed through the 'checkout' with no items. 

### To reproduce

1. Create a new prescription
2. don't add any items and click next

### Expected behaviour

`NEXT` should be disabled until at least one item has been chosen.

### Proposed Solution

N/A

### Version and device info

Dispensing development

### Additional context

N/A

### PR DESCRIPTION
**Pull request by joshxg**
#### BRANCHED FROM #1800

Fixes #1800 

## Change summary
- Adds a selector which checks if the current prescription has items and quantity applied.
- Adds a `createRecord` parameter to set an initial value of the `TransactionItem`.. this has been set to 1 for a prescription, and also adjusted the lower limit of the stepper.

## Testing

N/A

### Related areas to think about

N/A

### CODE REVIEW

File: src/widgets/StepperRow.js [hunk 1]
```diff
@@ -60,7 +60,7 @@ const localStylez = {
 };
```
Comment (mark-prins) [inline src/widgets/StepperRow.js]: wait, `localStylez`?? how did that slip past?

Comment (joshxg) [reply src/widgets/StepperRow.js]: whoops will get that fixed up 🤣

**Comment by joshxg** [comment]
thoughts were:
- If it's in the 'cart' it would have a quantity.. most/all 'cart' type interfaces I have tried out recently have a default of 1 when you add it.
- Could potentially be customizable for an item..?
- could save a press in a lot of cases?
