### PR TITLE
#2062 cash in cash out totals incorrect

### LINKED ISSUE #2062: Custoemr Credit made from a cash in is incorrect
## Describe the bug

Custoemr Credit made from a cash in is incorrect

### To reproduce

Dispensary development bug

### Expected behaviour

- Should have correct total, subtotal - the negative amount of the total of the RC

### Proposed Solution

N/A

### Version and device info

N/A

### PR DESCRIPTION
**Pull request by joshxg**
Fixes #2062 

## Change summary

- Save the transaction total amount on a Transaction rather than trying to use the derived value for anything other than a `ps` or `rc`, 'sc', 'cc' when finalising. Avoiding regressions by keeping the same behaviour for the existing types. The only problem is for the `ci` created for a cash out which would technically get through and have it's `total` reset, but the finalise method isn't used for that type. I don't think that's a good enough reason, so I think this still needs some thinking - it is working for now though.. :(
- Can then use `total` field in `outgoingSync` for all cases.
- Using `total` field in all cases fixes this for the `cc` and `ci`

## Testing

N/A

### Related areas to think about

- There's probably so more nicer cleanup to do here. I think using a different method to determine the total for cash transactions would be nice? I.e. if no `Item`, try see if there are any `batch` or something like that.

### CODE REVIEW

File: src/database/DataTypes/Transaction.js [hunk 1]
```diff
@@ -449,6 +457,13 @@ export class Transaction extends Realm.Object {
     }
     if (!this.isConfirmed) this.confirm(database);
 
+    // Finding the totalPrice propogates through `TransactionItem` records down to the batch
+    // level, deriving the full cost of the Transaction. Cash transactions and credits are
+    // created finalised, having their total already set.
+    if (!this.isCashTransaction || !this.isCredit) {
```
Comment (wlthomson) [inline src/database/DataTypes/Transaction.js]: Should this be `!(this.isCashTransaction || this.isCredit)`

File: src/sync/outgoingSyncUtils.js [hunk 2]
```diff
@@ -188,21 +185,18 @@ const generateSyncData = (settings, recordType, record) => {
...
         mode: record.mode,
         prescriber_ID: record.prescriber && record.prescriber.id,
-        total,
-        foreign_currency_total: total,
+        total: String(record.total),
+        foreign_currency_total: String(record.total),
         their_ref: record.theirRef,
         confirm_date: getDateString(record.confirmDate),
-        subtotal: total,
+        subtotal: String(record.total),
```
Comment (wlthomson) [inline src/sync/outgoingSyncUtils.js]: Nite: might be nicer to do something like:

```
const total = String(record.total);
return {
  ...
  total,
  foreign_currency_total: total,
  ...
  subtotal: total.
  ...
};
```

Or, something I just found out works in JS:


```
const foreign_currency_total = subtotal = total = String(record.total);
return {
  ...
  total,
  foreign_currency_total,
  ...
  subtotal,
  ...
};
```

😆 .

File: src/database/DataTypes/Transaction.js (hunk 1 above)
Comment (joshxg) [reply src/database/DataTypes/Transaction.js]: embares

https://github.com/openmsupply/mobile/pull/2136/commits/e7870f102c8abf3ecfd77e57f4a961c1c1f633b4

File: src/sync/outgoingSyncUtils.js (hunk 2 above)
Comment (joshxg) [reply src/sync/outgoingSyncUtils.js]: about to do a new PR for #2134 that changes more things regarding total, so will change this up there
