### PR TITLE
#3569  Breaches only create, never continue

### LINKED ISSUE #3569: Temperature breaches are being created rather than continuing
## Describe the bug

When in breach, a temperature breach is created every download, rather than adding the logs to the previous breach.

### To reproduce

1. Go to add a sensor and let it download for a while while in a temperature that is in breach
2. check the realm and see there are a lot of breaches.

### Expected behaviour

Breaches should continue rather than be created contiuously

### Proposed Solution

TBD

### Version and device info

- App version: 7.0.0-RC5
- Tablet model:
- OS version:

### Additional context

N/A

### PR DESCRIPTION
**Pull request by joshxg**
Fixes #3569 

## Change summary

- Fair few changes. Primarily this was to ensure breaches are being continued rather than only created. To do this required mainly date format changes, which revealed a few other issues which i'll comment in the PR

## Testing
Set up a new sensor
- [ ] When the sensor goes in to a breach, all the logs for that breach are aggregated into a single temperature breach record
- [ ] When the sensor goes out of the breach, the end timestamp is correctly applied to the breach.

### Related areas to think about

Trying to share the logic between the apps needed more thinking through, this is a bit of a mess sorry :(

### CODE REVIEW

File: src/actions/BreachActions.js [hunk 1]
```diff
@@ -23,18 +23,24 @@ const createConsecutiveSuccess = (sensor, updatedBreaches, updatedLogs) => ({
 });
 
 const createConsecutiveBreaches = sensor => async dispatch => {
-  const { id } = sensor;
+  const { id: sensorID } = sensor;
 
   try {
-    const logs = await BreachManager().getLogsToCheck(id);
+    const logs = await BreachManager().getLogsToCheck(sensorID);
+    const mappedToPlainObjects = logs.map(({ id, temperature, timestamp }) => ({
```
Comment (joshxg) [inline src/actions/BreachActions.js:30]: When we assign a `breach` in the `BreachManager` to a log, we are actually assigning to a realm object which would throw an error because you can only edit realm objects within a realm transaction, so mapped this to a plain object.. this only started happening when I corrected the the logic to actually close off breaches

Comment (joshxg) [reply src/actions/BreachActions.js:30]: Maybe should add a `toJSON` to the `TemperatureLog` class

File: src/actions/BreachActions.js [hunk 2]
```diff
@@ -23,18 +23,24 @@ const createConsecutiveSuccess = (sensor, updatedBreaches, updatedLogs) => ({
...
     const configs = sensor.breachConfigs;
-    const mostRecentBreach = await BreachManager().getMostRecentBreach(id);
+    const mostRecentBreach = await BreachManager().getMostRecentBreach(sensorID);
     const [breaches, temperatureLogs] = await BreachManager().createBreaches(
       sensor,
-      logs,
+      mappedToPlainObjects,
       configs,
-      mostRecentBreach
+      mostRecentBreach?.toJSON()
```
Comment (joshxg) [inline src/actions/BreachActions.js:41]: Same logic with the log above, just now when assigning an `endTimestamp` to the breach

File: src/bluetooth/BreachManager.js [hunk 3]
```diff
@@ -25,8 +25,8 @@ const createBreachRecord = (
     thresholdMaxTemperature,
     thresholdDuration,
     type,
-    startTimestamp,
-    endTimestamp,
+    startTimestamp: new Date(startTimestamp * MILLISECONDS.ONE_SECOND),
+    endTimestamp: endTimestamp ? new Date(endTimestamp * MILLISECONDS.ONE_SECOND) : endTimestamp,
```
Comment (joshxg) [inline src/bluetooth/BreachManager.js:29]: when creating a breach, the logs from the bluetooth are a unix timestamp

File: src/bluetooth/BreachManager.js [hunk 4]
```diff
@@ -170,17 +174,11 @@ class BreachManager {
   getTemperatureLogsFrom = async (sensorId, timeToCheckFrom) =>
     this.db.getTemperatureLogsFrom(sensorId, timeToCheckFrom);
 
-  getMostRecentBreachLog = async sensorId => {
-    this.db.getMostRecentBreachLog(sensorId);
-  };
+  getMostRecentBreachLog = async sensorId => this.db.getMostRecentBreachLog(sensorId);
```
Comment (joshxg) [inline src/bluetooth/BreachManager.js:177]: these methods weren't returning anything

File: src/bluetooth/VaccineDataAccess.js [hunk 5]
```diff
@@ -48,12 +48,18 @@ export class VaccineDataAccess {
...
+  upsertBreaches = breaches => {
     this.db.write(() => {
       breaches.forEach(breach => {
-        this.db.update(VACCINE_ENTITIES.TEMPERATURE_BREACH, breach);
+        this.db.update(VACCINE_ENTITIES.TEMPERATURE_BREACH, {
+          ...breach,
+          id: breach.id,
+          startTimestamp: new Date(breach.startTimestamp),
+          endTimestamp: breach.endTimestamp ? new Date(breach.endTimestamp) : breach.endTimestamp,
+        });
```
Comment (joshxg) [inline src/bluetooth/VaccineDataAccess.js:59]: Ensuring dates are Date's when saving to realm

File: src/database/DataTypes/TemperatureBreach.js [hunk 6]
```diff
@@ -82,6 +82,21 @@ export class TemperatureBreach extends Realm.Object {
...
+      endTimestamp: this.endTimestamp?.getTime(),
+      locationID: this.location.id,
+      thresholdMaxTemperature: this.thresholdMaxTemperature,
+      thresholdMinTemperature: this.thresholdMinTemperature,
+      thresholdDuration: this.thresholdDuration,
+      acknowledged: this.acknowledged,
+      type: this.type,
+      sensorID: this.sensor.id,
+    };
+  }
```
Comment (joshxg) [inline src/database/DataTypes/TemperatureBreach.js:99]: Is this name OK or `toObject` is better?

**Review by joshxg — COMMENTED** [review]
Hm this took a while to figure out. Not happy about all the mess 😢

File: src/bluetooth/VaccineDataAccess.js (hunk 5 above)
Comment (katherine-sussol) [reply src/bluetooth/VaccineDataAccess.js:59]: So many different kinds of dates and objects 😕  eep. I think the default here is (just a little) counter-intuitive, more explicit to just set to `null` if no `endTimestamp`?

File: src/database/DataTypes/TemperatureBreach.js (hunk 6 above)
Comment (katherine-sussol) [reply src/database/DataTypes/TemperatureBreach.js:99]: I like `JSON`, less ambiguity between regular JS and Realm object 🤔

**Review by katherine-sussol — APPROVED** [review]
Looking good 👍 . 

I got a little trapped by the fact the breach configs are copied to the breach record (i.e. can't 'end' a breach by simply increasing the threshold) 😆  but was able to successfully end a hot consecutive breach by mocking a temperature to something lower than the original threshold.

**Comment by joshxg** [comment]
Thanks @katherine-sussol 

I think it's maybe a good thing that breaches are not updated with new configs settings, but I'm not sure. I think it's probably a bit of an edge case, anyway and people most likely wont be updating the breach configs very frequently.. 🤷

**Review by mark-prins — APPROVED** [review]
Looks fine to me :) Seems to work.. though I trust @katherine-sussol's testing more than mine 😉

**Comment by mark-prins** [comment]
I see the `JSON` comment now..
Maybe `toJSONObject` 🤷‍♂️

**Comment by katherine-sussol** [comment]
> I see the `JSON` comment now..
> Maybe `toJSONObject` 🤷‍♂️

Or what about `toJSObject`? 😆  I think it's the notation part that denotes stringy-ness? Hah now there are too many options. Oh no 🏃‍♀️

**Comment by joshxg** [comment]
I'm gonna merge to get these pr's in - I think `toObject` is probably the way to go, so I'll make a new PR for that with the other ones I've added in other PR's, heh.
