### PR TITLE
#1277 Expiry date column key

### LINKED ISSUE #1277: ExpiryDate cells in DataTableRow broken
## Describe the bug

- `ExpiryDate` cells rendered through `DataTableRow` is broken due to column type

### To reproduce

1. Go to above cell

### Expected behaviour

Should work

### Version and device info

DataTable refactor branch

### Additional context

The keys are a little confused also, could be changed

### PR DESCRIPTION
**Pull request by joshxg**
Fixes #1277 

## Change summary

- Column type of expiry date was `editableExpiryDate` but `DataTableRow` was trying to render `EDITABLE_DATE` - corrected this
- Also changed types to be in the form `EDITABLE_XX` from `XX_EDITABLE` just to match the actual scalar value `editableXXX` cause I was getting confused

## Testing

See #1043 

### Related areas to think about

N/A

### CODE REVIEW

File: src/widgets/DataTable/DataTableRow.js [hunk 1]
```diff
@@ -87,8 +87,8 @@ const DataTableRow = React.memo(
           const cellAlignment = alignText || 'left';
 
           switch (type) {
-            case COLUMN_TYPES.STRING_EDITABLE:
-            case COLUMN_TYPES.NUMERIC_EDITABLE:
+            case COLUMN_TYPES.EDITABLE_STRING:
+            case COLUMN_TYPES.EDITABLE_NUMERIC:
               return (
                 <TextInputCell
                   key={columnKey}
```
Comment (mark-prins) [inline src/widgets/DataTable/DataTableRow.js]: line 106 will need updating:

`type === COLUMN_TYPES.NUMERIC ? COLUMN_TYPES.NUMERIC_EDITABLE : 'default'`

should be 

`type === COLUMN_TYPES.NUMERIC ? COLUMN_TYPES.EDITABLE_NUMERIC : 'default'`

Comment (joshxg) [reply src/widgets/DataTable/DataTableRow.js]: fc2ec4a508c62d362e524ebcd5794ca99f79f40f thanks!
