### PR TITLE
#2333 Remove item code column for supplier credits

### LINKED ISSUE #2333: SupplierCredit created from an item shouldn't display the item code
## Describe the bug

In a `SupplierCredit` created for an `Item` rather than an `Invoice`, the `ItemCode` column is redundant

### To reproduce

N/A

### Expected behaviour

N/A

### Proposed Solution

N/A

### Version and device info

N/A

### Additional context

N/A

### PR DESCRIPTION
**Pull request by joshxg**
Fixes #2333 

## Change summary

- Removed the item code column for a supplier credit modal opened from a particular item.
- Added the code into the title

## Testing

N/A

### Related areas to think about

N/A

### CODE REVIEW

File: src/selectors/supplierCredit.js [hunk 1]
```diff
@@ -38,6 +38,12 @@ export const selectItemName = ({ supplierCredit }) => {
   return name;
 };
 
+export const selectItemCode = ({ supplierCredit }) => {
+  const { item } = supplierCredit;
+  const { code } = item || {};
```
Comment (wlthomson) [inline src/selectors/supplierCredit.js]: `??`

Comment (joshxg) [reply src/selectors/supplierCredit.js]: 12gf87h
