### PR TITLE
#3011 temperature syncing and saving

### LINKED ISSUE #3011: New temperatures should be recorded from the last temperature synced
## Describe the bug

When syncing temperatures, the time set should be counted from the last temperature which was synced

### To reproduce

Internal code error here: 

https://github.com/openmsupply/mobile/blob/9f5deeaa04f9084958114525607c2850e3c61258/src/actions/TemperatureSyncActions.js#L108-L118

- Rather than counting back from 'now' find either the most recent `SensorLog` or `TemperatureLog` record (which ever is most recent).
- Then, calculate how many records should be read from the sensor from the time now, until that point and only save those records.

### Expected behaviour

As above

### Proposed Solution

As above

### Version and device info

- App version: Vaccine feature branch
- Tablet model: N/A
- OS version: N/A

### Additional context

Reasoning: If there is a crash between syncing temperatures and resetting the sensor, we might still have logs on a sensor. If we then sync again, we will save all the records.

i.e: 
- Sync 1000 logs, save them, crash before resetting (or fail to reset)
- Next sync, sync 1010 logs, save them. We're now well into the future!

If we change to the above behaviour:
- Sync 1000 logs, save them, crash before resetting (or fail to reset)
- Next sync, sync 1010 logs, save only ~10. Better!

Of course there is still the problem where the sensor itself has some undefined/incorrect behaviour - i.e.
- Sync 1000 logs, save them, crash before resetting (or fail to reset)
- Sensor doesn't keep recording temps
- Next sync, sync 1010 logs, save only ~10. But they're not the right times!

Not ideal but much better.

### PR DESCRIPTION
**Pull request by joshxg**
Fixes #3011 

## Change summary
- Adds corrected logic to 'count' from the most recent log synced, rather than counting back from the current time 

## Testing

N/A

### Related areas to think about

N/A

### CODE REVIEW

File: src/actions/PermissionActions.js [hunk 1]
```diff
@@ -23,7 +23,8 @@ const setWriteStorage = status => ({
 });
 
 const requestBluetooth = () => async dispatch => {
-  const result = await BluetoothStatus.enable();
+  BluetoothStatus.enable();
+  const result = await BluetoothStatus.state();
```
Comment (joshxg) [inline src/actions/PermissionActions.js:27]: bug fix

File: src/actions/TemperatureSyncActions.js [hunk 2]
```diff
@@ -119,13 +120,40 @@ const downloadLogsComplete = () => ({
 });
 
 const saveLogs = (logData, sensor) => async dispatch => {
+  const { length: numberOfLogs = 0 } = logData;
```
Comment (joshxg) [inline src/actions/TemperatureSyncActions.js:123]: hooopefully my comments help with this. Essentially:

- find the most recent log that has been saved. 
- work out how long it has been since then and now in terms of the number of log intervals of the sensor. 
- count back that many logs from the the overall logs downloaded from the sensor

We were: syncing the logs and counting back from the current time, then deleting the logs. But, if the delete fails - 💣 oops

File: src/actions/TemperatureSyncActions.js [hunk 3]
```diff
@@ -303,17 +332,12 @@ const syncTemperatures = () => async (dispatch, getState) => {
     const downloadedLogsResult = await dispatch(downloadLogs(sensor));
 
     if (downloadedLogsResult) {
+      await dispatch(saveLogs(downloadedLogsResult, sensor));
+      await dispatch(createTemperatureLogs(sensor));
```
Comment (joshxg) [inline src/actions/TemperatureSyncActions.js:336]: changing the order - just save before deleting now

File: src/selectors/fridge.js [hunk 4]
```diff
@@ -5,7 +5,7 @@
 import moment from 'moment';
 import { createSelector } from 'reselect';
 import { UIDatabase } from '../database';
-import chunk from '../utilities';
+import { chunk } from '../utilities';
```
Comment (joshxg) [inline src/selectors/fridge.js:8]: bug fix..

File: src/widgets/modals/DataTablePageModal.js [hunk 5]
```diff
@@ -227,7 +227,8 @@ const DataTablePageModalComponent = ({
         );
       case MODAL_KEYS.SELECT_LOCATION: {
         const { currentLocationName } = currentValue;
-        const { id, description } = currentValue.restrictedLocationType(UIDatabase) ?? {};
+        const { id = '', description = '' } =
+          currentValue?.restrictedLocationType?.(UIDatabase) ?? {};
```
Comment (joshxg) [inline src/widgets/modals/DataTablePageModal.js:231]: more bug fixes

File: src/actions/TemperatureSyncActions.js [hunk 6]
```diff
@@ -119,13 +120,40 @@ const downloadLogsComplete = () => ({
...
+  const { location, logInterval } = sensor;
+  const { id: locationID } = location;
+
+  // SensorLog are saved directly from a sensor as five-minute logs. A TemperatureLog is 30 minutes
+  // worth of SensorLog records. If there isn't enough SensorLogs to aggregate into a
+  // TemperatureLog, there may be some 'left over'. Start counting from whichever is sooner,
+  // the most recent SensorLog or the most recent TemperatureLog.
+  const sensorLogs = UIDatabase.objects('SensorLog').filtered('location.id == $0', locationID);
+  const tempLogs = UIDatabase.objects('TemperatureLog').filtered('location.id == $0', locationID);
+  const mostRecentSensorLogTime = moment(sensorLogs.max('timestamp') ?? timeNow);
```
Comment (joshxg) [inline src/actions/TemperatureSyncActions.js:136]: `max` returns undefined if there are no logs
