### PR TITLE
#4311 better json live validation

### LINKED ISSUE #4311: better validation for JSONForm
## Describe the bug

Live validation is on on the patient edit modal from the dispensary page which isn't great

### To reproduce

Steps to reproduce the behaviour:

### Proposed Solution

Leave if you don't know how to fix/implement. Edit this issue description and explain here if you know the best path of implementing the fix within the codebase.

### Version and device info

- App version:
- Tablet model:
- OS version:

### PR DESCRIPTION
**Pull request by joshxg**
Fixes #4311 

## Change summary

- Dunno if this is good- i just removed the live validation 🤷 

## Testing

- [ ] No crazy error message spam on `PatientEditModal`

### Related areas to think about

🤷

### CODE REVIEW

**Review by mark-prins — COMMENTED** [review]
Not sure about the target branch - just hoping that you merge them all in the right order

I'm still playing around - the validation is still sub-optimal; with the extra information, the validation error wasn't showing until I tried NEXT a few times, and then they don't clear so it is hard to see what is still needing to be filled in

**Comment by joshxg** [comment]
Ah you're right. Hm. Maybe we leave this out for now

**Comment by mark-prins** [comment]
for me, the dispensing > patient edit is still live validating even with this set to `false`
confused.
I actually like it like that - and would prefer changing the vaccination > patient edit version too. That one is line 105 in `PatientEdit` which is currently set to `false`

File: src/widgets/JSONForm/JSONForm.js [hunk 1]
```diff
@@ -207,6 +207,16 @@ export const JSONFormComponent = React.forwardRef(
       []
     );
 
+    const mounted = useIsMounted();
+    const [noValidate, setNoValidate] = React.useState(true);
+    const touchedFields = {};
+
+    React.useEffect(() => {
```
Comment (mark-prins) [inline src/widgets/JSONForm/JSONForm.js:214]: not strictly necessary now that touched status is being used - I thought good to reduce the number of times that validation is called so left it in

File: src/widgets/JSONForm/JSONForm.js [hunk 2]
```diff
@@ -207,6 +207,16 @@ export const JSONFormComponent = React.forwardRef(
       []
     );
 
+    const mounted = useIsMounted();
+    const [noValidate, setNoValidate] = React.useState(true);
+    const touchedFields = {};
```
Comment (mark-prins) [inline src/widgets/JSONForm/JSONForm.js:212]: using `State` caused the form to reload, losing entered values.. so went with a mutable object. Not ideal, but working.

File: src/widgets/JSONForm/JSONForm.js [hunk 3]
```diff
@@ -221,6 +231,10 @@ export const JSONFormComponent = React.forwardRef(
             debouncedOnChange(change, validator);
           }}
           formData={formData}
+          onBlur={id => {
```
Comment (mark-prins) [inline src/widgets/JSONForm/JSONForm.js:234]: second parameter is the value, not used in this case.

File: src/widgets/JSONForm/widgets/Checkboxes.js [hunk 4]
```diff
@@ -19,16 +19,23 @@ const selectValue = (value, selected, all) => {
...
-      const all = enumOptions.map(({ value }) => value);
-      onChange(selectValue(option.value, checkboxesValue, all));
-    } else {
-      onChange(deselectValue(option.value, checkboxesValue));
-    }
+    const all = enumOptions.map(({ value }) => value);
+    const newValue = checked
+      ? onChange(selectValue(option.value, checkboxesValue, all))
+      : onChange(deselectValue(option.value, checkboxesValue));
+    onBlur(id, newValue);
```
Comment (mark-prins) [inline src/widgets/JSONForm/widgets/Checkboxes.js:38]: in all of these widgets, not necessary to add the value to the onBlur - the method on the form is expecting it though, so I thought best to be complete just in case this is used later.

**Review by joshxg — COMMENTED** [review]
Works great!

File: src/widgets/JSONForm/widgets/Textarea.js [hunk 5]
```diff
@@ -28,6 +37,7 @@ export const Textarea = ({ autofocus, disabled, placeholder, value, onChange, nu
       autoFocus={autofocus}
       multiline={true}
       numberOfLines={numberOfLines}
+      onEndEditing={handleBlur}
```
Comment (mark-prins) [inline src/widgets/JSONForm/widgets/Textarea.js:40]: this method returns the value of the text input, the `onBlur` doesn't with multiline text inputs

File: src/widgets/JSONForm/JSONForm.js (hunk 2 above)
Comment (joshxg) [reply src/widgets/JSONForm/JSONForm.js:212]: Maybe better to `useRef` so that there isn't future hunchy funchy with `memo`ing - but I don't think it's needed right now

Comment (mark-prins) [reply src/widgets/JSONForm/JSONForm.js:212]: good point!
