### PR TITLE
#2099 Store insurance details

### LINKED ISSUE #2099: Store insurance discount amount and rate on a Transaction
## Describe the bug

Currently deriving a `Transaction` insurance discount amount and rate through the relation. Need to store the values for history

### To reproduce

Dispensing Development bug

### Expected behaviour

Dispensing Development bug

### Proposed Solution

Dispensing Development bug

### Version and device info

Dispensing Development bug

### Additional context

Dispensing Development bug

### PR DESCRIPTION
**Pull request by joshxg**
Fixes #2099 

## Change summary

- Correctly assigns insurance details to a finalise prescription. I've made #2104 to refactor this code to be less weird/horrible as the amount of parameters is very msupplyesque but it works so going with it for now
- Added insurance stuff to outgoing sync including the historic insurance details
- Fixed a couple of prop type and key warnings

Basically, this makes syncing prescriptions with insurance correct

I.e. I can now get this in desktop after syncing a prescription with a payment of $10, with 25% insurance 🎉 

image

## Testing

N/A

### Related areas to think about

N/A

### CODE REVIEW

File: src/utilities/modules/dispensary/pay.js [hunk 1]
```diff
@@ -80,5 +89,9 @@ export const pay = (currentUser, patient, script, cashAmount, scriptTotal) => {
   if (usingCredit && creditToAllocate > 0) throw new Error('Credit not fully allocated');
 
   // Ensure the script is finalised once paid.
+  script.subtotal = subtotal;
+  script.total = subtotal;
```
Comment (mark-prins) [inline src/utilities/modules/dispensary/pay.js]: just a question: should the total be the subtotal - discount amount?

Kind of related, there's now this: https://github.com/sussol/msupply/issues/5085

Comment (joshxg) [reply src/utilities/modules/dispensary/pay.js]: Yeah - at this point I have no idea what implementation to do. Same with https://github.com/sussol/msupply/issues/5086 :(
