### PR TITLE
#3022 Permission requesting

### LINKED ISSUE #3022: Request location permission when scanning for sensors
## Describe the bug

When trying to scan for sensors, request location permission

### To reproduce

1. Go to vaccines -> admin
2. Click on sensors
3. Click on scan for sensors (without location permission given)

### Expected behaviour

Should request the location permission

### Proposed Solution

As above

### Version and device info

- App version: Vaccine feature branch
- Tablet model:
- OS version:

### Additional context

N/A

### PR DESCRIPTION
**Pull request by joshxg**
Fixes #3022 

## Change summary

- adds a permission request when scanning for sensors

## Testing

N/A

### Related areas to think about

N/A

### CODE REVIEW

File: src/actions/TemperatureSyncActions.js [hunk 1]
```diff
@@ -81,17 +81,17 @@ const updateSensors = sensorAdvertisements => dispatch => {
...
+  if (!locationPermission) await dispatch(PermissionActions.requestLocation());
 
-  if (!bluetoothEnabled) dispatch(errorDisabledBluetooth());
-  if (!locationPermission) dispatch(errorDisabledLocation());
   if (!(bluetoothEnabled && locationPermission)) return null;
 
   await dispatch(scanForSensors());
 
-  return dispatch(PageActions.refreshData(ROUTES.VACCINE_ADMIN_PAGE));
+  return dispatch(PageActions.refreshData(ROUTES.VACCINES_ADMIN));
```
Comment (joshxg) [inline src/actions/TemperatureSyncActions.js:94]: offroad a little missused constant 🤣

File: src/pages/dataTableUtilities/getColumns.js [hunk 2]
```diff
@@ -45,7 +45,7 @@ const PAGE_COLUMN_WIDTHS = {
   [ROUTES.PRESCRIPTION]: [2, 4, 2, 2, 1],
   [ROUTES.PRESCRIPTIONS]: [1.5, 2.5, 2, 1.5, 3, 1],
   fridges: [1, 3, 1],
-  sensors: [3, 3, 1, 1, 1],
+  sensors: [3, 3, 1, 1],
```
Comment (joshxg) [inline src/pages/dataTableUtilities/getColumns.js:48]: also offroad - removed unused 'remove' column

File: src/actions/TemperatureSyncActions.js (hunk 1 above)
Comment (wlthomson) [reply src/actions/TemperatureSyncActions.js:94]: huh
