### PR TITLE
#1464 Add update to stocktake manager navigation to replace

### LINKED ISSUE #1463: StocktakeBatchModal editable when finalised
## Describe the bug

When a stocktake is finalised, the `StocktakeBatchModal` is still editable

### To reproduce

1. Go to `StocktakeEditPage`, create and finalise a stocktake with at least one line
2. Click on the `batch` icon to open the modal

### Expected behaviour

Should not be able to edit a finalised stocktake

### Version and device info

- App version: 3.0.0+
- Tablet model: all
- OS version: all

### Additional context

N/A

### LINKED ISSUE #1464: StocktakeEditPage not being poped off the stack when navigating
## Describe the bug

Navigating to the stocktake manage page does and back to the stocktake edit page, the original stocktake edit page is not popped off the stack

### To reproduce

1. Go to `StocktakeEditPage`
2. Click on `ManageStocktake`
3. Click ok
4. Click on `ManageStocktake`
5. Click ok 
6. Navigate back a few times
7. See error

### Expected behaviour

Shouldn't navigate from stocktake edit page -> stocktake edit page when navigating back

### Version and device info

- App version: 3.0.0

### Additional context

N/A

### PR DESCRIPTION
**Pull request by joshxg**
Fixes #1464

## Change summary

- Updates navigation to `StocktakeManagePage` such that when navigating from the `StocktakeEditPage`, `StocktakeEditPage` is replaced, so that stack stays valid

## Testing

- [ ] When navigating to and from `StocktakeManagePage`->`StocktakeEditPage`, multiple `StocktakeEditPage`s are not added to the navigation stack

### Related areas to think about

N/A

### CODE REVIEW

File: src/navigation/actions.js [hunk 1]
```diff
@@ -61,7 +71,9 @@ export const gotoStocktakeEditPage = stocktake => (dispatch, getState) => {
   // replace the current page as the user is coming from StocktakeManagePage.
   const navigationActionCreator =
     currentRouteName === 'stocktakes' ? NavigationActions.navigate : StackActions.replace;
-
+  console.log(navigationActionCreator({ routeName: '?' }));
+  console.log(Object.keys(nav));
+  nav.routes.forEach(route => console.log(route.routeName));
```
Comment (andreievg) [inline src/navigation/actions.js]: debug logs, pls delete

Comment (joshxg) [reply src/navigation/actions.js]: 1c2503ea2aba7e22910d6059fe3a0253dfa8dd2d
