### PR TITLE
#2221 Correct hasSelection field

### LINKED ISSUE #2221: Selecting/deselecting rows in pages has odd behaviour
## Describe the bug

After selecting and deselecting a few rows in a page i.e. `SupplierRequisitionsPage`, the confirm bottom modal dissapears

### To reproduce

See: https://github.com/openmsupply/mobile/issues/1239#issuecomment-583924060

### Expected behaviour

The modal shouldn't disapear if something is selected

### Proposed Solution

N/A

### Version and device info

- App version: 3.0.0+
- Tablet model: N/A
- OS version: N/A

### Additional context

N/A

### PR DESCRIPTION
**Pull request by joshxg**
Fixes #2221 

## Change summary

- Checks if there is any selection before unsetting `hasSelection`

## Testing

- [ ] With two rows selected, unselecting one of them does not make the bottom modal dissapear

### Related areas to think about

N/A

### CODE REVIEW

File: src/pages/dataTableUtilities/reducer/rowReducers.js [hunk 1]
```diff
@@ -33,10 +33,12 @@ export const deselectRow = (state, action) => {
   const rowState = newDataState.get(rowKey);
   newDataState.set(rowKey, { ...rowState, isSelected: false });
 
+  const hasSelection = Array.from(newDataState).some(([, { isSelected }]) => isSelected);
```
Comment (wlthomson) [inline src/pages/dataTableUtilities/reducer/rowReducers.js]: NIT: I think can be made a bit more readable by using `.values()` and spitting into two lines (untested):

```
const dataStateValues = Array.from(newDataState.values());
const hasSelected = dataStateValues.some(({ isSelected }) => isSelected);
```
```

Comment (joshxg) [reply src/pages/dataTableUtilities/reducer/rowReducers.js]: 87gf10z
