### PR TITLE
#2237 Number of Prescribers as a parameter to selectors

### LINKED ISSUE #2237: When you add your first prescriber, it does not appear in the list
## Describe the bug

When you add your first prescriber, it does not appear in the list immediately. I had to search for it (it didn't show in the search) and then deleted my search term and it appeared. 

I have no screenshots because I can't delete prescribers and reproduce, sorry! 

It seems to work fine after the first one is added, ie. when adding the 2nd prescriber. 

### To reproduce

1. On a datafile with no prescribers, select a patient and click 'Dispense'
2. On the window with an empty prescriber listbox, click 'New Prescriber'
3. Add a prescriber and return to the listbox window - it will still be empty

### Expected behaviour

I think it should appear in the listbox when added 

### Proposed Solution

Leave if you don't know how to fix/implement. Edit this issue description and explain here if you know the best path of implementing the fix within the codebase.

### Version and device info

- App version:4.0.0 RC4
- Tablet model:
- OS version:

### PR DESCRIPTION
**Pull request by joshxg**
Fixes #2237 

## Change summary

- Make the number of prescribers a parameter to the selector so that it recalculates if it changes

## Testing

- [ ] Adding a prescriber in the `PrescriberSelect` component refreshes the list of prescribers

### Related areas to think about

N/A

### CODE REVIEW

File: src/selectors/prescriber.js [hunk 1]
```diff
@@ -21,14 +21,22 @@ export const selectSearchTerm = ({ prescriber }) => {
   return searchTerm;
 };
 
-export const selectFilteredPrescribers = createSelector([selectSearchTerm], searchTerm => {
-  const [lastName, firstName] = searchTerm.split(',').map(name => name.trim());
+export const selectNumberOfPrescribers = () => {
+  const numberOfPrescribers = UIDatabase.objects('Prescriber').length;
+  return numberOfPrescribers;
```
Comment (wlthomson) [inline src/selectors/prescriber.js]: Can make this a one-liner?

Comment (joshxg) [reply src/selectors/prescriber.js]: 89fp90
