### PR TITLE
#2676 fix form control cancel callback

### LINKED ISSUE #2676: Form on cancel callback not being fired
## Describe the bug

The `onCancel` callback is not being fired on the `FormControl` component.

### To reproduce

1. Go to any `FormControl` component.
2. Click cancel.
3. See error.

### Expected behaviour

The `onCancel` callback should be fired when the cancel button is pressed.

### Proposed Solution

Minor fix to `mapDispatchToProps`.

### Version and device info

- App version: `feature/patient-api`
- Tablet model: Android emulator
- OS version: API 28.

### Additional context

N/A.

### PR DESCRIPTION
**Pull request by wlthomson**
Fixes #2676.

## Change summary

Fixes `formControl` `onCancel` callback.

## Testing

Steps to reproduce or otherwise test the changes of this PR:

- [ ] Form component cancel button fires `onCancel` callback.

### Related areas to think about

N/A.

### CODE REVIEW

File: src/widgets/FormControl.js [hunk 1]
```diff
@@ -230,7 +230,7 @@ const mapDispatchToProps = (dispatch, ownProps) => {
   const onUpdateForm = (key, value) => dispatch(FormActions.updateForm(key, value));
   const onCancel = () => {
     dispatch(FormActions.resetForm());
-    ownProps.showCancelButton && ownProps.onCancel();
+    ownProps.onCancel();
```
Comment (joshxg) [inline src/widgets/FormControl.js:233]: very odd to not see destructuring 🤣

Comment (wlthomson) [reply src/widgets/FormControl.js:233]: Yeah, just shadowing! Couldn't think of a good identifier 😆 .
