### PR TITLE
#2870 PropType updates

### LINKED ISSUE #2870: Vaccines prop type updates
## Describe the bug

There are a few prop type warnings on the `feature/vaccines` branch

### To reproduce

N/A

### Expected behaviour

No prop type warnings

### Proposed Solution

N/A

### Version and device info

N/A

### Additional context

N/A

### PR DESCRIPTION
**Pull request by joshxg**
Fixes #2870 

## Change summary

- Updates a couple of prop types which were throwing warnings

## Testing

N/A

### Related areas to think about

N/A

### CODE REVIEW

File: src/widgets/DataTable/TouchableNoFeedback.js [hunk 1]
```diff
@@ -24,10 +24,11 @@ const TouchableNoFeedback = ({ children, style, ...touchableProps }) => (
 
 TouchableNoFeedback.defaultProps = {
   style: null,
+  children: null,
 };
 
 TouchableNoFeedback.propTypes = {
-  children: PropTypes.oneOfType([PropTypes.arrayOf(PropTypes.node), PropTypes.node]).isRequired,
+  children: PropTypes.oneOfType([PropTypes.arrayOf(PropTypes.node), PropTypes.node]),
```
Comment (joshxg) [inline src/widgets/DataTable/TouchableNoFeedback.js:31]: Just getting a warning if null is passed as a child. This is pretty inconsequential

File: src/widgets/RowDetail.js [hunk 2]
```diff
@@ -114,7 +114,7 @@ RowDetailComponent.defaultProps = {
   dismissOnKeyboardOpen: true,
   modalStyle: localStyles.modal,
   headerRowStyle: localStyles.headerRow,
-  containerStyle: localStyles.containerStyle,
+  containerStyle: localStyles.container,
```
Comment (joshxg) [inline src/widgets/RowDetail.js:117]: wrong variable naming

File: src/widgets/modalChildren/TemperatureSync.js [hunk 3]
```diff
@@ -76,13 +76,17 @@ const mapDispatchToProps = dispatch => ({
...
+};
+
 TemperatureSyncComponent.propTypes = {
   total: PropTypes.number.isRequired,
   progress: PropTypes.number.isRequired,
   lastTemperatureSync: PropTypes.string.isRequired,
   temperatureSyncMessage: PropTypes.string.isRequired,
   isSyncing: PropTypes.bool.isRequired,
-  currentSensor: PropTypes.string.isRequired,
+  currentSensor: PropTypes.string,
```
Comment (joshxg) [inline src/widgets/modalChildren/TemperatureSync.js:89]: before the syncing process starts, there is no 'currentSensor'

File: src/widgets/modals/ModalContainer.js [hunk 4]
```diff
@@ -118,14 +118,15 @@ ModalContainer.defaultProps = {
...
+  children: null,
 };
 
 ModalContainer.propTypes = {
   fullScreen: PropTypes.bool,
   isVisible: PropTypes.bool.isRequired,
   onClose: PropTypes.func,
   title: PropTypes.string,
-  children: PropTypes.oneOfType([PropTypes.arrayOf(PropTypes.node), PropTypes.node]).isRequired,
+  children: PropTypes.oneOfType([PropTypes.arrayOf(PropTypes.node), PropTypes.node]),
```
Comment (joshxg) [inline src/widgets/modals/ModalContainer.js:129]: similar to the above - null is apparently not a node - thought it was? 🤷
