### PR TITLE
#1034 Consolidating vaccine module

### LINKED ISSUE #984: Display more detail on syncing temperatures
Build Number:

v2.2.0 rc-0

Description:

Currently when syncing temperatures from sensors, there is no feedback to the user. This could be improved:

- Progress bar
    - searching for devices
    - syncing temperatures
    - aggregating data
    - resetting sensors
- Text feedback for the above steps to the user.
- Should also disable the regular manual sync button during syncing temperatures and vice versa

Reproducible:

Yes

Reproduction Steps:

Manually try to sync temperatures

Comments:

This will require changes to the current blue tooth module. This should maybe be a new issue.

- Consistent return values

Suggest:

```
{
    success: false,
    error: {
        code,
        message,
        extra,
    }
}

{
    success: true,
    data: {
    }
}
```

### LINKED ISSUE #995: Tidy up of vaccine and sensor helper methods
Build Number: 2.2.0 rc0

Description:

In `utilities/modules/` are two files `vaccines.js` and `temperatureSensorHelpers.js` which have gotten pretty big and out of control. Needs a bit of a tidy up.

Reproducible: N/A

Reproduction Steps: N/A

Comments:

- Need to be careful to no cause any regressions
- In particular comments/commenting
- Fixing code to be able to commit changes without using `--no-verify` (respecting linter rules)
- constants consolidated
- potentially more files to separate this a bit more

### LINKED ISSUE #1034: Vaccine module merge
## Describe
Many changes were made for the vaccine module feature branch, in a branch from that (originally from 2.2.0), including sensor log aggregation logic and bluetooth sensor syncing

### Version and device info
 - App version: 2.2.0

### Additional context
The PR for this issue is into `vaccine-development`, which was originally branched from `2.2`. After this is merged, `vaccine-development` will need to be updated from `develop`, and then  merged into that.

### LINKED ISSUE #1049: bleDeviceScanner invalid arguments
## Error in mSupply Mobile

**java.lang.IllegalArgumentException** in **MainActivity**
invalid device address sen1MacAddress

[View on Bugsnag](https://app.bugsnag.com/sustainable-solutions-nz-ltd/msupply-mobile/errors/5d1e7dd0218ca300191e9993?event_id=5d1e7dd0004884571f2d0000&i=gh&m=ci)

## Stacktrace

    bleDeviceScanner.java:75 - com.msupplymobile.bleDeviceScanner.startScanning
    bleTempoDisc.java:27 - com.msupplymobile.bleTempoDisc.getDevices

[View full stacktrace](https://app.bugsnag.com/sustainable-solutions-nz-ltd/msupply-mobile/errors/5d1e7dd0218ca300191e9993?event_id=5d1e7dd0004884571f2d0000&i=gh&m=ci)

*Created automatically via Bugsnag*

### PR DESCRIPTION
**Pull request by joshxg**
Fixes #1034 Fixes #995 Fixes #984 Fixes #1049 

## Change summary

- Made some adjustments to the bluetooth native module with the goal of being able to easily extend it in the future if we have different types of sensors, to have no state being saved (as it's discouraged since it is a singleton and can cause problems).
- Tidied up all helper methods, with having the files `utilities.js`, `aggregation.js` and `chartHelpers.js`. Bluetooth methods have gone into `Sensor.js` and synchronisation has gone into `sensorSynchroniser.js`, to be transferred into redux once into develop.
- Removed quite a few methods as parsing is done in the native-module
- Added a button to have a sensor blink it's LED.

Still need to handle permission checking, adding syncing into redux once in develop. Also using `locationType` for fetching breach data.

## Testing
Testing will be directed toward a main vaccine-development PR into develop

### Related areas to think about
- GATT status error 133 - bit of a problem I think!
- ScanFilter/ScanSettings - On my phone using these makes the bluetooth adapter not pick up any devices, removing them it works fine. However it connects to a device instantly with a GATT connection. On the Lenovo tablet, using ScanSettings/ScanFilter works fine, but get a lot of GATT 133 errors..
- VaccineModulePage I think could be cleaned up a bit more adding a ScrollView
- Localization still needs to be done
- Could change the breach chart helpers to account for there being `breachAggregates` and linked item batches

### CODE REVIEW

File: android/app/src/main/java/com/msupplymobile/Ble/BlueMaestroDevice.java [hunk 1]
```diff
@@ -0,0 +1,200 @@
...
+            byte response[] = characteristic.getValue();
+            ByteArrayOutputStream output = new ByteArrayOutputStream();
+            try{
+                output.write(commandResult);
+                output.write(response);
+            } catch(Exception exception){
+                notifyListener(new MsupplyException(ErrorCode.E_DOWNLOADING_LOGS, exception));
+                
+            }
+            commandResult = output.toByteArray();
```
Comment (andreievg) [inline android/app/src/main/java/com/msupplymobile/Ble/BlueMaestroDevice.java]: i see you are flattening a 2 d array response here, I don't really see anything wrong with that apart from, is there a chance that LOGS_HEADER_OFFSET is not always 15 ? Is this how the blue maestro pps do it ?

File: src/database/DataTypes/Sensor.js [hunk 2]
```diff
@@ -5,9 +5,199 @@
...
-  // Does this need to be a class ??
+  /**
+   * Scans for all devices matching the passed manufacturer ID,
+   * returning their advertisement data. Updates or creates
+   * any found sensors.
+   */
+  static async scanForSensors(database) {
+    try {
+      const { BleManager } = NativeModules;
+      const result = await BleManager.getDevices(MANUFACTURER_ID, '');
```
Comment (andreievg) [inline src/database/DataTypes/Sensor.js]: perhaps it's better to have an overloaded method in native (with, omitting mac address)

File: src/database/DataTypes/Sensor.js [hunk 3]
```diff
@@ -5,9 +5,199 @@
 
 import Realm from 'realm';
 
+import { NativeModules } from 'react-native';
+import { generateUUID } from 'react-native-database';
+
+const MANUFACTURER_ID = 307;
```
Comment (andreievg) [inline src/database/DataTypes/Sensor.js]: I like what you've done with future proofing (incase we need to change sensor). This is just a thought (not going there for atm), you were probably thinking about this too -> manufacturer id into schema

File: src/database/DataTypes/Sensor.js [hunk 4]
```diff
@@ -5,9 +5,199 @@
...
+      return { success: false, error };
+    }
+  }
+
+  /**
+   * Connects with the native bluetooth adapter to scan for this sensor
+   * and retrieve the advertisement data, updating this sensor.
+   * Return object: See BleParser.java
+   */
+  async scanAndUpdate({ manufacturerId, database }) {
```
Comment (andreievg) [inline src/database/DataTypes/Sensor.js]: i don't beleive this method will be used, nice to have I guess

File: src/database/DataTypes/Sensor.js [hunk 5]
```diff
@@ -5,9 +5,199 @@
...
+    const { BleManager } = NativeModules;
+    try {
+      const result = await BleManager.getDevices(manufacturerId, this.macAddress);
+      const { success, data } = result;
+      if (!success) return result;
+      if (!data || data.length === 0) return result;
```
Comment (andreievg) [inline src/database/DataTypes/Sensor.js]: interesting, checking data here but not in scanForSensors (any reason ?)

File: src/mSupplyMobileApp.js [hunk 6]
```diff
@@ -68,23 +68,35 @@ class MSupplyMobileAppContainer extends React.Component {
     this.scheduler = new Scheduler();
     const isInitialised = this.synchroniser.isInitialised();
     this.scheduler.schedule(this.synchronise, SYNC_INTERVAL);
+    // this.scheduler.schedule(this.synchroniseSensor, SYNC_INTERVAL);
```
Comment (andreievg) [inline src/mSupplyMobileApp.js]: can you TODO this please

File: src/mSupplyMobileApp.js [hunk 7]
```diff
@@ -68,23 +68,35 @@ class MSupplyMobileAppContainer extends React.Component {
...
+        lastSync: latestTemperatureSync,
+        isSyncing: false,
+        progress: 1,
+        total: 1,
+      },
     };
   }
 
-  componentDidMount = () => BackHandler.addEventListener('hardwareBackPress', this.handleBackEvent);
+  componentDidMount = async () => {
```
Comment (andreievg) [inline src/mSupplyMobileApp.js]: ooh, is this new ? why async ?

File: src/mSupplyMobileApp.js [hunk 8]
```diff
@@ -122,24 +134,41 @@ class MSupplyMobileAppContainer extends React.Component {
...
     this.setState({ isLoading: false });
     this.database.isLoading = false;
   };
 
+  updateMessageSyncState = ({ message, lastSync, total = 100, progress = 100 }) => {
+    // eslint-disable-next-line react/destructuring-assignment, prefer-destructuring
+    if (!lastSync) lastSync = this.state.temperatureSyncState.lastSync;
+    this.setState({
+      temperatureSyncState: {
+        ...this.state.temperatureSyncState, // eslint-disable-line react/no-access-state-in-setstate, react/destructuring-assignment, max-len
```
Comment (andreievg) [inline src/mSupplyMobileApp.js]: what is in ...temperatureSyncState that's not being set here btw ?

File: src/mSupplyMobileApp.js [hunk 9]
```diff
@@ -122,24 +134,41 @@ class MSupplyMobileAppContainer extends React.Component {
...
-    functionToRun();
+    if (isAsync) await functionToRun();
+    else functionToRun();
     this.setState({ isLoading: false });
     this.database.isLoading = false;
   };
 
+  updateMessageSyncState = ({ message, lastSync, total = 100, progress = 100 }) => {
+    // eslint-disable-next-line react/destructuring-assignment, prefer-destructuring
+    if (!lastSync) lastSync = this.state.temperatureSyncState.lastSync;
```
Comment (andreievg) [inline src/mSupplyMobileApp.js]: can you add TODO (redux)

File: src/mSupplyMobileApp.js [hunk 10]
```diff
@@ -216,8 +245,12 @@ class MSupplyMobileAppContainer extends React.Component {
       isInitialised,
       isLoading,
       syncModalIsOpen,
+      temperatureSyncState,
     } = this.state;
-
+    const sensorSynchroniser = synchroniseSensors.bind(this, {
```
Comment (andreievg) [inline src/mSupplyMobileApp.js]: this should be bound in constructor pls.

Can also make a const method in mSupplyMobileApp class:

```
const sensorSynchorniser = () = > synchroniseSensor({database: this.databse ....
```

File: src/pages/ManageVaccineStockPage.js [hunk 11]
```diff
@@ -55,33 +55,33 @@ const TABLE_COLUMNS = {
...
     title: LOCALIZATION.headers.totalQuantity,
-    alignText: 'right',
+    alignText: 'center',
   },
   hasBreach: {
     key: 'hasBreach',
     width: 0.5,
     title: LOCALIZATION.headers.hasBreach,
-    alignText: 'left',
+    alignText: 'lecenterft',
```
Comment (andreievg) [inline src/pages/ManageVaccineStockPage.js]: is that some sort of yoga alignment hehe

File: src/pages/ManageVaccineStockPage.js [hunk 12]
```diff
@@ -196,12 +196,10 @@ export class ManageVaccineStockPage extends React.Component {
   // be available.
   componentDidMount = () => {
     const { database, initialLocation } = this.props;
-    const fridges = database.objects('Location').filter(location => location.isFridge);
-    fridges.unshift({ description: LOCALIZATION.misc.allLocations });
+    const fridges = database.objects('Fridge');
+    fridges.slice().unshift({ description: LOCALIZATION.misc.allLocations });
```
Comment (andreievg) [inline src/pages/ManageVaccineStockPage.js]: this.LOCATION_FILTERS = fridges.slice().uns...

Also suggest adding 'no fridges filter' quite useful to know which items are not assigned to fridge

File: src/pages/ManageVaccineStockPage.js [hunk 13]
```diff
@@ -196,12 +196,10 @@ export class ManageVaccineStockPage extends React.Component {
...
     this.LOCATION_FILTERS = fridges;
-    this.ITEMS = database
-      .objects('Item')
-      .filtered('category.name BEGINSWITH[c] $0 && category.name ENDSWITH[c] $0 ', 'vaccine');
+    this.ITEMS = database.objects('Item').filtered('category.name CONTAINS[c] $0 ', 'vaccine');
```
Comment (andreievg) [inline src/pages/ManageVaccineStockPage.js]: should we add VaccineItem as an object (i.e. like Fridge) ?

File: src/pages/MenuPage.js [hunk 14]
```diff
@@ -26,22 +26,22 @@ const SECTIONS = {
...
+      { title: 'supplier_invoices', page: 'supplierInvoices' },
+      { title: 'supplier_requisitions', page: 'supplierRequisitions' },
     ],
   },
   stock: {
     icon: require('../images/menu_pc_clipboard.png'),
     buttons: [
-      { title: navStrings.current_stock, page: 'stock' },
-      { title: navStrings.stocktakes, page: 'stocktakes' },
+      { title: 'current_stock', page: 'stock' },
```
Comment (andreievg) [inline src/pages/MenuPage.js]: i know this i of my doing, but if we make this a method (like you've done for IC customisation, can revert back to navStrings and don't need to do the `navStrings[title]` shenanigans in renderButton ) and

File: src/pages/VaccineModuleAdminPage.js [hunk 15]
```diff
@@ -0,0 +1,214 @@
...
+      database.update('Sensor', { id, location });
+    });
+    this.setState({ currentFridge: null, isModalOpen: false }, this.refresh);
+  };
+
+  renderSelectSensorModal = () => {
+    const { database } = this.props;
+    const { sensors, currentFridge } = this.state;
+    const fridgeSensor = currentFridge.getSensor(database);
+    const highlightValue = fridgeSensor || (fridgeSensor && fridgeSensor.toString());
```
Comment (andreievg) [inline src/pages/VaccineModuleAdminPage.js]: const highlightValue = fridgeSensor && fridgeSensor.toString;

File: src/utilities/modules/vaccines/aggregation.js [hunk 16]
```diff
@@ -0,0 +1,212 @@
...
+      if (temperature > sensorLog.temperature) temperature = logTemperature;
+    } else {
+      // If the currentlogs timestamp is greater than the end timestamp of the current
+      // aggregation, increment the timestamps for the next aggregation.
+      while (logTimestamp >= new Date(endTimestamp)) {
+        firstTimestamp = endTimestamp;
+        endTimestamp = new Date(endTimestamp.getTime() + PREAGGREGATE_INTERVAL);
+      }
+      logsToDelete = [...logsToDelete, ...logsToDeleteTemp];
+      logsToDeleteTemp = [{ ...sensorLog }];
```
Comment (andreievg) [inline src/utilities/modules/vaccines/aggregation.js]: why not [sensorLog] ?

File: src/utilities/modules/vaccines/aggregation.js [hunk 17]
```diff
@@ -0,0 +1,212 @@
...
+  let logsToDeleteTemp = [];
+  let temperature = Infinity;
+  sortedLogs.forEach(sensorLog => {
+    const { timestamp: logTimestamp, temperature: logTemperature } = sensorLog;
+    // If this sensorlog does exceed the aggregates end timestamp, check if it has
+    // the minimum temperature and push it onto the potential delete stack, to be
+    // deleted if it is included in an aggregation.
+    if (logTimestamp <= endTimestamp) {
+      logsToDeleteTemp.push({ ...sensorLog });
+      if (temperature > sensorLog.temperature) temperature = logTemperature;
```
Comment (andreievg) [inline src/utilities/modules/vaccines/aggregation.js]: sensorLog.temperature = logTemperature

File: src/utilities/modules/vaccines/aggregation.js [hunk 18]
```diff
@@ -0,0 +1,212 @@
...
+  let endTimestamp = new Date(firstTimestamp.getTime() + PREAGGREGATE_INTERVAL);
+  let logsToDeleteTemp = [];
+  let temperature = Infinity;
+  sortedLogs.forEach(sensorLog => {
+    const { timestamp: logTimestamp, temperature: logTemperature } = sensorLog;
+    // If this sensorlog does exceed the aggregates end timestamp, check if it has
+    // the minimum temperature and push it onto the potential delete stack, to be
+    // deleted if it is included in an aggregation.
+    if (logTimestamp <= endTimestamp) {
+      logsToDeleteTemp.push({ ...sensorLog });
```
Comment (andreievg) [inline src/utilities/modules/vaccines/aggregation.js]: was wondering why not just push([sensorLog])

File: src/utilities/modules/vaccines/aggregation.js [hunk 19]
```diff
@@ -0,0 +1,212 @@
...
+const FIVE_MINUTES_MILLISECONDS = ONE_MINUTE_MILLISECONDS * 5;
+const EIGHT_HOURS_MILLISECONDS = ONE_HOUR_MILLISECONDS * 8;
+
+const NO_FULL_AGGREGATE_PERIOD = EIGHT_HOURS_MILLISECONDS * 4 + FIVE_MINUTES_MILLISECONDS;
+const FULL_AGGREGATION_INTERVAL = EIGHT_HOURS_MILLISECONDS + FIVE_MINUTES_MILLISECONDS;
+const PREAGGREGATE_INTERVAL = 20 * ONE_MINUTE_MILLISECONDS;
+/**
+ * Aggregates sensor logs that have been pulled from a physical sensor.
+ */
+export function preAggregateLogs({ sensor, database }) {
```
Comment (andreievg) [inline src/utilities/modules/vaccines/aggregation.js]: we'll have to remember that aggregation should be based on location, i..e sensor independent (maybe add a todo here, or i'll try to remember to add an issue)

File: src/utilities/modules/vaccines/aggregation.js [hunk 20]
```diff
@@ -0,0 +1,212 @@
...
+  database.write(() => {
+    logsToAdd.forEach(sensorLog => {
+      const newSensorLog = database.update('SensorLog', sensorLog);
+      sensor.sensorLogs.push(newSensorLog);
+    });
+  });
+
+  database.write(() => {
+    // **TODO: Change to use IN when realm is upgraded
+    logsToDelete.forEach(sensorLog => {
```
Comment (andreievg) [inline src/utilities/modules/vaccines/aggregation.js]: i think if you didn't destructure {...sensorLog} previously you wouldn't' need to search for the object

File: src/utilities/modules/vaccines/aggregation.js [hunk 21]
```diff
@@ -0,0 +1,212 @@
...
+      database.delete('SensorLog', database.objects('SensorLog').filtered('id = $0', sensorLog.id));
+    });
+  });
+
+  return { success: true };
```
Comment (andreievg) [inline src/utilities/modules/vaccines/aggregation.js]: should we keep the data in the return as per before ?

File: android/app/src/main/java/com/msupplymobile/Ble/BleManager.java [hunk 22]
```diff
@@ -0,0 +1,192 @@
...
+        // If there is a command, mac address and devices have been scanned, 
+        // a command needs to be executed.
+        boolean shouldSendCommand = this.command != null && this.macAddress != null && this.devices != null;
+        if (shouldSendCommand){
+            try{
+                BleDevice device = (BleDevice)this.devices.get(this.macAddress);
+                if (Debug.LOG) Log.i(Debug.TAG, "BleManager: in should send");
+                String commandSub = this.command;
+                this.command = this.macAddress = null;
+                device.register(this);
```
[the remark this answers is not in the document]
Comment (joshxg) [reply android/app/src/main/java/com/msupplymobile/Ble/BleManager.java]: ffb088a18b39311830f5c723e0388708e9c372c2

File: android/app/src/main/java/com/msupplymobile/Ble/BleManager.java [hunk 23]
```diff
@@ -0,0 +1,192 @@
...
+     * MsupplyExcpetion can be represented as a WritableMap to send
+     * to JS.
+     */
+    @Override
+    public void BleCallback(MsupplyException exception){
+        if (Debug.LOG) Log.i(Debug.TAG, "BleManager: Exception callback");
+        this.returnException(exception);
+    }
+
+    /** Callback for scanning operations */
```
[the remark this answers is not in the document]
Comment (joshxg) [reply android/app/src/main/java/com/msupplymobile/Ble/BleManager.java]: 99ad45120c3ddd61c41c6113fe0df627f44ab210

File: android/app/src/main/java/com/msupplymobile/Ble/BleManager.java [hunk 24]
```diff
@@ -0,0 +1,192 @@
...
+        if (Debug.LOG) Log.i(Debug.TAG, "getDevices:" + Integer.toString(manufacturerID) + " " + macAddress);
+        this.promise = promise;
+        BleDeviceScanner deviceScanner = new BleDeviceScanner(reactContext);
+        deviceScanner.registerListener(this);
+        deviceScanner.setFilters(manufacturerID, macAddress);
+        // Full coverage fallback catcher for any uncaught errors occuring.
+        try{
+            deviceScanner.startScan();
+        }catch(Throwable e){
+            promise.reject("error", e.toString());
```
[the remark this answers is not in the document]
Comment (joshxg) [reply android/app/src/main/java/com/msupplymobile/Ble/BleManager.java]: So the plan was that any explicit exceptions would be caught and resolved, whereas real errors being caught (unexpected/uncaught) would be rejected

File: android/app/src/main/java/com/msupplymobile/Ble/BleManager.java [hunk 25]
```diff
@@ -0,0 +1,192 @@
...
+     *     error: {
+     *         code,
+     *         message,
+     *         extra [stack trace],
+     *     }
+     * }
+     */
+    private void returnException(MsupplyException exception){
+        if (Debug.LOG) Log.i(Debug.TAG, "BleManager: Returning Exception");
+        WritableMap jsObject = Arguments.createMap();
```
[the remark this answers is not in the document]
Comment (joshxg) [reply android/app/src/main/java/com/msupplymobile/Ble/BleManager.java]: 82ccc5513d8bd2c1a7f8dda6f44eed748eb7c43f

File: android/app/src/main/java/com/msupplymobile/Ble/BleParser.java [hunk 26]
```diff
@@ -0,0 +1,38 @@
+package com.msupplymobile;
+import com.facebook.react.bridge.WritableMap;
+import com.facebook.react.bridge.WritableArray;
+
+public abstract class BleParser{
+ 
+    public static final String BATTERY_LEVEL = "batteryLevel";
```
[the remark this answers is not in the document]
Comment (joshxg) [reply android/app/src/main/java/com/msupplymobile/Ble/BleParser.java]: My thought was that any return object should be consistent - i.e. battery levels for any sensor would return as `batteryLevel` etc. But maybe not all sensors would have these exact properties, so I used constants to be used

File: android/app/src/main/java/com/msupplymobile/Ble/BleManager.java [hunk 27]
```diff
@@ -0,0 +1,192 @@
...
+     * Callback for handling commands sent to devices,
+     * whether it was succcesful, or not.
+     */
+    @Override
+    public void BleCallback(boolean result){
+        if (Debug.LOG) Log.i(Debug.TAG, "BleManager: Device callback");
+        if (result){
+            this.handleEvent();    
+        } else{
+            this.returnException(new MsupplyException(ErrorCode.E_COMMAND_FAILED));
```
[the remark this answers is not in the document]
Comment (joshxg) [reply android/app/src/main/java/com/msupplymobile/Ble/BleManager.java]: It would be from a command being executed on a previously found device, so I went with that

File: android/app/src/main/java/com/msupplymobile/Ble/BleDeviceScanner.java [hunk 28]
```diff
@@ -0,0 +1,228 @@
...
+                notifyListeners(new MsupplyException(ErrorCode.E_INVALID_ADDRESS));
+                return;
+            }
+        }
+
+        scanFilters = Arrays.asList(new ScanFilter[]{ scanFilterBuilder.build() });
+        scanSettings = scanSettingsBuilder.build();
+        
+        
+        Intent enableBtIntent = new Intent(BluetoothAdapter.ACTION_REQUEST_ENABLE);
```
[the remark this answers is not in the document]
Comment (joshxg) [reply android/app/src/main/java/com/msupplymobile/Ble/BleDeviceScanner.java]: They're not prompted again, just flows through

File: android/app/src/main/java/com/msupplymobile/Ble/BleDeviceScanner.java [hunk 29]
```diff
@@ -0,0 +1,228 @@
...
+            return false;
+        }
+    }
+
+    /**
+     * Start the scan by setting the scan settings and filters. Starts an
+     * acitivity requesting BlueTooth is enabled, if it is, or if the
+     * users enables it, start the scan through that activity.
+     */
+    public void startScan(){
```
[the remark this answers is not in the document]
Comment (joshxg) [reply android/app/src/main/java/com/msupplymobile/Ble/BleDeviceScanner.java]: 4334a0f9c43b5f8ab053c7a21d701624501499ad

File: android/app/src/main/java/com/msupplymobile/Ble/BleDeviceScanner.java [hunk 30]
```diff
@@ -0,0 +1,228 @@
...
+    private int manufacturerID;
+    private boolean isScanEnabled;
+    private String deviceAddress;
+    private Map<String, Object> scannedDevices;
+    private ReactContext reactContext;
+    private BluetoothLeScanner leScanner;
+    BluetoothAdapter btAdapter;
+    private ScanSettings scanSettings;
+    private List<ScanFilter> scanFilters;
+    private List<BleScanListener> listeners;
```
[the remark this answers is not in the document]
Comment (joshxg) [reply android/app/src/main/java/com/msupplymobile/Ble/BleDeviceScanner.java]: Doesn't need to be.. my thought was that it costs very little to set it up for multiple listeners, but going the other way edits old code which is worse.. but I guess I wasn't really consistent!

File: android/app/src/main/java/com/msupplymobile/Ble/BleManager.java [hunk 31]
```diff
@@ -0,0 +1,192 @@
...
+    /**
+     * Find the provided device and send the provided command.
+     */
+    @ReactMethod
+    public void sendCommand(int manufacturerID, String macAddress, String command, Promise promise) {
+        if (Debug.LOG) Log.i(Debug.TAG, "sendCommand" + Integer.toString(manufacturerID) + " " + macAddress + " " + command);
+        this.promise = promise;
+        this.command = command;
+        this.macAddress = macAddress;
+        getDevices(manufacturerID, macAddress, promise);
```
[the remark this answers is not in the document]
Comment (joshxg) [reply android/app/src/main/java/com/msupplymobile/Ble/BleManager.java]: 20a99ca1c79ec1459a804d7e29fb89ec86f3275c

This was the main reason for the change. As react-native native classes are singletons I thought it was best it didn't keep old state as it can lead to pretty hard to find bugs in the future

File: android/app/src/main/java/com/msupplymobile/Ble/BlueMaestroDevice.java (hunk 1 above)
Comment (joshxg) [reply android/app/src/main/java/com/msupplymobile/Ble/BlueMaestroDevice.java]: It's not how they do it, but I tried to do pretty extensive testing. I think if we can't rely on *some* form of consistency it's pretty hard to decode anything

File: src/database/DataTypes/Item.js [hunk 32]
```diff
@@ -303,7 +303,8 @@ export class Item extends Realm.Object {
   getAllSensorLogs(database) {
     return database
       .objects('SensorLog')
-      .filtered('itemBatches.item.id = $0 && itemBatches.numberOfPacks > 0', this.id);
+      .filtered('itemBatches.item.id = $0', this.id)
+      .filtered('itemBatches.numberOfPacks > 0 && NOT itemBatches.numberOfPacks == 0');
```
[the remark this answers is not in the document]
Comment (joshxg) [reply src/database/DataTypes/Item.js]: db616ca6340a595e3deae8d09a8f343649c3eaf0

File: src/database/DataTypes/Sensor.js [hunk 33]
```diff
@@ -5,9 +5,199 @@
...
+import { generateUUID } from 'react-native-database';
+
+const MANUFACTURER_ID = 307;
+
+const getCommand = (manufacturerID, command, param) => {
+  const commands = {
+    307: {
+      BLINK: '*blink',
+      RESET_ADV_FREQ: '*sadv1000',
+      RESET_LOG_FREQ: `*lint${param}`,
```
[the remark this answers is not in the document]
Comment (joshxg) [reply src/database/DataTypes/Sensor.js]: 7d8fab3805b40aa7c5e542f9e05b9e468de27104

File: src/database/DataTypes/Sensor.js (hunk 3 above)
Comment (joshxg) [reply src/database/DataTypes/Sensor.js]: 100%

File: src/database/DataTypes/Sensor.js (hunk 5 above)
Comment (joshxg) [reply src/database/DataTypes/Sensor.js]: just because of the operations on the other method and this one not so

File: src/mSupplyMobileApp.js (hunk 6 above)
Comment (joshxg) [reply src/mSupplyMobileApp.js]: I'd rather make a list of issues rather than chuck TODO's all through if that's all good? I find TODO's all the time, they seem to just get chucked in and forgot about

File: src/mSupplyMobileApp.js (hunk 7 above)
Comment (joshxg) [reply src/mSupplyMobileApp.js]: just an accident from devving from that method hehe

File: src/mSupplyMobileApp.js (hunk 8 above)
Comment (joshxg) [reply src/mSupplyMobileApp.js]: hmm tbh I just copy pasted that I didn't really look at it heh

File: src/mSupplyMobileApp.js (hunk 10 above)
Comment (joshxg) [reply src/mSupplyMobileApp.js]: f8fbb2bfe3b38313c85b6bdba8af111c9c196357

File: src/pages/ManageVaccineStockPage.js (hunk 11 above)
Comment (joshxg) [reply src/pages/ManageVaccineStockPage.js]: 78f258f5b45abe12a5526d2aa9e1c3f17daa428b

File: src/pages/ManageVaccineStockPage.js (hunk 13 above)
Comment (joshxg) [reply src/pages/ManageVaccineStockPage.js]: 18bdf39e201e70828c47827044e83428f092bedd

File: src/pages/ManageVaccineStockPage.js (hunk 12 above)
Comment (joshxg) [reply src/pages/ManageVaccineStockPage.js]: c32bcad2ada67ca870dbcd363f8865f35b718db0

7c6be3ae39256e7e65e2738bc90c5cfbec5bcca9

File: src/pages/MenuPage.js (hunk 14 above)
Comment (joshxg) [reply src/pages/MenuPage.js]: d94ade22813c4579ce9acbc7f1245228bc612005

File: src/pages/SupplierRequisitionPage.js [hunk 34]
```diff
@@ -46,9 +47,14 @@ export class SupplierRequisitionPage extends React.Component {
       searchTerm: '',
       sortBy: 'itemName',
       isAscending: true,
+      isVaccine: false,
```
[the remark this answers is not in the document]
Comment (joshxg) [reply src/pages/SupplierRequisitionPage.js]: 62a42abb7109615b1e0cc3a9f0912cff3c4484dd

File: src/pages/SupplierRequisitionPage.js [hunk 35]
```diff
@@ -357,6 +372,84 @@ export class SupplierRequisitionPage extends React.Component {
...
+    // Get date of most recent requisition.
+
+    const prevRequisitions = database
+      .objects('Requisition')
+      .filtered('id != $0 && items.item.id = $1', requisition.id, requisitionItem.item.id)
+      .sorted('entryDate');
+
+    const isPrevRequisition = prevRequisitions.length > 0;
+
+    const prevRequisitionDate = isPrevRequisition ? prevRequisitions[0].entryDate : null;
```
[the remark this answers is not in the document]
Comment (joshxg) [reply src/pages/SupplierRequisitionPage.js]: bf494c8bd4d9008cb3edca4ad220ed490f4ae74c

File: src/pages/SupplierRequisitionPage.js [hunk 36]
```diff
@@ -357,6 +372,84 @@ export class SupplierRequisitionPage extends React.Component {
...
+
+    // Get transactions for this item since most recent requisition.
+
+    const transactionBatches = database
+      .objects('TransactionBatch')
+      .filtered('itemId = $0', requisitionItem.item.id);
+
+    const recentTransactionBatches = prevRequisitionDate
+      ? transactionBatches.filtered('transaction.confirmDate >= $0', prevRequisitionDate)
+      : transactionBatches;
```
[the remark this answers is not in the document]
Comment (joshxg) [reply src/pages/SupplierRequisitionPage.js]: 4c1e0134ca34a3f9557f29ac5b7d00b556874679

`Date(null)` gives the earliest possible timestamp

File: src/pages/SupplierRequisitionPage.js [hunk 37]
```diff
@@ -357,6 +372,84 @@ export class SupplierRequisitionPage extends React.Component {
...
+    const openVialWastage = transactionBatchesCI.sum('numberOfPacks') * dosesInVial - doses;
+    const closeVialWastage = transactionBatchesIA.sum('numberOfPacks') * dosesInVial;
+
+    // Initialise columns for rendering expansion.
+
+    const infoColumns = [
+      [
+        {
+          title: `Previous Requisition Date:`,
+          info: prevRequisitionDate ? dateFormater(prevRequisitionDate, 'dd/mm/yy') : 'n/a',
```
[the remark this answers is not in the document]
Comment (joshxg) [reply src/pages/SupplierRequisitionPage.js]: 435d858252709b404ecc7bffbe732e1794c3ba91

File: src/pages/VaccineModuleAdminPage.js [hunk 38]
```diff
@@ -0,0 +1,214 @@
...
+  }
+
+  componentDidMount() {
+    this.refresh();
+  }
+
+  refresh = () => {
+    const { database } = this.props;
+    const locationTypes = database.objects('FridgeLocationType');
+    // TODO Warn here that there are not location types of fridge
```
[the remark this answers is not in the document]
Comment (joshxg) [reply src/pages/VaccineModuleAdminPage.js]: Not sure how to do this. Possibly there should be a validation check when opening the vaccine module page - checking if there is a `fridge`, a `location type`, the `fridge` related to the `location type` etc etc?

File: src/pages/VaccineModuleAdminPage.js [hunk 39]
```diff
@@ -0,0 +1,214 @@
...
+    this.setState({ fridges, sensors, hasSensors });
+  };
+
+  selectSensor = fridge => {
+    this.setState({ currentFridge: fridge, isModalOpen: true });
+  };
+
+  onSensorSelection = ({ item: sensor }) => {
+    const { database } = this.props;
+    const { currentFridge: location, sensors } = this.state;
```
[the remark this answers is not in the document]
Comment (joshxg) [reply src/pages/VaccineModuleAdminPage.js]: d7a0370e652be249fa399e3a84e28b0c66104bbf

File: src/pages/VaccineModuleAdminPage.js (hunk 15 above)
Comment (joshxg) [reply src/pages/VaccineModuleAdminPage.js]: 2cb8c2679e121575e3a8149ab4a69251278a0861

File: src/pages/VaccineModulePage.js [hunk 40]
```diff
@@ -102,156 +108,156 @@ export class VaccineModulePage extends React.Component {
...
 
-  renderNumberOfBreaches = ({ numBreaches }) => {
-    const { greyTextStyleSmall, greyTextStyleLarge, fridgeInfoContainer } = localStyles;
-    return (
-      <View style={{ ...fridgeInfoContainer, width: '15%' }}>
-        <SimpleText style={greyTextStyleSmall}>{`${LOCALIZATION.misc.breaches}:`}</SimpleText>
-        <SimpleText style={{ ...greyTextStyleLarge, width: '50%' }}>{numBreaches}</SimpleText>
-      </View>
-    );
+  blinkSensor = async () => {
```
[the remark this answers is not in the document]
Comment (joshxg) [reply src/pages/VaccineModulePage.js]: just thinking about multiple sensors .. ?

File: src/pages/VaccineModulePage.js [hunk 41]
```diff
@@ -102,156 +108,156 @@ export class VaccineModulePage extends React.Component {
...
+    const { selectedFridge } = this.state;
+    const { database, runWithLoadingIndicator } = this.props;
+    const sensors = database.objects('Sensor').filtered('location.id = $0', selectedFridge.id);
```
[the remark this answers is not in the document]
Comment (joshxg) [reply src/pages/VaccineModulePage.js]: c339e159e9848d45bc659d281da9a3a69a39cb5b

File: src/pages/VaccineModulePage.js [hunk 42]
```diff
@@ -102,156 +108,156 @@ export class VaccineModulePage extends React.Component {
...
-      <View style={{ flexDirection: 'row' }}>
-        {this.renderFridgeName(props)}
-        <View style={fridgeExtraInfoContainer}>
-          {renderNumBreaches && this.renderNumberOfBreaches({ numBreaches })}
-          {renderExposure && this.renderTemperatureExposure({ minTemperature, maxTemperature })}
-          {this.renderFridgeStock(props)}
-        </View>
+      <View style={[fridgeInfoSectionStyle, extraInfoSectionStyle]}>
+        {hasBreaches && (
+          <View style={[fridgeInfoSectionStyle, { marginRight: 10 }]}>
```
[the remark this answers is not in the document]
Comment (joshxg) [reply src/pages/VaccineModulePage.js]: huh

File: src/pages/VaccineModulePage.js [hunk 43]
```diff
@@ -102,156 +108,156 @@ export class VaccineModulePage extends React.Component {
...
-    const hasSensorLogs = minLine && maxLine;
-    return hasSensorLogs ? (
-      <VaccineChart {...chartData} onHazardPress={this.onHazardPress} />
-    ) : (
-      <View style={localStyles.noFridgesContainerStyle}>
-        <Text style={localStyles.greyTextStyleLarge}>
-          {LOCALIZATION.misc.noRecordedTemperatures}
-        </Text>
-      </View>
+  /* Render 'Breach: {num} Exposure: {fromTemp} to {toTemp} */
```
[the remark this answers is not in the document]
Comment (joshxg) [reply src/pages/VaccineModulePage.js]: 10c7ec0d6a10a11ef95bd485d54eaa3ef5f50d47

File: src/pages/VaccineModulePage.js [hunk 44]
```diff
@@ -277,10 +283,12 @@ export class VaccineModulePage extends React.Component {
...
 
   render() {
-    const { fridges, hasFridges } = this;
-    const { isModalOpen, currentBreach } = this.state;
+    const { FRIDGES, HAS_FRIDGES } = this;
+    const { navigateTo, isInAdminMode } = this.props;
+    const { isModalOpen, currentBreach, selectedFridge } = this.state;
     const { pageContainerStyle, sectionStyle, imageStyle, greyTextStyleLarge } = localStyles;
 
+    if (!selectedFridge) return null;
```
[the remark this answers is not in the document]
Comment (joshxg) [reply src/pages/VaccineModulePage.js]: This is primarily for rendering running before `componentDidMount` has run - maybe im confused, I'll tkae another look

File: src/sync/incomingSyncUtils.js [hunk 45]
```diff
@@ -664,7 +653,7 @@ export const createOrUpdateRecord = (database, settings, recordType, record) =>
     }
     case 'StocktakeBatch': {
       const stocktake = database.getOrCreate('Stocktake', record.stock_take_ID);
-      const packSize = parseNumber(record.snapshot_packsize);
+      const packSize = 1;
```
[the remark this answers is not in the document]
Comment (joshxg) [reply src/sync/incomingSyncUtils.js]: f2e6172aff37456ba0365687de49831e40b9bbf3

File: src/utilities/modules/vaccines/aggregation.js [hunk 46]
```diff
@@ -0,0 +1,212 @@
...
+        endTimestamp = new Date(endTimestamp.getTime() + PREAGGREGATE_INTERVAL);
+      }
+      logsToDelete = [...logsToDelete, ...logsToDeleteTemp];
+      logsToDeleteTemp = [{ ...sensorLog }];
+      logsToAdd.push(
+        createGenericSensorLog({
+          sensor,
+          location,
+          temperature,
+          timestamp: endTimestamp,
```
[the remark this answers is not in the document]
Comment (joshxg) [reply src/utilities/modules/vaccines/aggregation.js]: 801e7eafa6a1f1b1a3314dcf114317fd2fddbe84

File: src/utilities/modules/vaccines/aggregation.js (hunk 16 above)
Comment (joshxg) [reply src/utilities/modules/vaccines/aggregation.js]: Because realm are live records I quite like using clones 

ce984a71cc3e5878294bf06f16ce5f86ce5a820b

File: src/utilities/modules/vaccines/aggregation.js (hunk 21 above)
Comment (joshxg) [reply src/utilities/modules/vaccines/aggregation.js]: 29139aa2be0ef208c88e8346ba57a196e42ff388

File: src/utilities/modules/vaccines/chartHelpers.js [hunk 47]
```diff
@@ -226,22 +229,20 @@ export const sensorLogsExtractBatches = ({ sensorLogs = [], itemBatch, item, dat
   // Also return the sensorLogs for these items and batches.
   // If no items or batches have been found, items: [] is returned
   return {
+    id: sensorLogs.map(({ id }) => id).join(),
```
[the remark this answers is not in the document]
Comment (joshxg) [reply src/utilities/modules/vaccines/chartHelpers.js]: I believe this is just making a unique id as a key

File: src/utilities/modules/vaccines/sensorSynchroniser.js [hunk 48]
```diff
@@ -0,0 +1,88 @@
...
+  if (!(downloadedLogs && downloadedLogs.success)) {
+    updateMessage({ message: 'Failed to sync temperature data' });
+    return;
+  }
+
+  database.write(() => {
+    database.update('Sensor', {
+      id: sensor.id,
+      lastConnectionTimestamp: new Date(),
+      ...downloadedLogs.data[0],
```
[the remark this answers is not in the document]
Comment (joshxg) [reply src/utilities/modules/vaccines/sensorSynchroniser.js]: Can put whatever data in and only what is needed in the schema is extracted out, javascript...!

File: src/utilities/modules/vaccines/utilities.js [hunk 49]
```diff
@@ -0,0 +1,346 @@
...
+ * After grouping the breaches, determine if each group exceeds the given
+ * duration required for a breach. If so, set each aggregation field to
+ * breachAggregate, link all itemBatches in the location of the sensorlog.
+ * @param {Sensor}   sensor   Sensor object for breaches to be created
+ * @param {database} database App wide database accessor
+ */
+export function createBreaches({ sensor, database }) {
+  const { sensorLogs, location } = sensor;
+  // Early return where there are no sensor logs or location
+  if (!(sensorLogs || sensorLogs.length || location)) return null;
```
[the remark this answers is not in the document]
Comment (joshxg) [reply src/utilities/modules/vaccines/utilities.js]: d60914d4a8398106fdefbb4a5b9c8cd504cc167c

File: src/utilities/modules/vaccines/sensorSynchroniser.js [hunk 50]
```diff
@@ -0,0 +1,88 @@
...
+    updateMessage({
+      message: 'Temperature sync successfull, but failure during aggregation',
+      progress: 45,
+    });
+    return;
+  }
+
+  updateMessage({ message: 'Searching for breaches', progress: 50 });
+  const breachesResult = await createBreaches({ sensor, database });
+  if (!breachesResult.success) {
```
[the remark this answers is not in the document]
Comment (joshxg) [reply src/utilities/modules/vaccines/sensorSynchroniser.js]: a524671385123ad3dbc00635138b23bf0bc3ed2e

**Comment by joshxg** [comment]
Creating breaches: I have added a method which will return either an empty array or the last breach in an array so the breach can just be carried on. I don't know what you mean in regard to a breach 'just ending' - if so, the code is such that the last tail log will also be a head log?

Preaggregation: I did quite a bit of testing regarding the un-aggregated log. I could only figure out that if there aren't enough logs to create a pre-aggregate then one won't be created. I think this is the desired behaviour? Possibly the condition should be `<` over `<=` so that there doesn't need to be an 'extra' log in order for aggregation to occur

File: src/pages/VaccineModulePage.js [hunk 51]
```diff
@@ -102,156 +108,156 @@ export class VaccineModulePage extends React.Component {
...
+    this.setState({ currentBreach: [sensorLogs], isModalOpen: true });
+  };
+
+  /* Fridge and all of it's components */
   renderFridge = fridge => {
-    const { selectedFridge } = this.state;
     const { database } = this.props;
-    const fridgeChartData = extractDataForFridgeChart({ database, fridge });
+    const fridgeChartData = this.FRIDGE_DATA[fridge.id];
+    if (!fridgeChartData) return null;
```
[the remark this answers is not in the document]
Comment (joshxg) [reply src/pages/VaccineModulePage.js]: image


So I added this for protection on rendering as the data is retrieved in `componentDidMount` (fetching this elsewhere can lead to inconsistent behavior in react). This method can technically be called before the data has been fetched. A re-render is caused by the selected fridge state after it has been fetched. However you're right that if there are no fridges, nothing is rendered. Fridges are added in the VM admin page though.

Do you think displaying 'No fridges' or something like that?

File: src/pages/VaccineModulePage.js (hunk 44 above)
[the remark this answers is not in the document]
Comment (joshxg) [reply src/pages/VaccineModulePage.js]: image


Ended up doing this - show this component when fridges aren't there or theres not fridge data. Not happy with implementation so I will go back to it but seeing how you like it 

6638afa0771da124840ab7b26ae1f1cc74c27f47

File: src/pages/VaccineModulePage.js (hunk 51 above)
[the remark this answers is not in the document]
Comment (joshxg) [reply src/pages/VaccineModulePage.js]: see https://github.com/openmsupply/mobile/pull/1078#discussion_r312784862

File: src/utilities/modules/vaccines/aggregation.js (hunk 17 above)
Comment (joshxg) [reply src/utilities/modules/vaccines/aggregation.js]: This variable is keeping track of the minimum temperature. I've updated the naming to reflect that better: 0c3b9e6e26ac41d7ee35031eb2f676cdeb573031

File: src/database/DataTypes/Sensor.js (hunk 2 above)
Comment (joshxg) [reply src/database/DataTypes/Sensor.js]: 5de77427f7b82a154ab6eb0a0cfdf812acb57ffd

File: src/pages/VaccineModuleAdminPage.js (hunk 15 above)
Comment (joshxg) [reply src/pages/VaccineModuleAdminPage.js]: oops im a muppet 0d7a82307d1ce49147acf1ece05779badae0e8ab

File: src/pages/VaccineModulePage.js (hunk 42 above)
[the remark this answers is not in the document]
Comment (joshxg) [reply src/pages/VaccineModulePage.js]: tbh I think this should be TODO to refactor, it's pretty messy, what do you think?

File: src/utilities/modules/vaccines/sensorSynchroniser.js [hunk 52]
```diff
@@ -0,0 +1,88 @@
+import { preAggregateLogs, doFullAggregation } from './aggregation';
+import { createSensorLogs, createBreaches } from './utilities';
+
+export const syncSensor = async ({ database, sensor, updateMessage }) => {
+  updateMessage({ message: 'Searching for sensor', progress: 0 });
```
[the remark this answers is not in the document]
Comment (joshxg) [reply src/utilities/modules/vaccines/sensorSynchroniser.js]: I think we can look at it again when we sort sync out in a new issue is that cool

**Comment by joshxg** [comment]
## Current vaccine issues 
- https://github.com/openmsupply/mobile/issues?q=is%3Aissue+is%3Aopen+label%3A%22Vaccine+Module%22

## New Issues
- sensor sync schedule
    - Issue: https://github.com/openmsupply/mobile/issues/985
- Sync into redux 
    - Issue: *not made*
- vaccine module admin page - no location type
    - Issue: *not made*
- no fridge/fridge data
    - Issue: *not made*
- aggregation based on location rather than sensor
    - Issue: *not made*

File: src/database/DataTypes/Sensor.js (hunk 2 above)
Comment (joshxg) [reply src/database/DataTypes/Sensor.js]: 7add042deeb8f01ae9fb27d714297eb888c6746d turns out you cant overload native module methods - so have reverted this. Want your opinion: Create two methods with different names in java and create a javascript method (probably in `Sensor` which would have an `if` to determine which method should be called?

**Comment by joshxg** [comment]
@andreievg I've done some clicking on a tablet and fixed some problems I made with the requested changes so some of the commits I replied with might not be 100%
